#!/bin/bash
#
#Dump pics_config config tables and import into specified database
backup_dir=/var/backups/
filename="pics_config_tbls.sql"
deploy_dir=${backup_dir}deployments/
cfg_file=${deploy_dir}config_tables.txt
cfg_tbls=
dumpfile=${backup_dir}${filename}
dumpdb="pics"

exec<$cfg_file
while read line
do
cfg_tbls="${cfg_tbls} $line"
done



echo "Dumping pics_config config tables"
/usr/bin/mysqldump $dumpdb $cfg_tbls > $dumpfile

#echo "Importing config tables to $dbname"
#/usr/bin/mysql $dbname < $dumpfile

#echo "Cleaning up dump files"
#/bin/rm $dumpfile

echo "done"

