-- -----------------------------------------------------------------------------------------------
-- THIS FILE IS FOR CHANGES TO CONFIG TABLES THAT CANNOT BE APPLIED UNTIL RELEASE TIME
-- EXAMPLES:
-- -- changing app_translation msgKeys
-- REFER TO config_tables.txt FOR A FULL LIST OF CONFIG TABLES
-- SEE upgrade.sql FOR NON-CONFIG CHANGES
-- -----------------------------------------------------------------------------------------------

-- PICS-3414 removing spaces from the msgKey in these translations
update app_translation set msgKey = "ContractorEdit.error.BrochureFormat" where msgKey = "ContractorEdit.error.Brochure Format";

-- PICS-3803
update audit_question set uniqueCode='policyExpirationDatePlus120' where id = 2952

-- PICS-3428 Product Assessment Questions
update audit_question set expirationDate=CURDATE() where id in (7662, 7663, 7678);
update audit_question set optionID=169 where id=7679;
update audit_question set optionID=170 where id=2444;
update app_translation set msgValue='What amount of risk do your services place on the health & safety of your employees?' where locale='en' and msgKey='AuditQuestion.2444.name';

-- PICS-3746
DELETE from app_translation where msgKey = 'ContractorAccount.city.fieldhelp';

-- PICS-3747
DELETE from app_translation where msgKey = 'ContractorAccount.zip.fieldhelp';

-- PICS-3749
DELETE from app_translation where msgKey = 'User.email.fieldhelp';

-- PICS-3750
DELETE from app_translation where msgKey = 'User.phone.fieldhelp';

INSERT into app_translation (msgKey, locale, msgValue) values ("RegistrationServiceEvaluation.ServicesPerformed", "en", "Services Performed");
INSERT into app_translation (msgKey, locale, msgValue) values ("RegistrationServiceEvaluation.SelectServices", "en", "Please select <i>all</i> services that your company performs. It is common to select more than one.");
INSERT into app_translation (msgKey, locale, msgValue) values ("RegistrationServiceEvaluation.SoleProprietor", "en", "Are you a sole proprietor with no employees? (A sole proprietor means you do not employee anyone and do not pay any employees (this includes administrative help))");
INSERT into app_translation (msgKey, locale, msgValue) values ("RegistrationServiceEvaluation.BidOnly", "en", "Are you bid only?");
INSERT into app_translation (msgKey, locale, msgValue) values ("RegistrationServiceEvaluation.ServiceSafety", "en", "Service Safety Evaluation");
INSERT into app_translation (msgKey, locale, msgValue) values ("RegistrationServiceEvaluation.ProductSafety", "en", "Product and Safety Evaluation");
--
INSERT into app_translation (msgKey, locale, msgValue) values ("ContractorTrades.NeedsUpdating", "en", "Please select all applicable trades that apply to your company. Completing this portion of the process is very important as it will help ensure the proper risk ranking and will also allow existing/new clients to find you via your selected trades");
--
UPDATE app_translation set msgValue='Does your company perform services that require the operation of equipment and/or machinery at your client(s) facility? ' where locale='en' and msgKey='AuditQuestion.2442.name';
UPDATE audit_question set optionID = 170 where id = 2444;
UPDATE audit_question set optionID = 169 where id = 7679;
--
INSERT into app_translation (msgKey, locale, msgValue) values ("button.Save&Next", "en", "Save & Next");
INSERT into app_translation (msgKey, locale, msgValue) values ("button.SaveNext", "en", "Save & Next");
INSERT into app_translation (msgKey, locale, msgValue) values ("button.SubmitPayment", "en", "Submit Payment");
INSERT into app_translation (msgKey, locale, msgValue) values ("button.GetStarted", "en", "Get Started");
--
INSERT into app_translation (msgKey, locale, msgValue) values ("RegistrationAddClientSite.AnyOtherSites", "en", "Are there any other client sites you work for?");
INSERT into app_translation (msgKey, locale, msgValue) values ("RegistrationAddClientSite.SearchSuggest", "en", "Start by using the search above or using the suggest feature.");
--
UPDATE app_translation set msgValue="<p>The name of your company as listed on legal documents, trade certificates and licenses</p><br /><p>We'll search our database to see if your company has already been registered.</p><br /><p>If your formal name has a business number in its title, use your marketing name and list your business number as the DBA. </p>" where locale='en' and msgKey='ContractorAccount.name.fieldhelp';
UPDATE app_translation set msgValue="Your company's primary address or headquarters. This should be located in the country you selected in Company Details above.<br /><br /><h5>Example:</h5> 123 Main Street, Suite 100 " where locale='en' and msgKey='ContractorAccount.address.fieldhelp';
UPDATE app_translation set msgValue="<p>Please type in your desired user name. <br />We'll let you know if it's available.</p><br /> <ul> <li>Must be at least 3 characters long</li> <li>Don't use spaces in your name</li> <li>Your email address is recommended because it's easy to remember.</li> </ul>" where locale='en' and msgKey='User.username.fieldhelp';
UPDATE app_translation set msgValue="Les réponses que vous avez fournies indiquent les niveaux de risque plus élevé que les évaluations que vous avez sélectionné. Nous recommandons d'augmenter votre {0}. Vous pouvez toujours continuer avec le processus d'inscription. <br /> S'il vous plaît contactez PICS avec toutes les questions." where msgKey = "ContractorRegistrationServices.message.RiskLevels" and locale='fr';
--
INSERT into app_translation (msgKey, locale, msgValue) values ("RegistrationAddClientSite.SearchInstructions", "en", "Enter the name or location of your client site");
--
INSERT into app_translation (msgKey, locale, msgValue) values ("ContractorAccount.onsiteServices.withDescription", "en", "Onsite Services: You perform services at a physical location controlled by your client (examples include refineries, plants, pipelines, docks/piers, oil rig, construction sites, mines, administration buildings).");
INSERT into app_translation (msgKey, locale, msgValue) values ("ContractorAccount.offsiteServices.withDescription", "en", "Offsite Services:  You perform services for your client at <i>your</i> location(s) (examples of offsite locations include labs, warehouses, fabrication shops, engineering, maintenance).");
INSERT into app_translation (msgKey, locale, msgValue) values ("ContractorAccount.materialSupplier.withDescription", "en", "Material Supplier:  You supply, manufacture, sell, or distribute product(s) to your client (examples include chemicals, equipment, software, furniture, consumables). ");
INSERT into app_translation (msgKey, locale, msgValue) values ("ContractorAccount.transportationServices.withDescription", "en", "Transportation Services:  You provide transportation services (examples include shuttle, courier, tanker, delivery, hauler, charter, rail).");
-- --------------------------------------------------------
-- Updating timezones and countries
update app_translation set msgValue = 'Heure du Pacifique (US / Canada)', updatedBy = 24143, updateDate = NOW() WHERE msgKey = 'TimeZone.US.Pacific' AND locale = 'fr';
update app_translation set msgValue = 'Heure d''été Magadan (Asie)', updatedBy = 24143, updateDate = NOW() WHERE msgKey = 'TimeZone.Asia.Magadan' AND locale = 'fr';
update app_translation set msgValue = 'GMT-12: 00 (GMT +12)', updatedBy = 24143, updateDate = NOW() WHERE msgKey = 'TimeZone.Etc.GMT+12' AND locale = 'fr';
update app_translation set msgValue = 'Samoa Heure Normale (Pacifique)', updatedBy = 24143, updateDate = NOW() WHERE msgKey = 'TimeZone.Pacific.Samoa' AND locale = 'fr';
update app_translation set msgValue = 'Hawaï Standard Time (Honolulu)', updatedBy = 24143, updateDate = NOW() WHERE msgKey = 'TimeZone.Pacific.Honolulu' AND locale = 'fr';
update app_translation set msgValue = 'Temps Tahiti (Pacifique)', updatedBy = 24143, updateDate = NOW() WHERE msgKey = 'TimeZone.Pacific.Tahiti' AND locale = 'fr';
update app_translation set msgValue = 'Heure avancée de Hawaii Aléoutiennes (Etats-Unis)', updatedBy = 24143, updateDate = NOW() WHERE msgKey = 'TimeZone.US.Aleutian' AND locale = 'fr';
update app_translation set msgValue = 'Alaska Heure Normale (YST9)', updatedBy = 24143, updateDate = NOW() WHERE msgKey = 'TimeZone.SystemV.YST9' AND locale = 'fr';
update app_translation set msgValue = 'Heure avancée de l''Alaska (États-Unis)', updatedBy = 24143, updateDate = NOW() WHERE msgKey = 'TimeZone.US.Alaska' AND locale = 'fr';
update app_translation set msgValue = 'Heure normale des Rocheuses (Arizona)', updatedBy = 24143, updateDate = NOW() WHERE msgKey = 'TimeZone.US.Arizona' AND locale = 'fr';
update app_translation set msgValue = 'Heure avancée des Rocheuses (USA / Canada)', updatedBy = 24143, updateDate = NOW() WHERE msgKey = 'TimeZone.US.Mountain' AND locale = 'fr';
update app_translation set msgValue = 'Heure Normale du Centre (Saskatchewan)', updatedBy = 24143, updateDate = NOW() WHERE msgKey = 'TimeZone.Canada.Saskatchewan' AND locale = 'fr';
update app_translation set msgValue = 'Heure avancée du Centre (Bahia_Banderas)', updatedBy = 24143, updateDate = NOW() WHERE msgKey = 'TimeZone.America.Bahia_Banderas' AND locale = 'fr';
update app_translation set msgValue = 'Heure avancée du Centre (US / Canada)', updatedBy = 24143, updateDate = NOW() WHERE msgKey = 'TimeZone.US.Central' AND locale = 'fr';
update app_translation set msgValue = 'Heure normale de l''est (Port-au-Prince)', updatedBy = 24143, updateDate = NOW() WHERE msgKey = 'TimeZone.America.Port-au-Prince' AND locale = 'fr';
update app_translation set msgValue = 'Heure avancée de l''est(US / Canada)', updatedBy = 24143, updateDate = NOW() WHERE msgKey = 'TimeZone.US.Eastern' AND locale = 'fr';
update app_translation set msgValue = 'Heure du Venezuela  (Caracas)', updatedBy = 24143, updateDate = NOW() WHERE msgKey = 'TimeZone.America.Caracas' AND locale = 'fr';
update app_translation set msgValue = 'Heure de Bolivie  (La Paz)', updatedBy = 24143, updateDate = NOW() WHERE msgKey = 'TimeZone.America.La_Paz' AND locale = 'fr';
update app_translation set msgValue = 'Heure du Chili Temps (Santiago)', updatedBy = 24143, updateDate = NOW() WHERE msgKey = 'TimeZone.America.Santiago' AND locale = 'fr';
update app_translation set msgValue = 'Heure d'' Argentine (Buenos Aires)', updatedBy = 24143, updateDate = NOW() WHERE msgKey = 'TimeZone.America.Argentina.Buenos_Aires' AND locale = 'fr';
update app_translation set msgValue = 'Heure de Brasilia  (Sao Paulo)', updatedBy = 24143, updateDate = NOW() WHERE msgKey = 'TimeZone.America.Sao_Paulo' AND locale = 'fr';
update app_translation set msgValue = 'Heure avancée de Terre-Neuve (Canada)', updatedBy = 24143, updateDate = NOW() WHERE msgKey = 'TimeZone.Canada.Newfoundland' AND locale = 'fr';
update app_translation set msgValue = 'Heure d''été de l''ouest Groenland (Godthab)', updatedBy = 24143, updateDate = NOW() WHERE msgKey = 'TimeZone.America.Godthab' AND locale = 'fr';
update app_translation set msgValue = 'Heure de Fernando de Noronha (DeNoronha)', updatedBy = 24143, updateDate = NOW() WHERE msgKey = 'TimeZone.Brazil.DeNoronha' AND locale = 'fr';
update app_translation set msgValue = 'Heure médiane de Greenwich', updatedBy = 24143, updateDate = NOW() WHERE msgKey = 'TimeZone.Greenwich' AND locale = 'fr';
update app_translation set msgValue = 'Temps universel coordonné (UTC)', updatedBy = 24143, updateDate = NOW() WHERE msgKey = 'TimeZone.Etc.UTC' AND locale = 'fr';
update app_translation set msgValue = 'Heure d''été britannique (Londres)', updatedBy = 24143, updateDate = NOW() WHERE msgKey = 'TimeZone.Europe.London' AND locale = 'fr';
update app_translation set msgValue = 'Heure de l''Afrique de l''Ouest (Lagos)', updatedBy = 24143, updateDate = NOW() WHERE msgKey = 'TimeZone.Africa.Lagos' AND locale = 'fr';
update app_translation set msgValue = 'Heure de l''Afrique de l''Ouest (Windhoek)', updatedBy = 24143, updateDate = NOW() WHERE msgKey = 'TimeZone.Africa.Windhoek' AND locale = 'fr';
update app_translation set msgValue = 'Heure d''été de l''Europe centrale (Paris)', updatedBy = 24143, updateDate = NOW() WHERE msgKey = 'TimeZone.Europe.Paris' AND locale = 'fr';
update app_translation set msgValue = 'Heure d''Europe (Tripoli)', updatedBy = 24143, updateDate = NOW() WHERE msgKey = 'TimeZone.Africa.Tripoli' AND locale = 'fr';
update app_translation set msgValue = 'Heure avancée d''Israël (Jérusalem)', updatedBy = 24143, updateDate = NOW() WHERE msgKey = 'TimeZone.Asia.Jerusalem' AND locale = 'fr';
update app_translation set msgValue = 'Heure normale Saoudite (Riyad)', updatedBy = 24143, updateDate = NOW() WHERE msgKey = 'TimeZone.Asia.Riyadh' AND locale = 'fr';
update app_translation set msgValue = 'Heure avancée de Moscou (Europe)', updatedBy = 24143, updateDate = NOW() WHERE msgKey = 'TimeZone.Europe.Moscow' AND locale = 'fr';
update app_translation set msgValue = 'Heure avancée d''Iran (Téhéran)', updatedBy = 24143, updateDate = NOW() WHERE msgKey = 'TimeZone.Asia.Tehran' AND locale = 'fr';
update app_translation set msgValue = 'Heure normale du Golfe (Dubaï)', updatedBy = 24143, updateDate = NOW() WHERE msgKey = 'TimeZone.Asia.Dubai' AND locale = 'fr';
update app_translation set msgValue = 'Heure de Géorgie (Tbilissi)', updatedBy = 24143, updateDate = NOW() WHERE msgKey = 'TimeZone.Asia.Tbilisi' AND locale = 'fr';
update app_translation set msgValue = 'Heure de l''Afghanistan (Kaboul)', updatedBy = 24143, updateDate = NOW() WHERE msgKey = 'TimeZone.Asia.Kabul' AND locale = 'fr';
update app_translation set msgValue = 'Heure du Pakistan (Karachi)', updatedBy = 24143, updateDate = NOW() WHERE msgKey = 'TimeZone.Asia.Karachi' AND locale = 'fr';
update app_translation set msgValue = 'Heure normale de l''Inde (Kolkata)', updatedBy = 24143, updateDate = NOW() WHERE msgKey = 'TimeZone.Asia.Kolkata' AND locale = 'fr';
update app_translation set msgValue = 'Heure du Népal (Katmandou)', updatedBy = 24143, updateDate = NOW() WHERE msgKey = 'TimeZone.Asia.Kathmandu' AND locale = 'fr';
update app_translation set msgValue = 'Heure du Kirghizstan (Bichkek)', updatedBy = 24143, updateDate = NOW() WHERE msgKey = 'TimeZone.Asia.Bishkek' AND locale = 'fr';
update app_translation set msgValue = 'Heure de Alma-Ata (Almaty)', updatedBy = 24143, updateDate = NOW() WHERE msgKey = 'TimeZone.Asia.Almaty' AND locale = 'fr';
update app_translation set msgValue = 'Heure du Myanmar (Rangoon)', updatedBy = 24143, updateDate = NOW() WHERE msgKey = 'TimeZone.Asia.Rangoon' AND locale = 'fr';
update app_translation set msgValue = 'Heure d''Indochine (Bangkok)', updatedBy = 24143, updateDate = NOW() WHERE msgKey = 'TimeZone.Asia.Bangkok' AND locale = 'fr';
update app_translation set msgValue = 'Heure d''Hovd (Asie)', updatedBy = 24143, updateDate = NOW() WHERE msgKey = 'TimeZone.Asia.Hovd' AND locale = 'fr';
update app_translation set msgValue = 'Heure normale de Chine (Shanghai)', updatedBy = 24143, updateDate = NOW() WHERE msgKey = 'TimeZone.Asia.Shanghai' AND locale = 'fr';
update app_translation set msgValue = 'Heure normale de l''ouest central (Australie) (Eucla)', updatedBy = 24143, updateDate = NOW() WHERE msgKey = 'TimeZone.Australia.Eucla' AND locale = 'fr';
update app_translation set msgValue = 'Heure d''été d''Irkoutsk (Asie)', updatedBy = 24143, updateDate = NOW() WHERE msgKey = 'TimeZone.Asia.Irkutsk' AND locale = 'fr';
update app_translation set msgValue = 'Heure normale du Japon (Tokyo)', updatedBy = 24143, updateDate = NOW() WHERE msgKey = 'TimeZone.Asia.Tokyo' AND locale = 'fr';
update app_translation set msgValue = 'Heure normale du Centre (Northern Territory) (Darwin)', updatedBy = 24143, updateDate = NOW() WHERE msgKey = 'TimeZone.Australia.Darwin' AND locale = 'fr';
update app_translation set msgValue = 'Heure normale du Centre (South Australia) (Adelaide)', updatedBy = 24143, updateDate = NOW() WHERE msgKey = 'TimeZone.Australia.Adelaide' AND locale = 'fr';
update app_translation set msgValue = 'Heure normale de l''est (Queensland) (Brisbane)', updatedBy = 24143, updateDate = NOW() WHERE msgKey = 'TimeZone.Australia.Brisbane' AND locale = 'fr';
update app_translation set msgValue = 'Heure normale de l''est (Nouvelle-Galles du Sud) (Sydney)', updatedBy = 24143, updateDate = NOW() WHERE msgKey = 'TimeZone.Australia.Sydney' AND locale = 'fr';
update app_translation set msgValue = 'Heure normale de Lord Howe (Lord_Howe)', updatedBy = 24143, updateDate = NOW() WHERE msgKey = 'TimeZone.Australia.Lord_Howe' AND locale = 'fr';
update app_translation set msgValue = 'Heure de Fidji (Pacifique)', updatedBy = 24143, updateDate = NOW() WHERE msgKey = 'TimeZone.Pacific.Fiji' AND locale = 'fr';
update app_translation set msgValue = 'Heure normale de Nouvelle-Zélande (Auckland)', updatedBy = 24143, updateDate = NOW() WHERE msgKey = 'TimeZone.Pacific.Auckland' AND locale = 'fr';
update app_translation set msgValue = 'Heure des Marquises (Pacifique)', updatedBy = 24143, updateDate = NOW() WHERE msgKey = 'TimeZone.Pacific.Marquesas' AND locale = 'fr';
update app_translation set msgValue = 'Heure normale de Pitcairn', updatedBy = 24143, updateDate = NOW() WHERE msgKey = 'TimeZone.Pacific.Pitcairn' AND locale = 'fr';
update app_translation set msgValue = 'Heure des Galapagos (Pacifique)', updatedBy = 24143, updateDate = NOW() WHERE msgKey = 'TimeZone.Pacific.Galapagos' AND locale = 'fr';
update app_translation set msgValue = 'Heure de l''Île de Pâques (Pacifique)', updatedBy = 24143, updateDate = NOW() WHERE msgKey = 'TimeZone.Pacific.Easter' AND locale = 'fr';
update app_translation set msgValue = 'Heure avancée de l''Atlantique (Bermudes)', updatedBy = 24143, updateDate = NOW() WHERE msgKey = 'TimeZone.Atlantic.Bermuda' AND locale = 'fr';
update app_translation set msgValue = 'Heure du Cap-Vert (Cape Verde)', updatedBy = 24143, updateDate = NOW() WHERE msgKey = 'TimeZone.Atlantic.Cape_Verde' AND locale = 'fr';
update app_translation set msgValue = 'Heure d''été des Açores (Atlantique)', updatedBy = 24143, updateDate = NOW() WHERE msgKey = 'TimeZone.Atlantic.Azores' AND locale = 'fr';
update app_translation set msgValue = 'Heure normale d''Inde (Colombo)', updatedBy = 24143, updateDate = NOW() WHERE msgKey = 'TimeZone.Asia.Colombo' AND locale = 'fr';
update app_translation set msgValue = 'Heure d''été de Yakoutsk (Asie)', updatedBy = 24143, updateDate = NOW() WHERE msgKey = 'TimeZone.Asia.Yakutsk' AND locale = 'fr';
update app_translation set msgValue = 'Heure d''été de Vladivostok (Asie)', updatedBy = 24143, updateDate = NOW() WHERE msgKey = 'TimeZone.Asia.Vladivostok' AND locale = 'fr';
update app_translation set msgValue = 'Heure de Pohnpei (Pacifique)', updatedBy = 24143, updateDate = NOW() WHERE msgKey = 'TimeZone.Pacific.Pohnpei' AND locale = 'fr';
update app_translation set msgValue = 'Heure de Norfolk (Pacifique)', updatedBy = 24143, updateDate = NOW() WHERE msgKey = 'TimeZone.Pacific.Norfolk' AND locale = 'fr';
update app_translation set msgValue = 'Heure d''été d''Anadyr (Asie)', updatedBy = 24143, updateDate = NOW() WHERE msgKey = 'TimeZone.Asia.Anadyr' AND locale = 'fr';
update app_translation set msgValue = 'Heure normale de Chatham (Pacifique)', updatedBy = 24143, updateDate = NOW() WHERE msgKey = 'TimeZone.Pacific.Chatham' AND locale = 'fr';
update app_translation set msgValue = 'Heure de Tonga (Tongatapu)', updatedBy = 24143, updateDate = NOW() WHERE msgKey = 'TimeZone.Pacific.Tongatapu' AND locale = 'fr';
update app_translation set msgValue = 'Heure de la Ligne Est (Kiritimati)', updatedBy = 24143, updateDate = NOW() WHERE msgKey = 'TimeZone.Pacific.Kiritimati' AND locale = 'fr';
update app_translation set msgValue = 'Pays', updatedBy = 24143, updateDate = NOW() where msgKey = 'ContractorAccount.country.isoCode' and locale = 'fr';
update app_translation set msgValue = '<p> Le siège social de votre compagnie. Cela confirmera la devise à utiliser pour votre compte PICS. </p>', updatedBy = 24143, updateDate = NOW() where msgKey = 'ContractorAccount.country.isoCode.fieldhelp' and locale = 'fr';
update app_translation set msgValue = 'Pays de l''entreprise.<br /><b>Ce champ est obligatoire.</b>', updatedBy = 24143, updateDate = NOW() where msgKey = 'ContractorRegistrationRequest.country.fieldhelp' and locale = 'fr';
update app_translation set msgValue = 'Andorre', updatedBy = 24143, updateDate = NOW() where msgKey = 'Country.AD' and locale = 'fr';
update app_translation set msgValue = 'Émirats Arabes Unis', updatedBy = 24143, updateDate = NOW() where msgKey = 'Country.AE' and locale = 'fr';
update app_translation set msgValue = 'Afghanistan', updatedBy = 24143, updateDate = NOW() where msgKey = 'Country.AF' and locale = 'fr';
update app_translation set msgValue = 'Antigua-et-Barbuda', updatedBy = 24143, updateDate = NOW() where msgKey = 'Country.AG' and locale = 'fr';
update app_translation set msgValue = 'Anguilla', updatedBy = 24143, updateDate = NOW() where msgKey = 'Country.AI' and locale = 'fr';
update app_translation set msgValue = 'Albanie', updatedBy = 24143, updateDate = NOW() where msgKey = 'Country.AL' and locale = 'fr';
update app_translation set msgValue = 'Arménie', updatedBy = 24143, updateDate = NOW() where msgKey = 'Country.AM' and locale = 'fr';
update app_translation set msgValue = 'Antilles Néerlandaises', updatedBy = 24143, updateDate = NOW() where msgKey = 'Country.AN' and locale = 'fr';
update app_translation set msgValue = 'Angola', updatedBy = 24143, updateDate = NOW() where msgKey = 'Country.AO' and locale = 'fr';
update app_translation set msgValue = 'Antarctique', updatedBy = 24143, updateDate = NOW() where msgKey = 'Country.AQ' and locale = 'fr';
update app_translation set msgValue = 'Argentine', updatedBy = 24143, updateDate = NOW() where msgKey = 'Country.AR' and locale = 'fr';
update app_translation set msgValue = 'Samoa Américaines', updatedBy = 24143, updateDate = NOW() where msgKey = 'Country.AS' and locale = 'fr';
update app_translation set msgValue = 'Autriche', updatedBy = 24143, updateDate = NOW() where msgKey = 'Country.AT' and locale = 'fr';
update app_translation set msgValue = 'Australie', updatedBy = 24143, updateDate = NOW() where msgKey = 'Country.AU' and locale = 'fr';
update app_translation set msgValue = 'Aruba', updatedBy = 24143, updateDate = NOW() where msgKey = 'Country.AW' and locale = 'fr';
update app_translation set msgValue = 'Îles Åland', updatedBy = 24143, updateDate = NOW() where msgKey = 'Country.AX' and locale = 'fr';
update app_translation set msgValue = 'Azerbaïdjan', updatedBy = 24143, updateDate = NOW() where msgKey = 'Country.AZ' and locale = 'fr';
update app_translation set msgValue = 'Bosnie-Hérzégovine', updatedBy = 24143, updateDate = NOW() where msgKey = 'Country.BA' and locale = 'fr';
update app_translation set msgValue = 'Barbade', updatedBy = 24143, updateDate = NOW() where msgKey = 'Country.BB' and locale = 'fr';
update app_translation set msgValue = 'Bangladesh', updatedBy = 24143, updateDate = NOW() where msgKey = 'Country.BD' and locale = 'fr';
update app_translation set msgValue = 'Bélgique', updatedBy = 24143, updateDate = NOW() where msgKey = 'Country.BE' and locale = 'fr';
update app_translation set msgValue = 'Burkina Faso', updatedBy = 24143, updateDate = NOW() where msgKey = 'Country.BF' and locale = 'fr';
update app_translation set msgValue = 'Bulgarie', updatedBy = 24143, updateDate = NOW() where msgKey = 'Country.BG' and locale = 'fr';
update app_translation set msgValue = 'Bahreïn', updatedBy = 24143, updateDate = NOW() where msgKey = 'Country.BH' and locale = 'fr';
update app_translation set msgValue = 'Burundi', updatedBy = 24143, updateDate = NOW() where msgKey = 'Country.BI' and locale = 'fr';
update app_translation set msgValue = 'Bénin', updatedBy = 24143, updateDate = NOW() where msgKey = 'Country.BJ' and locale = 'fr';
update app_translation set msgValue = 'Saint-Barthélemy', updatedBy = 24143, updateDate = NOW() where msgKey = 'Country.BL' and locale = 'fr';
update app_translation set msgValue = 'Bermudes', updatedBy = 24143, updateDate = NOW() where msgKey = 'Country.BM' and locale = 'fr';
update app_translation set msgValue = 'Brunei Darussalam', updatedBy = 24143, updateDate = NOW() where msgKey = 'Country.BN' and locale = 'fr';
update app_translation set msgValue = 'Bolivie', updatedBy = 24143, updateDate = NOW() where msgKey = 'Country.BO' and locale = 'fr';
update app_translation set msgValue = 'Brésil', updatedBy = 24143, updateDate = NOW() where msgKey = 'Country.BR' and locale = 'fr';
update app_translation set msgValue = 'Bahreïn', updatedBy = 24143, updateDate = NOW() where msgKey = 'Country.BS' and locale = 'fr';
update app_translation set msgValue = 'Bhoutan', updatedBy = 24143, updateDate = NOW() where msgKey = 'Country.BT' and locale = 'fr';
update app_translation set msgValue = 'Ile Bouvet', updatedBy = 24143, updateDate = NOW() where msgKey = 'Country.BV' and locale = 'fr';
update app_translation set msgValue = 'Botswana', updatedBy = 24143, updateDate = NOW() where msgKey = 'Country.BW' and locale = 'fr';
update app_translation set msgValue = 'Biélorussie', updatedBy = 24143, updateDate = NOW() where msgKey = 'Country.BY' and locale = 'fr';
update app_translation set msgValue = 'Bélize', updatedBy = 24143, updateDate = NOW() where msgKey = 'Country.BZ' and locale = 'fr';
update app_translation set msgValue = 'Canada', updatedBy = 24143, updateDate = NOW() where msgKey = 'Country.CA' and locale = 'fr';
update app_translation set msgValue = 'Iles Cocos', updatedBy = 24143, updateDate = NOW() where msgKey = 'Country.CC' and locale = 'fr';
update app_translation set msgValue = 'République Démocratique du Congo', updatedBy = 24143, updateDate = NOW() where msgKey = 'Country.CD' and locale = 'fr';
update app_translation set msgValue = 'République Centrafricaine', updatedBy = 24143, updateDate = NOW() where msgKey = 'Country.CF' and locale = 'fr';
update app_translation set msgValue = 'République du Congo', updatedBy = 24143, updateDate = NOW() where msgKey = 'Country.CG' and locale = 'fr';
update app_translation set msgValue = 'Suisse', updatedBy = 24143, updateDate = NOW() where msgKey = 'Country.CH' and locale = 'fr';
update app_translation set msgValue = 'Côte d''Ivoire', updatedBy = 24143, updateDate = NOW() where msgKey = 'Country.CI' and locale = 'fr';
update app_translation set msgValue = 'Iles Cook', updatedBy = 24143, updateDate = NOW() where msgKey = 'Country.CK' and locale = 'fr';
update app_translation set msgValue = 'Chili', updatedBy = 24143, updateDate = NOW() where msgKey = 'Country.CL' and locale = 'fr';
update app_translation set msgValue = 'Cameroun', updatedBy = 24143, updateDate = NOW() where msgKey = 'Country.CM' and locale = 'fr';
update app_translation set msgValue = 'Chine', updatedBy = 24143, updateDate = NOW() where msgKey = 'Country.CN' and locale = 'fr';
update app_translation set msgValue = 'Colombie', updatedBy = 24143, updateDate = NOW() where msgKey = 'Country.CO' and locale = 'fr';
update app_translation set msgValue = 'Costa Rica', updatedBy = 24143, updateDate = NOW() where msgKey = 'Country.CR' and locale = 'fr';
update app_translation set msgValue = 'Cuba', updatedBy = 24143, updateDate = NOW() where msgKey = 'Country.CU' and locale = 'fr';
update app_translation set msgValue = 'Cap-Vert', updatedBy = 24143, updateDate = NOW() where msgKey = 'Country.CV' and locale = 'fr';
update app_translation set msgValue = 'Ile Christmas', updatedBy = 24143, updateDate = NOW() where msgKey = 'Country.CX' and locale = 'fr';
update app_translation set msgValue = 'Chypre', updatedBy = 24143, updateDate = NOW() where msgKey = 'Country.CY' and locale = 'fr';
update app_translation set msgValue = 'République Tchèque', updatedBy = 24143, updateDate = NOW() where msgKey = 'Country.CZ' and locale = 'fr';
update app_translation set msgValue = 'Allemagne', updatedBy = 24143, updateDate = NOW() where msgKey = 'Country.DE' and locale = 'fr';
update app_translation set msgValue = 'Djibouti', updatedBy = 24143, updateDate = NOW() where msgKey = 'Country.DJ' and locale = 'fr';
update app_translation set msgValue = 'Danemark', updatedBy = 24143, updateDate = NOW() where msgKey = 'Country.DK' and locale = 'fr';
update app_translation set msgValue = 'Dominique', updatedBy = 24143, updateDate = NOW() where msgKey = 'Country.DM' and locale = 'fr';
update app_translation set msgValue = 'République Dominicaine', updatedBy = 24143, updateDate = NOW() where msgKey = 'Country.DO' and locale = 'fr';
update app_translation set msgValue = 'Algérie', updatedBy = 24143, updateDate = NOW() where msgKey = 'Country.DZ' and locale = 'fr';
update app_translation set msgValue = 'Équateur', updatedBy = 24143, updateDate = NOW() where msgKey = 'Country.EC' and locale = 'fr';
update app_translation set msgValue = 'Estonie', updatedBy = 24143, updateDate = NOW() where msgKey = 'Country.EE' and locale = 'fr';
update app_translation set msgValue = 'Égypte', updatedBy = 24143, updateDate = NOW() where msgKey = 'Country.EG' and locale = 'fr';
update app_translation set msgValue = 'Sahara Occidental', updatedBy = 24143, updateDate = NOW() where msgKey = 'Country.EH' and locale = 'fr';
update app_translation set msgValue = 'Érythrée', updatedBy = 24143, updateDate = NOW() where msgKey = 'Country.ER' and locale = 'fr';
update app_translation set msgValue = 'Espagne', updatedBy = 24143, updateDate = NOW() where msgKey = 'Country.ES' and locale = 'fr';
update app_translation set msgValue = 'Éthiopie', updatedBy = 24143, updateDate = NOW() where msgKey = 'Country.ET' and locale = 'fr';
update app_translation set msgValue = 'Finlande', updatedBy = 24143, updateDate = NOW() where msgKey = 'Country.FI' and locale = 'fr';
update app_translation set msgValue = 'Fidji', updatedBy = 24143, updateDate = NOW() where msgKey = 'Country.FJ' and locale = 'fr';
update app_translation set msgValue = 'Iles Falklands', updatedBy = 24143, updateDate = NOW() where msgKey = 'Country.FK' and locale = 'fr';
update app_translation set msgValue = 'Micronésie', updatedBy = 24143, updateDate = NOW() where msgKey = 'Country.FM' and locale = 'fr';
update app_translation set msgValue = 'Iles Féroé', updatedBy = 24143, updateDate = NOW() where msgKey = 'Country.FO' and locale = 'fr';
update app_translation set msgValue = 'France', updatedBy = 24143, updateDate = NOW() where msgKey = 'Country.FR' and locale = 'fr';
update app_translation set msgValue = 'Gabon', updatedBy = 24143, updateDate = NOW() where msgKey = 'Country.GA' and locale = 'fr';
update app_translation set msgValue = 'Royaume-Uni', updatedBy = 24143, updateDate = NOW() where msgKey = 'Country.GB' and locale = 'fr';
update app_translation set msgValue = 'Grenade', updatedBy = 24143, updateDate = NOW() where msgKey = 'Country.GD' and locale = 'fr';
update app_translation set msgValue = 'Géorgie', updatedBy = 24143, updateDate = NOW() where msgKey = 'Country.GE' and locale = 'fr';
update app_translation set msgValue = 'Guyane Française', updatedBy = 24143, updateDate = NOW() where msgKey = 'Country.GF' and locale = 'fr';
update app_translation set msgValue = 'Guernesey', updatedBy = 24143, updateDate = NOW() where msgKey = 'Country.GG' and locale = 'fr';
update app_translation set msgValue = 'Ghana', updatedBy = 24143, updateDate = NOW() where msgKey = 'Country.GH' and locale = 'fr';
update app_translation set msgValue = 'Gibraltar', updatedBy = 24143, updateDate = NOW() where msgKey = 'Country.GI' and locale = 'fr';
update app_translation set msgValue = 'Groenland', updatedBy = 24143, updateDate = NOW() where msgKey = 'Country.GL' and locale = 'fr';
update app_translation set msgValue = 'Gambie', updatedBy = 24143, updateDate = NOW() where msgKey = 'Country.GM' and locale = 'fr';
update app_translation set msgValue = 'Guinée', updatedBy = 24143, updateDate = NOW() where msgKey = 'Country.GN' and locale = 'fr';
update app_translation set msgValue = 'Guadeloupe', updatedBy = 24143, updateDate = NOW() where msgKey = 'Country.GP' and locale = 'fr';
update app_translation set msgValue = 'Guinée Équatoriale', updatedBy = 24143, updateDate = NOW() where msgKey = 'Country.GQ' and locale = 'fr';
update app_translation set msgValue = 'Grèce', updatedBy = 24143, updateDate = NOW() where msgKey = 'Country.GR' and locale = 'fr';
update app_translation set msgValue = 'Géorgie du Sud-et-les Îles Sandwich', updatedBy = 24143, updateDate = NOW() where msgKey = 'Country.GS' and locale = 'fr';
update app_translation set msgValue = 'Guatemala', updatedBy = 24143, updateDate = NOW() where msgKey = 'Country.GT' and locale = 'fr';
update app_translation set msgValue = 'Guam', updatedBy = 24143, updateDate = NOW() where msgKey = 'Country.GU' and locale = 'fr';
update app_translation set msgValue = 'Guinée-Bissau', updatedBy = 24143, updateDate = NOW() where msgKey = 'Country.GW' and locale = 'fr';
update app_translation set msgValue = 'Guyane', updatedBy = 24143, updateDate = NOW() where msgKey = 'Country.GY' and locale = 'fr';
update app_translation set msgValue = 'Hong Kong', updatedBy = 24143, updateDate = NOW() where msgKey = 'Country.HK' and locale = 'fr';
update app_translation set msgValue = 'Îles Heard et McDonald', updatedBy = 24143, updateDate = NOW() where msgKey = 'Country.HM' and locale = 'fr';
update app_translation set msgValue = 'Honduras', updatedBy = 24143, updateDate = NOW() where msgKey = 'Country.HN' and locale = 'fr';
update app_translation set msgValue = 'Croatie', updatedBy = 24143, updateDate = NOW() where msgKey = 'Country.HR' and locale = 'fr';
update app_translation set msgValue = 'Haïti', updatedBy = 24143, updateDate = NOW() where msgKey = 'Country.HT' and locale = 'fr';
update app_translation set msgValue = 'Hongrie', updatedBy = 24143, updateDate = NOW() where msgKey = 'Country.HU' and locale = 'fr';
update app_translation set msgValue = 'Indonésie', updatedBy = 24143, updateDate = NOW() where msgKey = 'Country.ID' and locale = 'fr';
update app_translation set msgValue = 'Irlande', updatedBy = 24143, updateDate = NOW() where msgKey = 'Country.IE' and locale = 'fr';
update app_translation set msgValue = 'Israël', updatedBy = 24143, updateDate = NOW() where msgKey = 'Country.IL' and locale = 'fr';
update app_translation set msgValue = 'Île de Man', updatedBy = 24143, updateDate = NOW() where msgKey = 'Country.IM' and locale = 'fr';
update app_translation set msgValue = 'Inde', updatedBy = 24143, updateDate = NOW() where msgKey = 'Country.IN' and locale = 'fr';
update app_translation set msgValue = 'Territoire britannique de l''océan Indien', updatedBy = 24143, updateDate = NOW() where msgKey = 'Country.IO' and locale = 'fr';
update app_translation set msgValue = 'Irak', updatedBy = 24143, updateDate = NOW() where msgKey = 'Country.IQ' and locale = 'fr';
update app_translation set msgValue = 'Iran', updatedBy = 24143, updateDate = NOW() where msgKey = 'Country.IR' and locale = 'fr';
update app_translation set msgValue = 'Islande', updatedBy = 24143, updateDate = NOW() where msgKey = 'Country.IS' and locale = 'fr';
update app_translation set msgValue = 'Pays', updatedBy = 24143, updateDate = NOW() where msgKey = 'Country.isoCode' and locale = 'fr';
update app_translation set msgValue = '<p> Le siège social de votre compagnie. Cela confirmera la devise à utiliser pour votre compte PICS. </p>', updatedBy = 24143, updateDate = NOW() where msgKey = 'Country.isoCode.fieldhelp' and locale = 'fr';
update app_translation set msgValue = 'Italie', updatedBy = 24143, updateDate = NOW() where msgKey = 'Country.IT' and locale = 'fr';
update app_translation set msgValue = 'Jersey', updatedBy = 24143, updateDate = NOW() where msgKey = 'Country.JE' and locale = 'fr';
update app_translation set msgValue = 'Jamaïque', updatedBy = 24143, updateDate = NOW() where msgKey = 'Country.JM' and locale = 'fr';
update app_translation set msgValue = 'Jordanie', updatedBy = 24143, updateDate = NOW() where msgKey = 'Country.JO' and locale = 'fr';
update app_translation set msgValue = 'Japon', updatedBy = 24143, updateDate = NOW() where msgKey = 'Country.JP' and locale = 'fr';
update app_translation set msgValue = 'Kenya', updatedBy = 24143, updateDate = NOW() where msgKey = 'Country.KE' and locale = 'fr';
update app_translation set msgValue = 'Kirghizstan', updatedBy = 24143, updateDate = NOW() where msgKey = 'Country.KG' and locale = 'fr';
update app_translation set msgValue = 'Cambodge', updatedBy = 24143, updateDate = NOW() where msgKey = 'Country.KH' and locale = 'fr';
update app_translation set msgValue = 'Kiribati', updatedBy = 24143, updateDate = NOW() where msgKey = 'Country.KI' and locale = 'fr';
update app_translation set msgValue = 'Comores', updatedBy = 24143, updateDate = NOW() where msgKey = 'Country.KM' and locale = 'fr';
update app_translation set msgValue = 'Saint-Kitts-et-Nevis', updatedBy = 24143, updateDate = NOW() where msgKey = 'Country.KN' and locale = 'fr';
update app_translation set msgValue = 'Corée du Nord', updatedBy = 24143, updateDate = NOW() where msgKey = 'Country.KP' and locale = 'fr';
update app_translation set msgValue = 'Corée Sud', updatedBy = 24143, updateDate = NOW() where msgKey = 'Country.KR' and locale = 'fr';
update app_translation set msgValue = 'Koweït', updatedBy = 24143, updateDate = NOW() where msgKey = 'Country.KW' and locale = 'fr';
update app_translation set msgValue = 'Îles Caïmans', updatedBy = 24143, updateDate = NOW() where msgKey = 'Country.KY' and locale = 'fr';
update app_translation set msgValue = 'Kazakhstan', updatedBy = 24143, updateDate = NOW() where msgKey = 'Country.KZ' and locale = 'fr';
update app_translation set msgValue = 'Laos', updatedBy = 24143, updateDate = NOW() where msgKey = 'Country.LA' and locale = 'fr';
update app_translation set msgValue = 'Liban', updatedBy = 24143, updateDate = NOW() where msgKey = 'Country.LB' and locale = 'fr';
update app_translation set msgValue = 'Sainte-Lucie', updatedBy = 24143, updateDate = NOW() where msgKey = 'Country.LC' and locale = 'fr';
update app_translation set msgValue = 'Liechtenstein', updatedBy = 24143, updateDate = NOW() where msgKey = 'Country.LI' and locale = 'fr';
update app_translation set msgValue = 'Sri Lanka', updatedBy = 24143, updateDate = NOW() where msgKey = 'Country.LK' and locale = 'fr';
update app_translation set msgValue = 'Liberia', updatedBy = 24143, updateDate = NOW() where msgKey = 'Country.LR' and locale = 'fr';
update app_translation set msgValue = 'Lesotho', updatedBy = 24143, updateDate = NOW() where msgKey = 'Country.LS' and locale = 'fr';
update app_translation set msgValue = 'Lituanie', updatedBy = 24143, updateDate = NOW() where msgKey = 'Country.LT' and locale = 'fr';
update app_translation set msgValue = 'Luxembourg', updatedBy = 24143, updateDate = NOW() where msgKey = 'Country.LU' and locale = 'fr';
update app_translation set msgValue = 'Lettonie', updatedBy = 24143, updateDate = NOW() where msgKey = 'Country.LV' and locale = 'fr';
update app_translation set msgValue = 'Libye', updatedBy = 24143, updateDate = NOW() where msgKey = 'Country.LY' and locale = 'fr';
update app_translation set msgValue = 'Maroc', updatedBy = 24143, updateDate = NOW() where msgKey = 'Country.MA' and locale = 'fr';
update app_translation set msgValue = 'Monaco', updatedBy = 24143, updateDate = NOW() where msgKey = 'Country.MC' and locale = 'fr';
update app_translation set msgValue = 'Moldavie', updatedBy = 24143, updateDate = NOW() where msgKey = 'Country.MD' and locale = 'fr';
update app_translation set msgValue = 'Monténégro', updatedBy = 24143, updateDate = NOW() where msgKey = 'Country.ME' and locale = 'fr';
update app_translation set msgValue = 'Saint-Martin', updatedBy = 24143, updateDate = NOW() where msgKey = 'Country.MF' and locale = 'fr';
update app_translation set msgValue = 'Madagascar', updatedBy = 24143, updateDate = NOW() where msgKey = 'Country.MG' and locale = 'fr';
update app_translation set msgValue = 'Iles Marshall', updatedBy = 24143, updateDate = NOW() where msgKey = 'Country.MH' and locale = 'fr';
update app_translation set msgValue = 'Macédoine', updatedBy = 24143, updateDate = NOW() where msgKey = 'Country.MK' and locale = 'fr';
update app_translation set msgValue = 'Mali', updatedBy = 24143, updateDate = NOW() where msgKey = 'Country.ML' and locale = 'fr';
update app_translation set msgValue = 'Myanmar', updatedBy = 24143, updateDate = NOW() where msgKey = 'Country.MM' and locale = 'fr';
update app_translation set msgValue = 'Mongolie', updatedBy = 24143, updateDate = NOW() where msgKey = 'Country.MN' and locale = 'fr';
update app_translation set msgValue = 'Macao', updatedBy = 24143, updateDate = NOW() where msgKey = 'Country.MO' and locale = 'fr';
update app_translation set msgValue = 'Iles Mariannes du Nord', updatedBy = 24143, updateDate = NOW() where msgKey = 'Country.MP' and locale = 'fr';
update app_translation set msgValue = 'Martinique', updatedBy = 24143, updateDate = NOW() where msgKey = 'Country.MQ' and locale = 'fr';
update app_translation set msgValue = 'Mauritanie', updatedBy = 24143, updateDate = NOW() where msgKey = 'Country.MR' and locale = 'fr';
update app_translation set msgValue = 'Monserrat', updatedBy = 24143, updateDate = NOW() where msgKey = 'Country.MS' and locale = 'fr';
update app_translation set msgValue = 'Malte', updatedBy = 24143, updateDate = NOW() where msgKey = 'Country.MT' and locale = 'fr';
update app_translation set msgValue = 'Ile Maurice', updatedBy = 24143, updateDate = NOW() where msgKey = 'Country.MU' and locale = 'fr';
update app_translation set msgValue = 'Maldives', updatedBy = 24143, updateDate = NOW() where msgKey = 'Country.MV' and locale = 'fr';
update app_translation set msgValue = 'Malawi', updatedBy = 24143, updateDate = NOW() where msgKey = 'Country.MW' and locale = 'fr';
update app_translation set msgValue = 'Mexique', updatedBy = 24143, updateDate = NOW() where msgKey = 'Country.MX' and locale = 'fr';
update app_translation set msgValue = 'Malaisie', updatedBy = 24143, updateDate = NOW() where msgKey = 'Country.MY' and locale = 'fr';
update app_translation set msgValue = 'Mozambique', updatedBy = 24143, updateDate = NOW() where msgKey = 'Country.MZ' and locale = 'fr';
update app_translation set msgValue = 'Namibie', updatedBy = 24143, updateDate = NOW() where msgKey = 'Country.NA' and locale = 'fr';
update app_translation set msgValue = 'Nouvelle-Calédonie', updatedBy = 24143, updateDate = NOW() where msgKey = 'Country.NC' and locale = 'fr';
update app_translation set msgValue = 'Niger', updatedBy = 24143, updateDate = NOW() where msgKey = 'Country.NE' and locale = 'fr';
update app_translation set msgValue = 'Île de Norfolk', updatedBy = 24143, updateDate = NOW() where msgKey = 'Country.NF' and locale = 'fr';
update app_translation set msgValue = 'Nigeria', updatedBy = 24143, updateDate = NOW() where msgKey = 'Country.NG' and locale = 'fr';
update app_translation set msgValue = 'Nicaragua', updatedBy = 24143, updateDate = NOW() where msgKey = 'Country.NI' and locale = 'fr';
update app_translation set msgValue = 'Pays-Bas', updatedBy = 24143, updateDate = NOW() where msgKey = 'Country.NL' and locale = 'fr';
update app_translation set msgValue = 'Norvège', updatedBy = 24143, updateDate = NOW() where msgKey = 'Country.NO' and locale = 'fr';
update app_translation set msgValue = 'Népal', updatedBy = 24143, updateDate = NOW() where msgKey = 'Country.NP' and locale = 'fr';
update app_translation set msgValue = 'Nauru', updatedBy = 24143, updateDate = NOW() where msgKey = 'Country.NR' and locale = 'fr';
update app_translation set msgValue = 'Nioué', updatedBy = 24143, updateDate = NOW() where msgKey = 'Country.NU' and locale = 'fr';
update app_translation set msgValue = 'Nouvelle-Zélande', updatedBy = 24143, updateDate = NOW() where msgKey = 'Country.NZ' and locale = 'fr';
update app_translation set msgValue = 'Oman', updatedBy = 24143, updateDate = NOW() where msgKey = 'Country.OM' and locale = 'fr';
update app_translation set msgValue = 'Panama', updatedBy = 24143, updateDate = NOW() where msgKey = 'Country.PA' and locale = 'fr';
update app_translation set msgValue = 'Pérou', updatedBy = 24143, updateDate = NOW() where msgKey = 'Country.PE' and locale = 'fr';
update app_translation set msgValue = 'Polynésie Française', updatedBy = 24143, updateDate = NOW() where msgKey = 'Country.PF' and locale = 'fr';
update app_translation set msgValue = 'Papouasie-Nouvelle-Guinée', updatedBy = 24143, updateDate = NOW() where msgKey = 'Country.PG' and locale = 'fr';
update app_translation set msgValue = 'Philippines', updatedBy = 24143, updateDate = NOW() where msgKey = 'Country.PH' and locale = 'fr';
update app_translation set msgValue = 'Pakistan', updatedBy = 24143, updateDate = NOW() where msgKey = 'Country.PK' and locale = 'fr';
update app_translation set msgValue = 'Pologne', updatedBy = 24143, updateDate = NOW() where msgKey = 'Country.PL' and locale = 'fr';
update app_translation set msgValue = 'Saint-Pierre-et-Miquelon', updatedBy = 24143, updateDate = NOW() where msgKey = 'Country.PM' and locale = 'fr';
update app_translation set msgValue = 'Pitcairn', updatedBy = 24143, updateDate = NOW() where msgKey = 'Country.PN' and locale = 'fr';
update app_translation set msgValue = 'Puerto Rico', updatedBy = 24143, updateDate = NOW() where msgKey = 'Country.PR' and locale = 'fr';
update app_translation set msgValue = 'Territoires palestiniens', updatedBy = 24143, updateDate = NOW() where msgKey = 'Country.PS' and locale = 'fr';
update app_translation set msgValue = 'Portugal', updatedBy = 24143, updateDate = NOW() where msgKey = 'Country.PT' and locale = 'fr';
update app_translation set msgValue = 'Palau', updatedBy = 24143, updateDate = NOW() where msgKey = 'Country.PW' and locale = 'fr';
update app_translation set msgValue = 'Paraguay', updatedBy = 24143, updateDate = NOW() where msgKey = 'Country.PY' and locale = 'fr';
update app_translation set msgValue = 'Qatar', updatedBy = 24143, updateDate = NOW() where msgKey = 'Country.QA' and locale = 'fr';
update app_translation set msgValue = 'Ile de la Réunion', updatedBy = 24143, updateDate = NOW() where msgKey = 'Country.RE' and locale = 'fr';
update app_translation set msgValue = 'Roumanie', updatedBy = 24143, updateDate = NOW() where msgKey = 'Country.RO' and locale = 'fr';
update app_translation set msgValue = 'Sérbie', updatedBy = 24143, updateDate = NOW() where msgKey = 'Country.RS' and locale = 'fr';
update app_translation set msgValue = 'Russie', updatedBy = 24143, updateDate = NOW() where msgKey = 'Country.RU' and locale = 'fr';
update app_translation set msgValue = 'Rwanda', updatedBy = 24143, updateDate = NOW() where msgKey = 'Country.RW' and locale = 'fr';
update app_translation set msgValue = 'Arabie Saoudite', updatedBy = 24143, updateDate = NOW() where msgKey = 'Country.SA' and locale = 'fr';
update app_translation set msgValue = 'Iles Salomon', updatedBy = 24143, updateDate = NOW() where msgKey = 'Country.SB' and locale = 'fr';
update app_translation set msgValue = 'Séychèlles', updatedBy = 24143, updateDate = NOW() where msgKey = 'Country.SC' and locale = 'fr';
update app_translation set msgValue = 'Soudan', updatedBy = 24143, updateDate = NOW() where msgKey = 'Country.SD' and locale = 'fr';
update app_translation set msgValue = 'Suède', updatedBy = 24143, updateDate = NOW() where msgKey = 'Country.SE' and locale = 'fr';
update app_translation set msgValue = 'Singapour', updatedBy = 24143, updateDate = NOW() where msgKey = 'Country.SG' and locale = 'fr';
update app_translation set msgValue = 'Sainte-Hélène', updatedBy = 24143, updateDate = NOW() where msgKey = 'Country.SH' and locale = 'fr';
update app_translation set msgValue = 'Slovénie', updatedBy = 24143, updateDate = NOW() where msgKey = 'Country.SI' and locale = 'fr';
update app_translation set msgValue = 'Svalbard et Ile Jan Mayen', updatedBy = 24143, updateDate = NOW() where msgKey = 'Country.SJ' and locale = 'fr';
update app_translation set msgValue = 'Slovaquie', updatedBy = 24143, updateDate = NOW() where msgKey = 'Country.SK' and locale = 'fr';
update app_translation set msgValue = 'Sierra Leone', updatedBy = 24143, updateDate = NOW() where msgKey = 'Country.SL' and locale = 'fr';
update app_translation set msgValue = 'San Marino', updatedBy = 24143, updateDate = NOW() where msgKey = 'Country.SM' and locale = 'fr';
update app_translation set msgValue = 'Sénègal', updatedBy = 24143, updateDate = NOW() where msgKey = 'Country.SN' and locale = 'fr';
update app_translation set msgValue = 'Somalie', updatedBy = 24143, updateDate = NOW() where msgKey = 'Country.SO' and locale = 'fr';
update app_translation set msgValue = 'Surinam', updatedBy = 24143, updateDate = NOW() where msgKey = 'Country.SR' and locale = 'fr';
update app_translation set msgValue = 'Sao Tomé-et-Principe', updatedBy = 24143, updateDate = NOW() where msgKey = 'Country.ST' and locale = 'fr';
update app_translation set msgValue = 'Salvador', updatedBy = 24143, updateDate = NOW() where msgKey = 'Country.SV' and locale = 'fr';
update app_translation set msgValue = 'Syrie', updatedBy = 24143, updateDate = NOW() where msgKey = 'Country.SY' and locale = 'fr';
update app_translation set msgValue = 'Swaziland', updatedBy = 24143, updateDate = NOW() where msgKey = 'Country.SZ' and locale = 'fr';
update app_translation set msgValue = 'Iles Turques-et-Caïques', updatedBy = 24143, updateDate = NOW() where msgKey = 'Country.TC' and locale = 'fr';
update app_translation set msgValue = 'Tchad', updatedBy = 24143, updateDate = NOW() where msgKey = 'Country.TD' and locale = 'fr';
update app_translation set msgValue = 'Térritoires du Sud Français', updatedBy = 24143, updateDate = NOW() where msgKey = 'Country.TF' and locale = 'fr';
update app_translation set msgValue = 'Togo', updatedBy = 24143, updateDate = NOW() where msgKey = 'Country.TG' and locale = 'fr';
update app_translation set msgValue = 'Thaïlande', updatedBy = 24143, updateDate = NOW() where msgKey = 'Country.TH' and locale = 'fr';
update app_translation set msgValue = 'Tadjikistan', updatedBy = 24143, updateDate = NOW() where msgKey = 'Country.TJ' and locale = 'fr';
update app_translation set msgValue = 'Tokelau', updatedBy = 24143, updateDate = NOW() where msgKey = 'Country.TK' and locale = 'fr';
update app_translation set msgValue = 'Timor-Leste', updatedBy = 24143, updateDate = NOW() where msgKey = 'Country.TL' and locale = 'fr';
update app_translation set msgValue = 'Turkménistan', updatedBy = 24143, updateDate = NOW() where msgKey = 'Country.TM' and locale = 'fr';
update app_translation set msgValue = 'Tunisie', updatedBy = 24143, updateDate = NOW() where msgKey = 'Country.TN' and locale = 'fr';
update app_translation set msgValue = 'Tonga', updatedBy = 24143, updateDate = NOW() where msgKey = 'Country.TO' and locale = 'fr';
update app_translation set msgValue = 'Turquie', updatedBy = 24143, updateDate = NOW() where msgKey = 'Country.TR' and locale = 'fr';
update app_translation set msgValue = 'Trinidad-et-Tobago', updatedBy = 24143, updateDate = NOW() where msgKey = 'Country.TT' and locale = 'fr';
update app_translation set msgValue = 'Tuvalu', updatedBy = 24143, updateDate = NOW() where msgKey = 'Country.TV' and locale = 'fr';
update app_translation set msgValue = 'Taïwan', updatedBy = 24143, updateDate = NOW() where msgKey = 'Country.TW' and locale = 'fr';
update app_translation set msgValue = 'Tanzanie', updatedBy = 24143, updateDate = NOW() where msgKey = 'Country.TZ' and locale = 'fr';
update app_translation set msgValue = 'Ukraine', updatedBy = 24143, updateDate = NOW() where msgKey = 'Country.UA' and locale = 'fr';
update app_translation set msgValue = 'Ouganda', updatedBy = 24143, updateDate = NOW() where msgKey = 'Country.UG' and locale = 'fr';
update app_translation set msgValue = 'Îles mineures des États-Unis', updatedBy = 24143, updateDate = NOW() where msgKey = 'Country.UM' and locale = 'fr';
update app_translation set msgValue = 'États-Unis', updatedBy = 24143, updateDate = NOW() where msgKey = 'Country.US' and locale = 'fr';
update app_translation set msgValue = 'Uruguay', updatedBy = 24143, updateDate = NOW() where msgKey = 'Country.UY' and locale = 'fr';
update app_translation set msgValue = 'Ouzbékistan', updatedBy = 24143, updateDate = NOW() where msgKey = 'Country.UZ' and locale = 'fr';
update app_translation set msgValue = 'Saint-Siège', updatedBy = 24143, updateDate = NOW() where msgKey = 'Country.VA' and locale = 'fr';
update app_translation set msgValue = 'Saint-Vincent-et-les-Grenadines', updatedBy = 24143, updateDate = NOW() where msgKey = 'Country.VC' and locale = 'fr';
update app_translation set msgValue = 'Vénézuéla', updatedBy = 24143, updateDate = NOW() where msgKey = 'Country.VE' and locale = 'fr';
update app_translation set msgValue = 'Îles Vierges britanniques', updatedBy = 24143, updateDate = NOW() where msgKey = 'Country.VG' and locale = 'fr';
update app_translation set msgValue = 'Îles majeures des États-Unis', updatedBy = 24143, updateDate = NOW() where msgKey = 'Country.VI' and locale = 'fr';
update app_translation set msgValue = 'Vietnam', updatedBy = 24143, updateDate = NOW() where msgKey = 'Country.VN' and locale = 'fr';
update app_translation set msgValue = 'Vanuatu', updatedBy = 24143, updateDate = NOW() where msgKey = 'Country.VU' and locale = 'fr';
update app_translation set msgValue = 'Wallis-et-Futuna', updatedBy = 24143, updateDate = NOW() where msgKey = 'Country.WF' and locale = 'fr';
update app_translation set msgValue = 'Samoa', updatedBy = 24143, updateDate = NOW() where msgKey = 'Country.WS' and locale = 'fr';
update app_translation set msgValue = 'Yémen', updatedBy = 24143, updateDate = NOW() where msgKey = 'Country.YE' and locale = 'fr';
update app_translation set msgValue = 'Mayotte', updatedBy = 24143, updateDate = NOW() where msgKey = 'Country.YT' and locale = 'fr';
update app_translation set msgValue = 'Afrique du Sud', updatedBy = 24143, updateDate = NOW() where msgKey = 'Country.ZA' and locale = 'fr';
update app_translation set msgValue = 'Zambie', updatedBy = 24143, updateDate = NOW() where msgKey = 'Country.ZM' and locale = 'fr';
update app_translation set msgValue = 'Zimbabwe', updatedBy = 24143, updateDate = NOW() where msgKey = 'Country.ZW' and locale = 'fr';
update app_translation set msgValue = '<p>Veuillez sélectionner le pays dans lequel l''opérateur est situé. Cela détermine la configuration par pays héritée de PICS.</p>', updatedBy = 24143, updateDate = NOW() where msgKey = 'OperatorAccount.country.fieldhelp' and locale = 'fr';
update app_translation set msgValue = 'Créer un compte', updatedBy = 24143, updateDate = NOW() where msgKey = 'ContractorRegistration.button.CreateAccount' and locale = 'fr';
update app_translation set msgValue = 'Informations sur la compagnie', updatedBy = 24143, updateDate = NOW() where msgKey = 'ContractorRegistration.CompanyDetails.heading' and locale = 'fr';
update app_translation set msgValue = 'Identification de l''entreprise', updatedBy = 24143, updateDate = NOW() where msgKey = 'ContractorRegistration.CompanyIdentification.heading' and locale = 'fr';
update app_translation set msgValue = 'Le nom <b>{0}</b> existe déjà. S&#39;il vous plaît contacter un représentant PICS.', updatedBy = 24143, updateDate = NOW() where msgKey = 'ContractorRegistration.error.DuplicateContractorName' and locale = 'fr';
update app_translation set msgValue = 'Vous devez vous déconnecter avant de tenter d&#39;enregistrer un nouveau compte.', updatedBy = 24143, updateDate = NOW() where msgKey = 'ContractorRegistration.error.LogoutBeforRegistering' and locale = 'fr';
update app_translation set msgValue = 'S&#39;il vous plaît remplir le champ Mot de passe.', updatedBy = 24143, updateDate = NOW() where msgKey = 'ContractorRegistration.error.NoPassword' and locale = 'fr';
update app_translation set msgValue = 'Indique un champ requis', updatedBy = 24143, updateDate = NOW() where msgKey = 'ContractorRegistration.IndicatesRequiredInfo' and locale = 'fr';
update app_translation set msgValue = 'Produit ou service', updatedBy = 24143, updateDate = NOW() where msgKey = 'ContractorRegistration.IndustryDetails.heading' and locale = 'fr';
update app_translation set msgValue = 'Métier ou service principal', updatedBy = 24143, updateDate = NOW() where msgKey = 'ContractorRegistration.IndustryDetails.MainTrade' and locale = 'fr';
update app_translation set msgValue = 'Pays', updatedBy = 24143, updateDate = NOW() where msgKey = 'ContractorRegistration.PrimaryAddress.Country' and locale = 'fr';
update app_translation set msgValue = 'Adresse principale', updatedBy = 24143, updateDate = NOW() where msgKey = 'ContractorRegistration.PrimaryAddress.heading' and locale = 'fr';
update app_translation set msgValue = 'Personne-ressource', updatedBy = 24143, updateDate = NOW() where msgKey = 'ContractorRegistration.PrimaryContact.heading' and locale = 'fr';
update app_translation set msgValue = 'Propriétaire unique', updatedBy = 24143, updateDate = NOW() where msgKey = 'ContractorRegistration.SoleProprietor.heading' and locale = 'fr';
update app_translation set msgValue = 'En cliquant sur <span style="color: #529214; font-family: ''Lucida Grande'', Tahoma, Arial">[Créer un compte]</span> ci-dessous, je certifie que je suis d''accord avec les termes et conditions de <a href="#" onclick="window.open(''ContractorAgreement.action?request_locale=fr'',''name'',''toolbar=0,scrollbars=1,location=0,statusbar=0,menubar=0,resizable=1,width=700,height=700''); return false;" class="ext"> Accords de l''entrepreneur PICS</a>.', updatedBy = 24143, updateDate = NOW() where msgKey = 'ContractorRegistration.TermsAndConditions' and locale = 'fr';
update app_translation set msgValue = 'Enregistrement de la compagnie', updatedBy = 24143, updateDate = NOW() where msgKey = 'ContractorRegistration.title' and locale = 'fr';
update app_translation set msgValue = 'Veuillez inclure tout autre détail utile à l''entrepreneur pour s''enregistrer. Indiquez l''étendue des travaux et un échéancier au besoin. Ceci est essentiel pour avoir du succès avec les inscriptions.', updatedBy = 24143, updateDate = NOW() where msgKey = 'ContractorRegistrationRequest.reasonForRegistration.fieldhelp' and locale = 'fr';
update app_translation set msgValue = 'vérification la disponibilité du nom ...', updatedBy = 24143, updateDate = NOW() where msgKey = 'JS.Registration.CheckingName' and locale = 'fr';
update app_translation set msgValue = 'vérification de la disponibilité du numéro d''identification fiscale ...', updatedBy = 24143, updateDate = NOW() where msgKey = 'JS.Registration.CheckingTaxID' and locale = 'fr';
update app_translation set msgValue = 'vérification de la disponibilité du nom d''utilisateur ...', updatedBy = 24143, updateDate = NOW() where msgKey = 'JS.Registration.CheckingUsername' and locale = 'fr';
update app_translation set msgValue = 'Enregistrement de Entrepreneur', updatedBy = 24143, updateDate = NOW() where msgKey = 'Subscription.ContractorRegistration.description' and locale = 'fr';
update app_translation set msgValue = 'Ce courriel inclut une liste d''entrepreneurs qui se sont récemment enregistrés sur PICS et liés à votre compte. Vous pouvez choisir de le recevoir quotidiennement, hebdomadairement ou mensuellement. Si aucun entrepreneur ne s''est enregistré, vous ne recevrez pas de courriel.', updatedBy = 24143, updateDate = NOW() where msgKey = 'Subscription.ContractorRegistration.longDescription' and locale = 'fr';
insert into app_translation (msgKey, msgValue, locale, createdBy, creationDate) values ('Registration.AgreeTC', 'En cliquant sur Débuter, vous donnez votre accords avec les termes et conditions  <a href="#" class="contractor-agreement modal-link" data-title="Contractor Agreement" data-url="ContractorAgreement.action">PICS Contractor Agreement</a>.', 'fr', 24143, NOW());
insert into app_translation (msgKey, msgValue, locale, createdBy, creationDate) values ('Registration.BecomeAMember', 'Devenez membre de PICS maintenant !', 'fr', 24143, NOW());
insert into app_translation (msgKey, msgValue, locale, createdBy, creationDate) values ('Registration.CompanyDetails.heading', 'Traduction manquante', 'fr', 24143, NOW());
insert into app_translation (msgKey, msgValue, locale, createdBy, creationDate) values ('Registration.CompanyInformation', 'Informations sur la compagnie', 'fr', 24143, NOW());
insert into app_translation (msgKey, msgValue, locale, createdBy, creationDate) values ('Registration.ContactInformation', 'Contact principal', 'fr', 24143, NOW());
insert into app_translation (msgKey, msgValue, locale, createdBy, creationDate) values ('Registration.CountryCount', '16 Pays', 'fr', 24143, NOW());
insert into app_translation (msgKey, msgValue, locale, createdBy, creationDate) values ('Registration.JoinInfo', 'Vous n''êtes qu''à quelques clics de<br />de joindre le réseau d''entrepreneurs <br /> avec la croissance la plus rapide au monde.', 'fr', 24143, NOW());
insert into app_translation (msgKey, msgValue, locale, createdBy, creationDate) values ('Registration.ModalBody', 'One fine body…', 'fr', 24143, NOW());
insert into app_translation (msgKey, msgValue, locale, createdBy, creationDate) values ('Registration.ModalHeading', 'Modal Heading', 'fr', 24143, NOW());
insert into app_translation (msgKey, msgValue, locale, createdBy, creationDate) values ('Registration.NeedHelp', 'Besoin d''aide pour vous enregistrer?', 'fr', 24143, NOW());
insert into app_translation (msgKey, msgValue, locale, createdBy, creationDate) values ('Registration.OperatorCount', '850 Clients/Opérateurs', 'fr', 24143, NOW());
insert into app_translation (msgKey, msgValue, locale, createdBy, creationDate) values ('Registration.PICSCompanies', 'Compagnies qui utilisent PICS', 'fr', 24143, NOW());
insert into app_translation (msgKey, msgValue, locale, createdBy, creationDate) values ('Registration.Qualify', 'Se qualifer<br />grâce à PICS', 'fr', 24143, NOW());
insert into app_translation (msgKey, msgValue, locale, createdBy, creationDate) values ('Registration.Questions', 'Pour toutes questions, écrivez-nous à <a href="#">support@picsauditing.com</a>, appeler nous au (800) 506-PICS (7427) ou clavarder avec l''un de nos représentants.', 'fr', 24143, NOW());
insert into app_translation (msgKey, msgValue, locale, createdBy, creationDate) values ('Registration.Reason1', 'Se  préqualifer pour un projet ou un travail', 'fr', 24143, NOW());
insert into app_translation (msgKey, msgValue, locale, createdBy, creationDate) values ('Registration.Reason2', 'Être exposé à plus de clients', 'fr', 24143, NOW());
insert into app_translation (msgKey, msgValue, locale, createdBy, creationDate) values ('Registration.Reason3', 'Prime d''assurance réduite', 'fr', 24143, NOW());
insert into app_translation (msgKey, msgValue, locale, createdBy, creationDate) values ('Registration.Reason4', 'Marketing pour votre compagnie', 'fr', 24143, NOW());
insert into app_translation (msgKey, msgValue, locale, createdBy, creationDate) values ('Registration.Reason5', 'Accès direct à des professionnels de la sécurité', 'fr', 24143, NOW());
insert into app_translation (msgKey, msgValue, locale, createdBy, creationDate) values ('Registration.Reason6', 'Technologie de logiciel simple et puissante', 'fr', 24143, NOW());
insert into app_translation (msgKey, msgValue, locale, createdBy, creationDate) values ('Registration.Reason7', 'Service à la clientèle expert', 'fr', 24143, NOW());
insert into app_translation (msgKey, msgValue, locale, createdBy, creationDate) values ('Registration.TheContractorsChoice', 'Le Choix des entrepreneurs', 'fr', 24143, NOW());
insert into app_translation (msgKey, msgValue, locale, createdBy, creationDate) values ('Registration.UserCount', '50,000 utilisateurs courants', 'fr', 24143, NOW());
insert into app_translation (msgKey, msgValue, locale, createdBy, creationDate) values ('Registration.Why', 'Pourquoi les entrepreneurs <br />choisissent PICS?', 'fr', 24143, NOW());
--

-- PICS-4056
-- remove extensions in questions
UPDATE app_translation set msgValue=replace(msgValue, '.docx', '') where msgValue like '%.docx%' and msgValue like '%forms/form%';
UPDATE app_translation set msgValue=replace(msgValue, '.xlsx', '') where msgValue like '%.xlsx%' and msgValue like '%forms/form%';
UPDATE app_translation set msgValue=replace(msgValue, '.pptx', '') where msgValue like '%.pptx%' and msgValue like '%forms/form%';
UPDATE app_translation set msgValue=replace(msgValue, '.pdf', '') where msgValue like '%.pdf%' and msgValue like '%forms/form%';
UPDATE app_translation set msgValue=replace(msgValue, '.doc', '') where msgValue like '%.doc%' and msgValue like '%forms/form%';
UPDATE app_translation set msgValue=replace(msgValue, '.xls', '') where msgValue like '%.xls%' and msgValue like '%forms/form%';
UPDATE app_translation set msgValue=replace(msgValue, '.ppt', '') where msgValue like '%.ppt%' and msgValue like '%forms/form%';
UPDATE app_translation set msgValue=replace(msgValue, '.zip', '') where msgValue like '%.zip%' and msgValue like '%forms/form%';
-- remove absolute url in questions
UPDATE app_translation set msgValue=replace(msgValue, 'http://www.picsorganizer.com/forms/form', 'forms/form') where msgValue like '%http://www.picsorganizer.com/forms/form%';
UPDATE app_translation set msgValue=replace(msgValue, 'https://www.picsorganizer.com/forms/form', 'forms/form') where msgValue like '%https://www.picsorganizer.com/forms/form%';
-- existing url in questions
update app_translation set msgValue=replace(msgValue, 'forms/form', 'Resources!download.action?id=') where msgValue like '%forms/form%';
-- update any existing references in translations
update app_translation set msgValue=replace(msgValue, 'Forms & Docs', 'Resources') where msgValue like '%Forms & Docs%';
-- remove extensions in email templates
UPDATE email_template set body=replace(body, '.docx', '') where body like '%.docx%' and body like '%forms/form%';
UPDATE email_template set body=replace(body, '.xlsx', '') where body like '%.xlsx%' and body like '%forms/form%';
UPDATE email_template set body=replace(body, '.pptx', '') where body like '%.pptx%' and body like '%forms/form%';
UPDATE email_template set body=replace(body, '.pdf', '') where body like '%.pdf%' and body like '%forms/form%';
UPDATE email_template set body=replace(body, '.doc', '') where body like '%.doc%' and body like '%forms/form%';
UPDATE email_template set body=replace(body, '.xls', '') where body like '%.xls%' and body like '%forms/form%';
UPDATE email_template set body=replace(body, '.ppt', '') where body like '%.ppt%' and body like '%forms/form%';
UPDATE email_template set body=replace(body, '.zip', '') where body like '%.zip%' and body like '%forms/form%';
-- update url in email templates
update email_template set body=replace(body, 'forms/form', 'Resources!download.action?id=') where body like '%forms/form%';
-- update any remaining names in email templates
update email_template set body=replace(body, 'Forms & Docs', 'Resources') where body like '%Forms & Docs%';
--
