--liquibase formatted SQL
--changeset sshacter:20
--
--	This SQL Must be run in the log_archive database!
--
USE log_archive
;
CREATE TABLE IF NOT EXISTS	log_event
(
  logDate BIGINT(20) NOT NULL 	COMMENT "Log transaction date in UNIX epoch format.",
  validStart DATE NOT NULL 	COMMENT "Start date this fact was valid in reality.",
  validFinish DATE NOT NULL 	COMMENT "Finish date this fact was valid in reality.",
  dmlType ENUM("INSERT", "UPDATE", "DELETE", "VIEW")	COMMENT "Type of data manipulation (INSERT, UPDATE, DELETE, VIEW).",
  ddlName VARCHAR(128) DEFAULT NULL 	COMMENT "Name of data definition (table) being logged.",
  ddlKey INT(11) NOT NULL 	COMMENT "The primary key value of the table being logged (PK from ddlName).",
  logSeq INT(11) DEFAULT NULL 	COMMENT "The log sequence number for contiguous history.",
  userName VARCHAR(128) DEFAULT NULL 	COMMENT "The user logging the changes.",
  logYear INT(11) DEFAULT NULL 	COMMENT "Log transaction date year.",
  logMonth INT(11) DEFAULT NULL 	COMMENT "Log transaction date month.",
  logWeek INT(11) DEFAULT NULL 	COMMENT "Log transaction date week.",
  logDay INT(11) DEFAULT NULL 	COMMENT "Log transaction date day.",
  logQtr INT(11) DEFAULT NULL 	COMMENT "Log transaction date quarter.",
  logEntry TEXT DEFAULT NULL 	COMMENT "The XML description of changes."
)
	ENGINE=ARCHIVE AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci
	PARTITION BY RANGE (logDate)
(
	PARTITION p0 VALUES LESS THAN (UNIX_TIMESTAMP("2003-01-01"))
,	PARTITION p1 VALUES LESS THAN (UNIX_TIMESTAMP("2004-01-01"))
,	PARTITION p2 VALUES LESS THAN (UNIX_TIMESTAMP("2005-01-01"))
,	PARTITION p3 VALUES LESS THAN (UNIX_TIMESTAMP("2006-01-01"))
,	PARTITION p4 VALUES LESS THAN (UNIX_TIMESTAMP("2007-01-01"))
,	PARTITION p5 VALUES LESS THAN (UNIX_TIMESTAMP("2008-01-01"))
,	PARTITION p6 VALUES LESS THAN (UNIX_TIMESTAMP("2009-01-01"))
,	PARTITION p7 VALUES LESS THAN (UNIX_TIMESTAMP("2010-01-01"))
,	PARTITION p8 VALUES LESS THAN (UNIX_TIMESTAMP("2011-01-01"))
,	PARTITION p9 VALUES LESS THAN (UNIX_TIMESTAMP("2012-01-01"))
,	PARTITION p10 VALUES LESS THAN (UNIX_TIMESTAMP("2013-01-01"))
,	PARTITION p11 VALUES LESS THAN MAXVALUE
)
;

CREATE TABLE IF NOT EXISTS	log_invoice
(
  logDate BIGINT(20) NOT NULL,
  id INT(11) NOT NULL,
  accountID INT(11) NOT NULL,
  tableType CHAR(1) NOT NULL DEFAULT 'I',
  invoiceType VARCHAR(20) DEFAULT NULL,
  createdBy INT(11) DEFAULT NULL,
  updatedBy INT(11) DEFAULT NULL,
  creationDate DATETIME DEFAULT NULL,
  updateDate DATETIME DEFAULT NULL,
  dueDate DATE DEFAULT NULL,
  STATUS VARCHAR(10) DEFAULT NULL,
  totalAmount DECIMAL(9,2) DEFAULT NULL,
  amountApplied DECIMAL(9,2) DEFAULT NULL,
  commissionableAmount DECIMAL(9,2) NOT NULL DEFAULT '0.00',
  paidDate DATETIME DEFAULT NULL,
  paymentMethod VARCHAR(30) DEFAULT NULL,
  checkNumber VARCHAR(50) DEFAULT NULL,
  transactionID VARCHAR(50) DEFAULT NULL,
  poNumber VARCHAR(20) DEFAULT NULL,
  ccNumber VARCHAR(20) DEFAULT NULL,
  qbSync TINYINT(4) NOT NULL DEFAULT '0',
  sapLastSync DATETIME DEFAULT NULL,
  sapSync TINYINT(1) DEFAULT '0',
  sapID VARCHAR(25) DEFAULT NULL,
  qbListID VARCHAR(25) DEFAULT NULL,
  qbSyncWithTax TINYINT(4) NOT NULL DEFAULT '0',
  payingFacilities INT(11) NOT NULL DEFAULT '0',
  notes TEXT CHARACTER SET utf8,
  currency CHAR(3) DEFAULT 'USD',
  lateFeeInvoiceID INT(11) DEFAULT NULL
)
	ENGINE=ARCHIVE AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci
	PARTITION BY RANGE (logDate)
(
	PARTITION p0 VALUES LESS THAN (UNIX_TIMESTAMP("2003-01-01"))
,	PARTITION p1 VALUES LESS THAN (UNIX_TIMESTAMP("2004-01-01"))
,	PARTITION p2 VALUES LESS THAN (UNIX_TIMESTAMP("2005-01-01"))
,	PARTITION p3 VALUES LESS THAN (UNIX_TIMESTAMP("2006-01-01"))
,	PARTITION p4 VALUES LESS THAN (UNIX_TIMESTAMP("2007-01-01"))
,	PARTITION p5 VALUES LESS THAN (UNIX_TIMESTAMP("2008-01-01"))
,	PARTITION p6 VALUES LESS THAN (UNIX_TIMESTAMP("2009-01-01"))
,	PARTITION p7 VALUES LESS THAN (UNIX_TIMESTAMP("2010-01-01"))
,	PARTITION p8 VALUES LESS THAN (UNIX_TIMESTAMP("2011-01-01"))
,	PARTITION p9 VALUES LESS THAN (UNIX_TIMESTAMP("2012-01-01"))
,	PARTITION p10 VALUES LESS THAN (UNIX_TIMESTAMP("2013-01-01"))
,	PARTITION p11 VALUES LESS THAN MAXVALUE
)
;

CREATE TABLE IF NOT EXISTS log_invoice_commission
(
  logDate BIGINT(20) NOT NULL,
  id INT(11) NOT NULL,
  invoiceID INT(11) NOT NULL,
  userID INT(11) DEFAULT NULL,
  createdBy INT(11) NOT NULL,
  creationDate DATETIME NOT NULL,
  updatedBy INT(11) NOT NULL,
  updateDate DATETIME NOT NULL,
  activationPoints DECIMAL(11,7) NOT NULL,
  revenue DECIMAL(11,7) NOT NULL,
  accountUserID INT(11) NOT NULL
)
	ENGINE=ARCHIVE AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci
	PARTITION BY RANGE (logDate)
(
	PARTITION p0 VALUES LESS THAN (UNIX_TIMESTAMP("2003-01-01"))
,	PARTITION p1 VALUES LESS THAN (UNIX_TIMESTAMP("2004-01-01"))
,	PARTITION p2 VALUES LESS THAN (UNIX_TIMESTAMP("2005-01-01"))
,	PARTITION p3 VALUES LESS THAN (UNIX_TIMESTAMP("2006-01-01"))
,	PARTITION p4 VALUES LESS THAN (UNIX_TIMESTAMP("2007-01-01"))
,	PARTITION p5 VALUES LESS THAN (UNIX_TIMESTAMP("2008-01-01"))
,	PARTITION p6 VALUES LESS THAN (UNIX_TIMESTAMP("2009-01-01"))
,	PARTITION p7 VALUES LESS THAN (UNIX_TIMESTAMP("2010-01-01"))
,	PARTITION p8 VALUES LESS THAN (UNIX_TIMESTAMP("2011-01-01"))
,	PARTITION p9 VALUES LESS THAN (UNIX_TIMESTAMP("2012-01-01"))
,	PARTITION p10 VALUES LESS THAN (UNIX_TIMESTAMP("2013-01-01"))
,	PARTITION p11 VALUES LESS THAN MAXVALUE
)
;

CREATE TABLE IF NOT EXISTS log_invoice_fee
(
  logDate BIGINT(20) NOT NULL,
  id INT(11) NOT NULL,
  fee VARCHAR(100) DEFAULT NULL,
  defaultAmount DECIMAL(9,2) NOT NULL DEFAULT '0.00',
  ratePercent DECIMAL(6,3) DEFAULT '0.000',
  visible TINYINT(4) NOT NULL DEFAULT '1',
  feeClass VARCHAR(50) CHARACTER SET latin1 DEFAULT NULL,
  minFacilities INT(11) NOT NULL DEFAULT '0',
  maxFacilities INT(11) NOT NULL DEFAULT '0',
  qbFullName VARCHAR(75) DEFAULT NULL,
  createdBy INT(11) DEFAULT NULL,
  updatedBy INT(11) DEFAULT NULL,
  creationDate DATETIME DEFAULT NULL,
  updateDate DATETIME DEFAULT NULL,
  effectiveDate DATETIME DEFAULT NULL,
  displayOrder TINYINT(3) UNSIGNED NOT NULL DEFAULT '100',
  commissionEligible TINYINT(1) NOT NULL DEFAULT '0'
)
	ENGINE=ARCHIVE AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci
	PARTITION BY RANGE (logDate)
(
	PARTITION p0 VALUES LESS THAN (UNIX_TIMESTAMP("2003-01-01"))
,	PARTITION p1 VALUES LESS THAN (UNIX_TIMESTAMP("2004-01-01"))
,	PARTITION p2 VALUES LESS THAN (UNIX_TIMESTAMP("2005-01-01"))
,	PARTITION p3 VALUES LESS THAN (UNIX_TIMESTAMP("2006-01-01"))
,	PARTITION p4 VALUES LESS THAN (UNIX_TIMESTAMP("2007-01-01"))
,	PARTITION p5 VALUES LESS THAN (UNIX_TIMESTAMP("2008-01-01"))
,	PARTITION p6 VALUES LESS THAN (UNIX_TIMESTAMP("2009-01-01"))
,	PARTITION p7 VALUES LESS THAN (UNIX_TIMESTAMP("2010-01-01"))
,	PARTITION p8 VALUES LESS THAN (UNIX_TIMESTAMP("2011-01-01"))
,	PARTITION p9 VALUES LESS THAN (UNIX_TIMESTAMP("2012-01-01"))
,	PARTITION p10 VALUES LESS THAN (UNIX_TIMESTAMP("2013-01-01"))
,	PARTITION p11 VALUES LESS THAN MAXVALUE
)
;

CREATE TABLE IF NOT EXISTS log_invoice_fee_country
(
  logDate BIGINT(20) NOT NULL,
  id INT(11) NOT NULL,
  feeID INT(11) NOT NULL,
  country VARCHAR(10) NOT NULL,
  subdivision VARCHAR(10) DEFAULT NULL,
  amount DECIMAL(9,2) NOT NULL DEFAULT '0.00',
  ratePercent DECIMAL(6,3) DEFAULT '0.000',
  createdBy INT(11) DEFAULT NULL,
  updatedBy INT(11) DEFAULT NULL,
  creationDate DATETIME DEFAULT NULL,
  updateDate DATETIME DEFAULT NULL,
  effectiveDate DATETIME NOT NULL DEFAULT '1970-01-01 00:00:00',
  expirationDate DATETIME NOT NULL DEFAULT '4000-01-01 23:59:59'
)
	ENGINE=ARCHIVE AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci
	PARTITION BY RANGE (logDate)
(
	PARTITION p0 VALUES LESS THAN (UNIX_TIMESTAMP("2003-01-01"))
,	PARTITION p1 VALUES LESS THAN (UNIX_TIMESTAMP("2004-01-01"))
,	PARTITION p2 VALUES LESS THAN (UNIX_TIMESTAMP("2005-01-01"))
,	PARTITION p3 VALUES LESS THAN (UNIX_TIMESTAMP("2006-01-01"))
,	PARTITION p4 VALUES LESS THAN (UNIX_TIMESTAMP("2007-01-01"))
,	PARTITION p5 VALUES LESS THAN (UNIX_TIMESTAMP("2008-01-01"))
,	PARTITION p6 VALUES LESS THAN (UNIX_TIMESTAMP("2009-01-01"))
,	PARTITION p7 VALUES LESS THAN (UNIX_TIMESTAMP("2010-01-01"))
,	PARTITION p8 VALUES LESS THAN (UNIX_TIMESTAMP("2011-01-01"))
,	PARTITION p9 VALUES LESS THAN (UNIX_TIMESTAMP("2012-01-01"))
,	PARTITION p10 VALUES LESS THAN (UNIX_TIMESTAMP("2013-01-01"))
,	PARTITION p11 VALUES LESS THAN MAXVALUE
)
;

CREATE TABLE IF NOT EXISTS log_invoice_item
(
  logDate BIGINT(20) NOT NULL,
  id INT(11) NOT NULL,
  invoiceID INT(11) NOT NULL,
  feeID INT(11) NOT NULL,
  amount DECIMAL(9,2) NOT NULL DEFAULT '0.00',
  originalAmount DECIMAL(9,2) NOT NULL DEFAULT '0.00',
  description VARCHAR(100) DEFAULT NULL,
  createdBy INT(11) DEFAULT NULL,
  updatedBy INT(11) DEFAULT NULL,
  creationDate DATETIME DEFAULT NULL,
  updateDate DATETIME DEFAULT NULL,
  paymentExpires DATE DEFAULT NULL,
  qbRefundID VARCHAR(25) CHARACTER SET latin1 DEFAULT NULL,
  refunded TINYINT(4) DEFAULT '0',
  refundFor INT(11) DEFAULT NULL,
  transactionType CHAR(1) DEFAULT NULL,
  revenueStartDate DATE DEFAULT NULL,
  revenueFinishDate DATE DEFAULT NULL
)
	ENGINE=ARCHIVE AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci
	PARTITION BY RANGE (logDate)
(
	PARTITION p0 VALUES LESS THAN (UNIX_TIMESTAMP("2003-01-01"))
,	PARTITION p1 VALUES LESS THAN (UNIX_TIMESTAMP("2004-01-01"))
,	PARTITION p2 VALUES LESS THAN (UNIX_TIMESTAMP("2005-01-01"))
,	PARTITION p3 VALUES LESS THAN (UNIX_TIMESTAMP("2006-01-01"))
,	PARTITION p4 VALUES LESS THAN (UNIX_TIMESTAMP("2007-01-01"))
,	PARTITION p5 VALUES LESS THAN (UNIX_TIMESTAMP("2008-01-01"))
,	PARTITION p6 VALUES LESS THAN (UNIX_TIMESTAMP("2009-01-01"))
,	PARTITION p7 VALUES LESS THAN (UNIX_TIMESTAMP("2010-01-01"))
,	PARTITION p8 VALUES LESS THAN (UNIX_TIMESTAMP("2011-01-01"))
,	PARTITION p9 VALUES LESS THAN (UNIX_TIMESTAMP("2012-01-01"))
,	PARTITION p10 VALUES LESS THAN (UNIX_TIMESTAMP("2013-01-01"))
,	PARTITION p11 VALUES LESS THAN MAXVALUE
)
;

CREATE TABLE IF NOT EXISTS log_invoice_payment
(
  logDate BIGINT(20) NOT NULL,
  id INT(11) NOT NULL,
  paymentID INT(10) NOT NULL,
  invoiceID INT(10) DEFAULT NULL,
  refundID INT(10) DEFAULT NULL,
  amount DECIMAL(6,2) NOT NULL DEFAULT '0.00',
  createdBy INT(11) DEFAULT NULL,
  updatedBy INT(11) DEFAULT NULL,
  creationDate DATETIME DEFAULT NULL,
  updateDate DATETIME DEFAULT NULL,
  paymentType CHAR(1) NOT NULL DEFAULT 'I'
)
	ENGINE=ARCHIVE AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci
	PARTITION BY RANGE (logDate)
(
	PARTITION p0 VALUES LESS THAN (UNIX_TIMESTAMP("2003-01-01"))
,	PARTITION p1 VALUES LESS THAN (UNIX_TIMESTAMP("2004-01-01"))
,	PARTITION p2 VALUES LESS THAN (UNIX_TIMESTAMP("2005-01-01"))
,	PARTITION p3 VALUES LESS THAN (UNIX_TIMESTAMP("2006-01-01"))
,	PARTITION p4 VALUES LESS THAN (UNIX_TIMESTAMP("2007-01-01"))
,	PARTITION p5 VALUES LESS THAN (UNIX_TIMESTAMP("2008-01-01"))
,	PARTITION p6 VALUES LESS THAN (UNIX_TIMESTAMP("2009-01-01"))
,	PARTITION p7 VALUES LESS THAN (UNIX_TIMESTAMP("2010-01-01"))
,	PARTITION p8 VALUES LESS THAN (UNIX_TIMESTAMP("2011-01-01"))
,	PARTITION p9 VALUES LESS THAN (UNIX_TIMESTAMP("2012-01-01"))
,	PARTITION p10 VALUES LESS THAN (UNIX_TIMESTAMP("2013-01-01"))
,	PARTITION p11 VALUES LESS THAN MAXVALUE
)
;

CREATE TABLE IF NOT EXISTS log_msg_key
(
  logDate BIGINT(20) NOT NULL,
  id INT(11) NOT NULL,
  msgKey VARCHAR(100) NOT NULL,
  description VARCHAR(255) DEFAULT NULL,
  js TINYINT(1) NOT NULL DEFAULT '0' COMMENT '1 indicates translation applies to javascript',
  firstUsed DATE DEFAULT NULL,
  lastUsed DATE DEFAULT NULL,
  createdBy INT(11) DEFAULT NULL,
  updatedBy INT(11) DEFAULT NULL,
  creationDate DATETIME DEFAULT NULL,
  updateDate DATETIME DEFAULT NULL
)
	ENGINE=ARCHIVE AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci
	PARTITION BY RANGE (logDate)
(
	PARTITION p0 VALUES LESS THAN (UNIX_TIMESTAMP("2003-01-01"))
,	PARTITION p1 VALUES LESS THAN (UNIX_TIMESTAMP("2004-01-01"))
,	PARTITION p2 VALUES LESS THAN (UNIX_TIMESTAMP("2005-01-01"))
,	PARTITION p3 VALUES LESS THAN (UNIX_TIMESTAMP("2006-01-01"))
,	PARTITION p4 VALUES LESS THAN (UNIX_TIMESTAMP("2007-01-01"))
,	PARTITION p5 VALUES LESS THAN (UNIX_TIMESTAMP("2008-01-01"))
,	PARTITION p6 VALUES LESS THAN (UNIX_TIMESTAMP("2009-01-01"))
,	PARTITION p7 VALUES LESS THAN (UNIX_TIMESTAMP("2010-01-01"))
,	PARTITION p8 VALUES LESS THAN (UNIX_TIMESTAMP("2011-01-01"))
,	PARTITION p9 VALUES LESS THAN (UNIX_TIMESTAMP("2012-01-01"))
,	PARTITION p10 VALUES LESS THAN (UNIX_TIMESTAMP("2013-01-01"))
,	PARTITION p11 VALUES LESS THAN MAXVALUE
)
;

CREATE TABLE IF NOT EXISTS log_msg_locale
(
  logDate BIGINT(20) NOT NULL,
  id INT(11) NOT NULL,
  keyID INT(11) NOT NULL,
  locale VARCHAR(8) NOT NULL,
  msgValue TEXT,
  firstUsed DATE DEFAULT NULL,
  lastUsed DATE DEFAULT NULL,
  qualityRating INT(4) NOT NULL DEFAULT '0',
  createdBy INT(11) DEFAULT NULL,
  updatedBy INT(11) DEFAULT NULL,
  creationDate DATETIME DEFAULT NULL,
  updateDate DATETIME DEFAULT NULL
)
	ENGINE=ARCHIVE AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci
	PARTITION BY RANGE (logDate)
(
	PARTITION p0 VALUES LESS THAN (UNIX_TIMESTAMP("2003-01-01"))
,	PARTITION p1 VALUES LESS THAN (UNIX_TIMESTAMP("2004-01-01"))
,	PARTITION p2 VALUES LESS THAN (UNIX_TIMESTAMP("2005-01-01"))
,	PARTITION p3 VALUES LESS THAN (UNIX_TIMESTAMP("2006-01-01"))
,	PARTITION p4 VALUES LESS THAN (UNIX_TIMESTAMP("2007-01-01"))
,	PARTITION p5 VALUES LESS THAN (UNIX_TIMESTAMP("2008-01-01"))
,	PARTITION p6 VALUES LESS THAN (UNIX_TIMESTAMP("2009-01-01"))
,	PARTITION p7 VALUES LESS THAN (UNIX_TIMESTAMP("2010-01-01"))
,	PARTITION p8 VALUES LESS THAN (UNIX_TIMESTAMP("2011-01-01"))
,	PARTITION p9 VALUES LESS THAN (UNIX_TIMESTAMP("2012-01-01"))
,	PARTITION p10 VALUES LESS THAN (UNIX_TIMESTAMP("2013-01-01"))
,	PARTITION p11 VALUES LESS THAN MAXVALUE
)
;
