package com.picsauditing.report.models;

public enum ModelType {
	Accounts,
	ContractorAudits,
	ContractorAuditData,
	ContractorAuditOperators,
	ContractorAuditOperatorWorkflows,
	ContractorFees,
	ContractorNumbers,
	ContractorOperators,
	Contractors,
	ContractorSearch,
	ContractorTrades,
	Country,
	EmailExclusions,
	Emails,
	EmailSubscriptions,
	EmployeeAssessments,
	Employees,
	ExceptionLogs,
	InvoiceItems,
	Invoices,
	InvoiceCommissions,
	Operators,
	PaymentCommissions,
	RegistrationRequests,
	ReportPermissions,
	Reports,
	Resources,
	UserAssignments,
	UserGroups,
	Users;
}
