package com.picsauditing.report.models;

public enum ModelType {
	AccountNotes,
    Accounts,
    AuditTypes,
    ContractorAudits,
    ContractorAuditDatas,
    ContractorAuditFiles,
    ContractorAuditOperatorCemex,
    ContractorAuditOperators,
    ContractorAuditOperatorWorkflows,
    ContractorFees,
    ContractorFlagCriteriaDatas,
    ContractorFlagDatas,
    ContractorNumbers,
    ContractorOperators,
    Contractors,
    ContractorSearch,
    ContractorStatistics,
    ContractorTrades,
    EmployeeCompetencies,
    FlagArchive,
    ForcedFlags,
    ForcedFlagPercents,
    InvoiceItems,
    Invoices,
    Operators,
    OperatorAccountUsers,
    OperatorUsers,
    PaymentCommissions,
    Payments,
    Reports,
    ReportColumns,
    ReportFilters,
    ReportPermissions,
    ReportUsers,
    UserAssignments,
	Users;

//    ContractorAuditOperatorWorkflows,
//    Country,
//    EmailExclusions,
//    Emails,
//    EmailSubscriptions,
//    EmployeeAssessments,
//    Employees,
//    ExceptionLogs,
//    RegistrationRequests,
//    Resources,
//    UserGroups,
}
