package com.picsauditing.jpa.entities
import java.util.List;

rule "InvoiceFee.FREE"
when
	$con : ContractorAccount()
	$cos : List( size == 0 ) from collect( ContractorOperator( contractorAccount == $con, operatorAccount.status.active == true && operatorAccount.doContractorsPay != "No" ) from $con.nonCorporateOperators )
then
	InvoiceFee inv = new InvoiceFee();
	inv.setId(InvoiceFee.FREE);
	$con.setNewMembershipLevel(inv);
	System.out.println("InvoiceFee.FREE: "+$con.getName() + " has "+$cos.size()+" paying Facilities");
end


rule "InvoiceFee.FREE: Operator Pays"
salience 10
when
	$con : ContractorAccount()
	$cos : List( size == 1 ) from collect( ContractorOperator( contractorAccount == $con, operatorAccount.status.active == true && operatorAccount.doContractorsPay == "Multiple" ) from $con.nonCorporateOperators )
then
	InvoiceFee inv = new InvoiceFee();
	inv.setId(InvoiceFee.FREE);
	$con.setNewMembershipLevel(inv);
	System.out.println("InvoiceFee.FREE: "+$con.getName() + " has "+$cos.size()+" paying Facilities");
end