package com.picsauditing.jpa.entities

import java.util.List;
import java.math.BigDecimal;

rule "1"
when
	$con : ContractorAccount( )
	$inv : List() from collect( Invoice(status != TransactionStatus.Void) from $con.invoices )
	$ref : List() from collect( Refund(status != TransactionStatus.Void) from $con.refunds )
	$pay : List() from collect( Payment(status != TransactionStatus.Void) from $con.payments )
then
	System.out.println($con.getName() + " has " + $inv.size() + " legitimate invoices");
end