/**
 *
 *
 * User: APhatarphekar
 * Date: 6/23/2014
 * Time: 10:25 AM
 *
 */
package com.picsauditing.employeeguard.models;

public enum MOperations {
	COPY_ID, COPY_NAME, ATTACH_REQD_SKILLS, EVAL_EMPLOYEE_COUNT, EVAL_EMPLOYEE_COUNT_RETAIN_EMPLOYEE_SKILLS, ATTACH_DOCUMENTATION, ATTACH_SKILLS, ATTACH_ROLES, ATTACH_GROUPS, ATTACH_PROJECTS, ATTACH_SITES, ATTACH_CORPORATES, ATTACH_CONTRACTORS
}
