--liquibase formatted sql

--changeset mdo:59
INSERT INTO togglz (FEATURE_NAME,FEATURE_ENABLED) VALUES ('USER_NEW_AUDIT_BUILDER',0);
INSERT INTO togglz (FEATURE_NAME,FEATURE_ENABLED) VALUES ('USER_NEW_AUDIT_PERCENT_CALCULATOR',0);