DROP TABLE IF EXISTS `contractor_operator`;

CREATE TABLE `contractor_operator` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `opID` int(11) NOT NULL,
  `conID` int(11) NOT NULL,
  `type` varchar(25) DEFAULT NULL,
  `createdBy` int(11) DEFAULT NULL,
  `creationDate` datetime DEFAULT NULL,
  `updatedBy` int(11) DEFAULT NULL,
  `updateDate` datetime DEFAULT NULL,
  `workStatus` char(1) NOT NULL DEFAULT 'P',
  `flag` enum('Red','Amber','Green','Clear') NOT NULL DEFAULT 'Red',
  `waitingOn` tinyint(4) NOT NULL DEFAULT '0',
  `forceFlag` enum('Red','Amber','Green') DEFAULT NULL,
  `forceBegin` date DEFAULT NULL,
  `forceEnd` date DEFAULT NULL,
  `forcedBy` int(11) DEFAULT NULL,
  `relationshipType` varchar(10) DEFAULT NULL,
  `processCompletion` datetime DEFAULT NULL,
  `flagLastUpdated` datetime DEFAULT NULL,
  `forceReason` varchar(255) DEFAULT NULL,
  `contractorType` varchar(20) NOT NULL DEFAULT 'Onsite',
  `baselineFlag` enum('Red','Amber','Green','Clear') DEFAULT NULL,
  `baselineApprover` int(11) DEFAULT NULL,
  `baselineApproved` datetime DEFAULT NULL,
  `flagDetail` text,
  `baselineFlagDetail` text,
  `lastStepToGreenDate` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `conID` (`conID`,`opID`),
  KEY `opID` (`opID`),
  CONSTRAINT `FK_contractor_operator_con` FOREIGN KEY (`conID`) REFERENCES `accounts` (`id`) ON DELETE CASCADE,
  CONSTRAINT `FK_contractor_operator_op` FOREIGN KEY (`opID`) REFERENCES `accounts` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=275407 DEFAULT CHARSET=latin1;
