//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.03.12 at 04:00:19 PM PDT 
//


package com.picsauditing.quickbooks.qbxml;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded" minOccurs="0">
 *         &lt;element name="HostQueryRs" type="{}HostQueryRsType"/>
 *         &lt;element name="CompanyQueryRs" type="{}CompanyQueryRsType"/>
 *         &lt;element name="CompanyActivityQueryRs" type="{}CompanyActivityQueryRsType"/>
 *         &lt;element name="PreferencesQueryRs" type="{}PreferencesQueryRsType"/>
 *         &lt;element name="AccountAddRs" type="{}AccountAddRsType"/>
 *         &lt;element name="AccountModRs" type="{}AccountModRsType"/>
 *         &lt;element name="AccountQueryRs" type="{}AccountQueryRsType"/>
 *         &lt;element name="SpecialAccountAddRs" type="{}SpecialAccountAddRsType"/>
 *         &lt;element name="AccountTaxLineInfoQueryRs" type="{}AccountTaxLineInfoQueryRsType"/>
 *         &lt;element name="CustomerAddRs" type="{}CustomerAddRsType"/>
 *         &lt;element name="CustomerModRs" type="{}CustomerModRsType"/>
 *         &lt;element name="CustomerQueryRs" type="{}CustomerQueryRsType"/>
 *         &lt;element name="EmployeeAddRs" type="{}EmployeeAddRsType"/>
 *         &lt;element name="EmployeeModRs" type="{}EmployeeModRsType"/>
 *         &lt;element name="EmployeeQueryRs" type="{}EmployeeQueryRsType"/>
 *         &lt;element name="OtherNameAddRs" type="{}OtherNameAddRsType"/>
 *         &lt;element name="OtherNameModRs" type="{}OtherNameModRsType"/>
 *         &lt;element name="OtherNameQueryRs" type="{}OtherNameQueryRsType"/>
 *         &lt;element name="VendorAddRs" type="{}VendorAddRsType"/>
 *         &lt;element name="VendorModRs" type="{}VendorModRsType"/>
 *         &lt;element name="VendorQueryRs" type="{}VendorQueryRsType"/>
 *         &lt;element name="EntityQueryRs" type="{}EntityQueryRsType"/>
 *         &lt;element name="StandardTermsAddRs" type="{}StandardTermsAddRsType"/>
 *         &lt;element name="StandardTermsQueryRs" type="{}StandardTermsQueryRsType"/>
 *         &lt;element name="DateDrivenTermsAddRs" type="{}DateDrivenTermsAddRsType"/>
 *         &lt;element name="DateDrivenTermsQueryRs" type="{}DateDrivenTermsQueryRsType"/>
 *         &lt;element name="TermsQueryRs" type="{}TermsQueryRsType"/>
 *         &lt;element name="ClassAddRs" type="{}ClassAddRsType"/>
 *         &lt;element name="ClassQueryRs" type="{}ClassQueryRsType"/>
 *         &lt;element name="SalesRepAddRs" type="{}SalesRepAddRsType"/>
 *         &lt;element name="SalesRepModRs" type="{}SalesRepModRsType"/>
 *         &lt;element name="SalesRepQueryRs" type="{}SalesRepQueryRsType"/>
 *         &lt;element name="CustomerTypeAddRs" type="{}CustomerTypeAddRsType"/>
 *         &lt;element name="CustomerTypeQueryRs" type="{}CustomerTypeQueryRsType"/>
 *         &lt;element name="VendorTypeAddRs" type="{}VendorTypeAddRsType"/>
 *         &lt;element name="VendorTypeQueryRs" type="{}VendorTypeQueryRsType"/>
 *         &lt;element name="JobTypeAddRs" type="{}JobTypeAddRsType"/>
 *         &lt;element name="JobTypeQueryRs" type="{}JobTypeQueryRsType"/>
 *         &lt;element name="CustomerMsgAddRs" type="{}CustomerMsgAddRsType"/>
 *         &lt;element name="CustomerMsgQueryRs" type="{}CustomerMsgQueryRsType"/>
 *         &lt;element name="PaymentMethodAddRs" type="{}PaymentMethodAddRsType"/>
 *         &lt;element name="PaymentMethodQueryRs" type="{}PaymentMethodQueryRsType"/>
 *         &lt;element name="ShipMethodAddRs" type="{}ShipMethodAddRsType"/>
 *         &lt;element name="ShipMethodQueryRs" type="{}ShipMethodQueryRsType"/>
 *         &lt;element name="SalesTaxCodeAddRs" type="{}SalesTaxCodeAddRsType"/>
 *         &lt;element name="SalesTaxCodeQueryRs" type="{}SalesTaxCodeQueryRsType"/>
 *         &lt;element name="ToDoAddRs" type="{}ToDoAddRsType"/>
 *         &lt;element name="ToDoQueryRs" type="{}ToDoQueryRsType"/>
 *         &lt;element name="ItemServiceAddRs" type="{}ItemServiceAddRsType"/>
 *         &lt;element name="ItemServiceModRs" type="{}ItemServiceModRsType"/>
 *         &lt;element name="ItemServiceQueryRs" type="{}ItemServiceQueryRsType"/>
 *         &lt;element name="ItemNonInventoryAddRs" type="{}ItemNonInventoryAddRsType"/>
 *         &lt;element name="ItemNonInventoryModRs" type="{}ItemNonInventoryModRsType"/>
 *         &lt;element name="ItemNonInventoryQueryRs" type="{}ItemNonInventoryQueryRsType"/>
 *         &lt;element name="ItemOtherChargeAddRs" type="{}ItemOtherChargeAddRsType"/>
 *         &lt;element name="ItemOtherChargeModRs" type="{}ItemOtherChargeModRsType"/>
 *         &lt;element name="ItemOtherChargeQueryRs" type="{}ItemOtherChargeQueryRsType"/>
 *         &lt;element name="ItemInventoryAddRs" type="{}ItemInventoryAddRsType"/>
 *         &lt;element name="ItemInventoryModRs" type="{}ItemInventoryModRsType"/>
 *         &lt;element name="ItemInventoryQueryRs" type="{}ItemInventoryQueryRsType"/>
 *         &lt;element name="ItemInventoryAssemblyAddRs" type="{}ItemInventoryAssemblyAddRsType"/>
 *         &lt;element name="ItemInventoryAssemblyModRs" type="{}ItemInventoryAssemblyModRsType"/>
 *         &lt;element name="ItemInventoryAssemblyQueryRs" type="{}ItemInventoryAssemblyQueryRsType"/>
 *         &lt;element name="ItemFixedAssetAddRs" type="{}ItemFixedAssetAddRsType"/>
 *         &lt;element name="ItemFixedAssetModRs" type="{}ItemFixedAssetModRsType"/>
 *         &lt;element name="ItemFixedAssetQueryRs" type="{}ItemFixedAssetQueryRsType"/>
 *         &lt;element name="ItemSubtotalAddRs" type="{}ItemSubtotalAddRsType"/>
 *         &lt;element name="ItemSubtotalModRs" type="{}ItemSubtotalModRsType"/>
 *         &lt;element name="ItemSubtotalQueryRs" type="{}ItemSubtotalQueryRsType"/>
 *         &lt;element name="ItemDiscountAddRs" type="{}ItemDiscountAddRsType"/>
 *         &lt;element name="ItemDiscountModRs" type="{}ItemDiscountModRsType"/>
 *         &lt;element name="ItemDiscountQueryRs" type="{}ItemDiscountQueryRsType"/>
 *         &lt;element name="ItemPaymentAddRs" type="{}ItemPaymentAddRsType"/>
 *         &lt;element name="ItemPaymentModRs" type="{}ItemPaymentModRsType"/>
 *         &lt;element name="ItemPaymentQueryRs" type="{}ItemPaymentQueryRsType"/>
 *         &lt;element name="ItemSalesTaxAddRs" type="{}ItemSalesTaxAddRsType"/>
 *         &lt;element name="ItemSalesTaxModRs" type="{}ItemSalesTaxModRsType"/>
 *         &lt;element name="ItemSalesTaxQueryRs" type="{}ItemSalesTaxQueryRsType"/>
 *         &lt;element name="ItemSalesTaxGroupAddRs" type="{}ItemSalesTaxGroupAddRsType"/>
 *         &lt;element name="ItemSalesTaxGroupModRs" type="{}ItemSalesTaxGroupModRsType"/>
 *         &lt;element name="ItemSalesTaxGroupQueryRs" type="{}ItemSalesTaxGroupQueryRsType"/>
 *         &lt;element name="ItemGroupAddRs" type="{}ItemGroupAddRsType"/>
 *         &lt;element name="ItemGroupModRs" type="{}ItemGroupModRsType"/>
 *         &lt;element name="ItemGroupQueryRs" type="{}ItemGroupQueryRsType"/>
 *         &lt;element name="SpecialItemAddRs" type="{}SpecialItemAddRsType"/>
 *         &lt;element name="ItemQueryRs" type="{}ItemQueryRsType"/>
 *         &lt;element name="PayrollItemWageAddRs" type="{}PayrollItemWageAddRsType"/>
 *         &lt;element name="PayrollItemWageQueryRs" type="{}PayrollItemWageQueryRsType"/>
 *         &lt;element name="PayrollItemNonWageQueryRs" type="{}PayrollItemNonWageQueryRsType"/>
 *         &lt;element name="TemplateQueryRs" type="{}TemplateQueryRsType"/>
 *         &lt;element name="PriceLevelAddRs" type="{}PriceLevelAddRsType"/>
 *         &lt;element name="PriceLevelModRs" type="{}PriceLevelModRsType"/>
 *         &lt;element name="PriceLevelQueryRs" type="{}PriceLevelQueryRsType"/>
 *         &lt;element name="BillingRateAddRs" type="{}BillingRateAddRsType"/>
 *         &lt;element name="BillingRateQueryRs" type="{}BillingRateQueryRsType"/>
 *         &lt;element name="VehicleAddRs" type="{}VehicleAddRsType"/>
 *         &lt;element name="VehicleModRs" type="{}VehicleModRsType"/>
 *         &lt;element name="VehicleQueryRs" type="{}VehicleQueryRsType"/>
 *         &lt;element name="UnitOfMeasureSetAddRs" type="{}UnitOfMeasureSetAddRsType"/>
 *         &lt;element name="UnitOfMeasureSetQueryRs" type="{}UnitOfMeasureSetQueryRsType"/>
 *         &lt;element name="WorkersCompCodeAddRs" type="{}WorkersCompCodeAddRsType"/>
 *         &lt;element name="WorkersCompCodeModRs" type="{}WorkersCompCodeModRsType"/>
 *         &lt;element name="WorkersCompCodeQueryRs" type="{}WorkersCompCodeQueryRsType"/>
 *         &lt;element name="InvoiceAddRs" type="{}InvoiceAddRsType"/>
 *         &lt;element name="InvoiceModRs" type="{}InvoiceModRsType"/>
 *         &lt;element name="InvoiceQueryRs" type="{}InvoiceQueryRsType"/>
 *         &lt;element name="EstimateAddRs" type="{}EstimateAddRsType"/>
 *         &lt;element name="EstimateModRs" type="{}EstimateModRsType"/>
 *         &lt;element name="EstimateQueryRs" type="{}EstimateQueryRsType"/>
 *         &lt;element name="SalesOrderAddRs" type="{}SalesOrderAddRsType"/>
 *         &lt;element name="SalesOrderModRs" type="{}SalesOrderModRsType"/>
 *         &lt;element name="SalesOrderQueryRs" type="{}SalesOrderQueryRsType"/>
 *         &lt;element name="SalesReceiptAddRs" type="{}SalesReceiptAddRsType"/>
 *         &lt;element name="SalesReceiptModRs" type="{}SalesReceiptModRsType"/>
 *         &lt;element name="SalesReceiptQueryRs" type="{}SalesReceiptQueryRsType"/>
 *         &lt;element name="CreditMemoAddRs" type="{}CreditMemoAddRsType"/>
 *         &lt;element name="CreditMemoModRs" type="{}CreditMemoModRsType"/>
 *         &lt;element name="CreditMemoQueryRs" type="{}CreditMemoQueryRsType"/>
 *         &lt;element name="ReceivePaymentAddRs" type="{}ReceivePaymentAddRsType"/>
 *         &lt;element name="ReceivePaymentModRs" type="{}ReceivePaymentModRsType"/>
 *         &lt;element name="ReceivePaymentQueryRs" type="{}ReceivePaymentQueryRsType"/>
 *         &lt;element name="ReceivePaymentToDepositQueryRs" type="{}ReceivePaymentToDepositQueryRsType"/>
 *         &lt;element name="ChargeAddRs" type="{}ChargeAddRsType"/>
 *         &lt;element name="ChargeModRs" type="{}ChargeModRsType"/>
 *         &lt;element name="ChargeQueryRs" type="{}ChargeQueryRsType"/>
 *         &lt;element name="PurchaseOrderAddRs" type="{}PurchaseOrderAddRsType"/>
 *         &lt;element name="PurchaseOrderModRs" type="{}PurchaseOrderModRsType"/>
 *         &lt;element name="PurchaseOrderQueryRs" type="{}PurchaseOrderQueryRsType"/>
 *         &lt;element name="BillAddRs" type="{}BillAddRsType"/>
 *         &lt;element name="BillModRs" type="{}BillModRsType"/>
 *         &lt;element name="BillQueryRs" type="{}BillQueryRsType"/>
 *         &lt;element name="ItemReceiptAddRs" type="{}ItemReceiptAddRsType"/>
 *         &lt;element name="ItemReceiptModRs" type="{}ItemReceiptModRsType"/>
 *         &lt;element name="ItemReceiptQueryRs" type="{}ItemReceiptQueryRsType"/>
 *         &lt;element name="VendorCreditAddRs" type="{}VendorCreditAddRsType"/>
 *         &lt;element name="VendorCreditQueryRs" type="{}VendorCreditQueryRsType"/>
 *         &lt;element name="BillPaymentCheckAddRs" type="{}BillPaymentCheckAddRsType"/>
 *         &lt;element name="BillPaymentCheckModRs" type="{}BillPaymentCheckModRsType"/>
 *         &lt;element name="BillPaymentCheckQueryRs" type="{}BillPaymentCheckQueryRsType"/>
 *         &lt;element name="BillPaymentCreditCardAddRs" type="{}BillPaymentCreditCardAddRsType"/>
 *         &lt;element name="BillPaymentCreditCardQueryRs" type="{}BillPaymentCreditCardQueryRsType"/>
 *         &lt;element name="BillToPayQueryRs" type="{}BillToPayQueryRsType"/>
 *         &lt;element name="SalesTaxPaymentCheckQueryRs" type="{}SalesTaxPaymentCheckQueryRsType"/>
 *         &lt;element name="InventoryAdjustmentAddRs" type="{}InventoryAdjustmentAddRsType"/>
 *         &lt;element name="InventoryAdjustmentQueryRs" type="{}InventoryAdjustmentQueryRsType"/>
 *         &lt;element name="TimeTrackingAddRs" type="{}TimeTrackingAddRsType"/>
 *         &lt;element name="TimeTrackingModRs" type="{}TimeTrackingModRsType"/>
 *         &lt;element name="TimeTrackingQueryRs" type="{}TimeTrackingQueryRsType"/>
 *         &lt;element name="CheckAddRs" type="{}CheckAddRsType"/>
 *         &lt;element name="CheckModRs" type="{}CheckModRsType"/>
 *         &lt;element name="CheckQueryRs" type="{}CheckQueryRsType"/>
 *         &lt;element name="CreditCardChargeAddRs" type="{}CreditCardChargeAddRsType"/>
 *         &lt;element name="CreditCardChargeModRs" type="{}CreditCardChargeModRsType"/>
 *         &lt;element name="CreditCardChargeQueryRs" type="{}CreditCardChargeQueryRsType"/>
 *         &lt;element name="CreditCardCreditAddRs" type="{}CreditCardCreditAddRsType"/>
 *         &lt;element name="CreditCardCreditModRs" type="{}CreditCardCreditModRsType"/>
 *         &lt;element name="CreditCardCreditQueryRs" type="{}CreditCardCreditQueryRsType"/>
 *         &lt;element name="JournalEntryAddRs" type="{}JournalEntryAddRsType"/>
 *         &lt;element name="JournalEntryModRs" type="{}JournalEntryModRsType"/>
 *         &lt;element name="JournalEntryQueryRs" type="{}JournalEntryQueryRsType"/>
 *         &lt;element name="DepositAddRs" type="{}DepositAddRsType"/>
 *         &lt;element name="DepositModRs" type="{}DepositModRsType"/>
 *         &lt;element name="DepositQueryRs" type="{}DepositQueryRsType"/>
 *         &lt;element name="ListDelRs" type="{}ListDelRsType"/>
 *         &lt;element name="ListMergeRs" type="{}ListMergeRsType"/>
 *         &lt;element name="ListDeletedQueryRs" type="{}ListDeletedQueryRsType"/>
 *         &lt;element name="TxnDelRs" type="{}TxnDelRsType"/>
 *         &lt;element name="TxnVoidRs" type="{}TxnVoidRsType"/>
 *         &lt;element name="TxnDeletedQueryRs" type="{}TxnDeletedQueryRsType"/>
 *         &lt;element name="ClearedStatusModRs" type="{}ClearedStatusModRsType"/>
 *         &lt;element name="ListDisplayAddRs" type="{}ListDisplayAddRsType"/>
 *         &lt;element name="ListDisplayModRs" type="{}ListDisplayModRsType"/>
 *         &lt;element name="TxnDisplayAddRs" type="{}TxnDisplayAddRsType"/>
 *         &lt;element name="TxnDisplayModRs" type="{}TxnDisplayModRsType"/>
 *         &lt;element name="DataEventRecoveryInfoDelRs" type="{}DataEventRecoveryInfoDelRsType"/>
 *         &lt;element name="DataEventRecoveryInfoQueryRs" type="{}DataEventRecoveryInfoQueryRsType"/>
 *         &lt;element name="TransactionQueryRs" type="{}TransactionQueryRsType"/>
 *         &lt;element name="BuildAssemblyAddRs" type="{}BuildAssemblyAddRsType"/>
 *         &lt;element name="BuildAssemblyModRs" type="{}BuildAssemblyModRsType"/>
 *         &lt;element name="BuildAssemblyQueryRs" type="{}BuildAssemblyQueryRsType"/>
 *         &lt;element name="ItemAssembliesCanBuildQueryRs" type="{}ItemAssembliesCanBuildQueryRsType"/>
 *         &lt;element name="ARRefundCreditCardAddRs" type="{}ARRefundCreditCardAddRsType"/>
 *         &lt;element name="ARRefundCreditCardQueryRs" type="{}ARRefundCreditCardQueryRsType"/>
 *         &lt;element name="VehicleMileageAddRs" type="{}VehicleMileageAddRsType"/>
 *         &lt;element name="VehicleMileageQueryRs" type="{}VehicleMileageQueryRsType"/>
 *         &lt;element name="GeneralSummaryReportQueryRs" type="{}GeneralSummaryReportQueryRsType"/>
 *         &lt;element name="JobReportQueryRs" type="{}JobReportQueryRsType"/>
 *         &lt;element name="TimeReportQueryRs" type="{}TimeReportQueryRsType"/>
 *         &lt;element name="AgingReportQueryRs" type="{}AgingReportQueryRsType"/>
 *         &lt;element name="BudgetSummaryReportQueryRs" type="{}BudgetSummaryReportQueryRsType"/>
 *         &lt;element name="GeneralDetailReportQueryRs" type="{}GeneralDetailReportQueryRsType"/>
 *         &lt;element name="CustomDetailReportQueryRs" type="{}CustomDetailReportQueryRsType"/>
 *         &lt;element name="CustomSummaryReportQueryRs" type="{}CustomSummaryReportQueryRsType"/>
 *         &lt;element name="PayrollDetailReportQueryRs" type="{}PayrollDetailReportQueryRsType"/>
 *         &lt;element name="PayrollSummaryReportQueryRs" type="{}PayrollSummaryReportQueryRsType"/>
 *         &lt;element name="DataExtDefAddRs" type="{}DataExtDefAddRsType"/>
 *         &lt;element name="DataExtDefModRs" type="{}DataExtDefModRsType"/>
 *         &lt;element name="DataExtDefDelRs" type="{}DataExtDefDelRsType"/>
 *         &lt;element name="DataExtDefQueryRs" type="{}DataExtDefQueryRsType"/>
 *         &lt;element name="DataExtAddRs" type="{}DataExtAddRsType"/>
 *         &lt;element name="DataExtModRs" type="{}DataExtModRsType"/>
 *         &lt;element name="DataExtDelRs" type="{}DataExtDelRsType"/>
 *       &lt;/choice>
 *       &lt;attribute name="newMessageSetID" type="{}STRTYPE" />
 *       &lt;attribute name="messageSetStatusCode" type="{}INTTYPE" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "hostQueryRsOrCompanyQueryRsOrCompanyActivityQueryRs"
})
@XmlRootElement(name = "QBXMLMsgsRs")
public class QBXMLMsgsRs {

    @XmlElements({
        @XmlElement(name = "ListDeletedQueryRs", type = ListDeletedQueryRsType.class),
        @XmlElement(name = "CustomerTypeQueryRs", type = CustomerTypeQueryRsType.class),
        @XmlElement(name = "ReceivePaymentModRs", type = ReceivePaymentModRsType.class),
        @XmlElement(name = "CreditCardChargeAddRs", type = CreditCardChargeAddRsType.class),
        @XmlElement(name = "JobTypeAddRs", type = JobTypeAddRsType.class),
        @XmlElement(name = "UnitOfMeasureSetQueryRs", type = UnitOfMeasureSetQueryRsType.class),
        @XmlElement(name = "PayrollDetailReportQueryRs", type = PayrollDetailReportQueryRsType.class),
        @XmlElement(name = "ClassQueryRs", type = ClassQueryRsType.class),
        @XmlElement(name = "ItemDiscountModRs", type = ItemDiscountModRsType.class),
        @XmlElement(name = "ClassAddRs", type = ClassAddRsType.class),
        @XmlElement(name = "DepositAddRs", type = DepositAddRsType.class),
        @XmlElement(name = "ItemServiceQueryRs", type = ItemServiceQueryRsType.class),
        @XmlElement(name = "ShipMethodQueryRs", type = ShipMethodQueryRsType.class),
        @XmlElement(name = "SalesReceiptAddRs", type = SalesReceiptAddRsType.class),
        @XmlElement(name = "SalesTaxPaymentCheckQueryRs", type = SalesTaxPaymentCheckQueryRsType.class),
        @XmlElement(name = "EntityQueryRs", type = EntityQueryRsType.class),
        @XmlElement(name = "SalesRepAddRs", type = SalesRepAddRsType.class),
        @XmlElement(name = "ItemSubtotalAddRs", type = ItemSubtotalAddRsType.class),
        @XmlElement(name = "ItemInventoryModRs", type = ItemInventoryModRsType.class),
        @XmlElement(name = "DepositQueryRs", type = DepositQueryRsType.class),
        @XmlElement(name = "ToDoQueryRs", type = ToDoQueryRsType.class),
        @XmlElement(name = "VehicleQueryRs", type = VehicleQueryRsType.class),
        @XmlElement(name = "ItemReceiptAddRs", type = ItemReceiptAddRsType.class),
        @XmlElement(name = "EstimateAddRs", type = EstimateAddRsType.class),
        @XmlElement(name = "ItemSalesTaxGroupAddRs", type = ItemSalesTaxGroupAddRsType.class),
        @XmlElement(name = "BudgetSummaryReportQueryRs", type = BudgetSummaryReportQueryRsType.class),
        @XmlElement(name = "CreditMemoAddRs", type = CreditMemoAddRsType.class),
        @XmlElement(name = "DataExtAddRs", type = DataExtAddRsType.class),
        @XmlElement(name = "VendorQueryRs", type = VendorQueryRsType.class),
        @XmlElement(name = "DataExtDefQueryRs", type = DataExtDefQueryRsType.class),
        @XmlElement(name = "InvoiceModRs", type = InvoiceModRsType.class),
        @XmlElement(name = "BillPaymentCheckModRs", type = BillPaymentCheckModRsType.class),
        @XmlElement(name = "TemplateQueryRs", type = TemplateQueryRsType.class),
        @XmlElement(name = "AgingReportQueryRs", type = AgingReportQueryRsType.class),
        @XmlElement(name = "ItemDiscountQueryRs", type = ItemDiscountQueryRsType.class),
        @XmlElement(name = "JobReportQueryRs", type = JobReportQueryRsType.class),
        @XmlElement(name = "DepositModRs", type = DepositModRsType.class),
        @XmlElement(name = "PayrollItemWageAddRs", type = PayrollItemWageAddRsType.class),
        @XmlElement(name = "ItemFixedAssetModRs", type = ItemFixedAssetModRsType.class),
        @XmlElement(name = "EmployeeModRs", type = EmployeeModRsType.class),
        @XmlElement(name = "TimeTrackingQueryRs", type = TimeTrackingQueryRsType.class),
        @XmlElement(name = "GeneralSummaryReportQueryRs", type = GeneralSummaryReportQueryRsType.class),
        @XmlElement(name = "SalesTaxCodeAddRs", type = SalesTaxCodeAddRsType.class),
        @XmlElement(name = "JournalEntryQueryRs", type = JournalEntryQueryRsType.class),
        @XmlElement(name = "WorkersCompCodeModRs", type = WorkersCompCodeModRsType.class),
        @XmlElement(name = "ItemInventoryAddRs", type = ItemInventoryAddRsType.class),
        @XmlElement(name = "ListDisplayModRs", type = ListDisplayModRsType.class),
        @XmlElement(name = "CustomerQueryRs", type = CustomerQueryRsType.class),
        @XmlElement(name = "ItemGroupModRs", type = ItemGroupModRsType.class),
        @XmlElement(name = "EstimateModRs", type = EstimateModRsType.class),
        @XmlElement(name = "ItemSalesTaxGroupModRs", type = ItemSalesTaxGroupModRsType.class),
        @XmlElement(name = "DataExtDelRs", type = DataExtDelRsType.class),
        @XmlElement(name = "ItemSalesTaxAddRs", type = ItemSalesTaxAddRsType.class),
        @XmlElement(name = "ItemQueryRs", type = ItemQueryRsType.class),
        @XmlElement(name = "JobTypeQueryRs", type = JobTypeQueryRsType.class),
        @XmlElement(name = "SalesReceiptQueryRs", type = SalesReceiptQueryRsType.class),
        @XmlElement(name = "ChargeModRs", type = ChargeModRsType.class),
        @XmlElement(name = "ItemGroupQueryRs", type = ItemGroupQueryRsType.class),
        @XmlElement(name = "ClearedStatusModRs", type = ClearedStatusModRsType.class),
        @XmlElement(name = "SalesTaxCodeQueryRs", type = SalesTaxCodeQueryRsType.class),
        @XmlElement(name = "TermsQueryRs", type = TermsQueryRsType.class),
        @XmlElement(name = "CreditMemoModRs", type = CreditMemoModRsType.class),
        @XmlElement(name = "BillPaymentCreditCardQueryRs", type = BillPaymentCreditCardQueryRsType.class),
        @XmlElement(name = "SpecialItemAddRs", type = SpecialItemAddRsType.class),
        @XmlElement(name = "BillPaymentCheckQueryRs", type = BillPaymentCheckQueryRsType.class),
        @XmlElement(name = "ReceivePaymentAddRs", type = ReceivePaymentAddRsType.class),
        @XmlElement(name = "VendorTypeQueryRs", type = VendorTypeQueryRsType.class),
        @XmlElement(name = "InvoiceQueryRs", type = InvoiceQueryRsType.class),
        @XmlElement(name = "ItemGroupAddRs", type = ItemGroupAddRsType.class),
        @XmlElement(name = "UnitOfMeasureSetAddRs", type = UnitOfMeasureSetAddRsType.class),
        @XmlElement(name = "ItemOtherChargeQueryRs", type = ItemOtherChargeQueryRsType.class),
        @XmlElement(name = "ReceivePaymentQueryRs", type = ReceivePaymentQueryRsType.class),
        @XmlElement(name = "BuildAssemblyAddRs", type = BuildAssemblyAddRsType.class),
        @XmlElement(name = "CustomerTypeAddRs", type = CustomerTypeAddRsType.class),
        @XmlElement(name = "PayrollItemWageQueryRs", type = PayrollItemWageQueryRsType.class),
        @XmlElement(name = "DateDrivenTermsQueryRs", type = DateDrivenTermsQueryRsType.class),
        @XmlElement(name = "ItemPaymentQueryRs", type = ItemPaymentQueryRsType.class),
        @XmlElement(name = "CreditMemoQueryRs", type = CreditMemoQueryRsType.class),
        @XmlElement(name = "ChargeQueryRs", type = ChargeQueryRsType.class),
        @XmlElement(name = "ItemNonInventoryAddRs", type = ItemNonInventoryAddRsType.class),
        @XmlElement(name = "InventoryAdjustmentQueryRs", type = InventoryAdjustmentQueryRsType.class),
        @XmlElement(name = "BillModRs", type = BillModRsType.class),
        @XmlElement(name = "ItemFixedAssetQueryRs", type = ItemFixedAssetQueryRsType.class),
        @XmlElement(name = "SpecialAccountAddRs", type = SpecialAccountAddRsType.class),
        @XmlElement(name = "ShipMethodAddRs", type = ShipMethodAddRsType.class),
        @XmlElement(name = "ItemReceiptModRs", type = ItemReceiptModRsType.class),
        @XmlElement(name = "SalesRepModRs", type = SalesRepModRsType.class),
        @XmlElement(name = "ItemSubtotalModRs", type = ItemSubtotalModRsType.class),
        @XmlElement(name = "ItemServiceModRs", type = ItemServiceModRsType.class),
        @XmlElement(name = "CompanyActivityQueryRs", type = CompanyActivityQueryRsType.class),
        @XmlElement(name = "AccountAddRs", type = AccountAddRsType.class),
        @XmlElement(name = "PaymentMethodAddRs", type = PaymentMethodAddRsType.class),
        @XmlElement(name = "CreditCardCreditModRs", type = CreditCardCreditModRsType.class),
        @XmlElement(name = "CreditCardCreditQueryRs", type = CreditCardCreditQueryRsType.class),
        @XmlElement(name = "ARRefundCreditCardQueryRs", type = ARRefundCreditCardQueryRsType.class),
        @XmlElement(name = "TimeReportQueryRs", type = TimeReportQueryRsType.class),
        @XmlElement(name = "VendorCreditAddRs", type = VendorCreditAddRsType.class),
        @XmlElement(name = "CreditCardChargeModRs", type = CreditCardChargeModRsType.class),
        @XmlElement(name = "PayrollItemNonWageQueryRs", type = PayrollItemNonWageQueryRsType.class),
        @XmlElement(name = "CustomerMsgQueryRs", type = CustomerMsgQueryRsType.class),
        @XmlElement(name = "ItemFixedAssetAddRs", type = ItemFixedAssetAddRsType.class),
        @XmlElement(name = "HostQueryRs", type = HostQueryRsType.class),
        @XmlElement(name = "VendorTypeAddRs", type = VendorTypeAddRsType.class),
        @XmlElement(name = "CustomSummaryReportQueryRs", type = CustomSummaryReportQueryRsType.class),
        @XmlElement(name = "SalesReceiptModRs", type = SalesReceiptModRsType.class),
        @XmlElement(name = "ItemNonInventoryQueryRs", type = ItemNonInventoryQueryRsType.class),
        @XmlElement(name = "AccountModRs", type = AccountModRsType.class),
        @XmlElement(name = "VehicleMileageAddRs", type = VehicleMileageAddRsType.class),
        @XmlElement(name = "CreditCardChargeQueryRs", type = CreditCardChargeQueryRsType.class),
        @XmlElement(name = "SalesOrderQueryRs", type = SalesOrderQueryRsType.class),
        @XmlElement(name = "PurchaseOrderQueryRs", type = PurchaseOrderQueryRsType.class),
        @XmlElement(name = "BuildAssemblyModRs", type = BuildAssemblyModRsType.class),
        @XmlElement(name = "ItemInventoryQueryRs", type = ItemInventoryQueryRsType.class),
        @XmlElement(name = "ItemOtherChargeModRs", type = ItemOtherChargeModRsType.class),
        @XmlElement(name = "PayrollSummaryReportQueryRs", type = PayrollSummaryReportQueryRsType.class),
        @XmlElement(name = "ItemPaymentModRs", type = ItemPaymentModRsType.class),
        @XmlElement(name = "GeneralDetailReportQueryRs", type = GeneralDetailReportQueryRsType.class),
        @XmlElement(name = "ItemSalesTaxModRs", type = ItemSalesTaxModRsType.class),
        @XmlElement(name = "ItemDiscountAddRs", type = ItemDiscountAddRsType.class),
        @XmlElement(name = "VendorModRs", type = VendorModRsType.class),
        @XmlElement(name = "EmployeeQueryRs", type = EmployeeQueryRsType.class),
        @XmlElement(name = "AccountQueryRs", type = AccountQueryRsType.class),
        @XmlElement(name = "BillPaymentCheckAddRs", type = BillPaymentCheckAddRsType.class),
        @XmlElement(name = "PreferencesQueryRs", type = PreferencesQueryRsType.class),
        @XmlElement(name = "TxnDisplayModRs", type = TxnDisplayModRsType.class),
        @XmlElement(name = "VendorAddRs", type = VendorAddRsType.class),
        @XmlElement(name = "TxnDelRs", type = TxnDelRsType.class),
        @XmlElement(name = "BillAddRs", type = BillAddRsType.class),
        @XmlElement(name = "TxnVoidRs", type = TxnVoidRsType.class),
        @XmlElement(name = "SalesOrderAddRs", type = SalesOrderAddRsType.class),
        @XmlElement(name = "VehicleModRs", type = VehicleModRsType.class),
        @XmlElement(name = "PurchaseOrderAddRs", type = PurchaseOrderAddRsType.class),
        @XmlElement(name = "ItemSalesTaxQueryRs", type = ItemSalesTaxQueryRsType.class),
        @XmlElement(name = "SalesOrderModRs", type = SalesOrderModRsType.class),
        @XmlElement(name = "DataEventRecoveryInfoQueryRs", type = DataEventRecoveryInfoQueryRsType.class),
        @XmlElement(name = "CreditCardCreditAddRs", type = CreditCardCreditAddRsType.class),
        @XmlElement(name = "VendorCreditQueryRs", type = VendorCreditQueryRsType.class),
        @XmlElement(name = "ListDelRs", type = ListDelRsType.class),
        @XmlElement(name = "ItemInventoryAssemblyModRs", type = ItemInventoryAssemblyModRsType.class),
        @XmlElement(name = "OtherNameModRs", type = OtherNameModRsType.class),
        @XmlElement(name = "AccountTaxLineInfoQueryRs", type = AccountTaxLineInfoQueryRsType.class),
        @XmlElement(name = "ItemSubtotalQueryRs", type = ItemSubtotalQueryRsType.class),
        @XmlElement(name = "InventoryAdjustmentAddRs", type = InventoryAdjustmentAddRsType.class),
        @XmlElement(name = "WorkersCompCodeAddRs", type = WorkersCompCodeAddRsType.class),
        @XmlElement(name = "BillingRateAddRs", type = BillingRateAddRsType.class),
        @XmlElement(name = "ARRefundCreditCardAddRs", type = ARRefundCreditCardAddRsType.class),
        @XmlElement(name = "DataExtDefModRs", type = DataExtDefModRsType.class),
        @XmlElement(name = "OtherNameAddRs", type = OtherNameAddRsType.class),
        @XmlElement(name = "CustomerModRs", type = CustomerModRsType.class),
        @XmlElement(name = "DataExtDefAddRs", type = DataExtDefAddRsType.class),
        @XmlElement(name = "TimeTrackingModRs", type = TimeTrackingModRsType.class),
        @XmlElement(name = "CheckAddRs", type = CheckAddRsType.class),
        @XmlElement(name = "BillQueryRs", type = BillQueryRsType.class),
        @XmlElement(name = "ListMergeRs", type = ListMergeRsType.class),
        @XmlElement(name = "ItemOtherChargeAddRs", type = ItemOtherChargeAddRsType.class),
        @XmlElement(name = "BillingRateQueryRs", type = BillingRateQueryRsType.class),
        @XmlElement(name = "ToDoAddRs", type = ToDoAddRsType.class),
        @XmlElement(name = "ListDisplayAddRs", type = ListDisplayAddRsType.class),
        @XmlElement(name = "VehicleMileageQueryRs", type = VehicleMileageQueryRsType.class),
        @XmlElement(name = "ItemAssembliesCanBuildQueryRs", type = ItemAssembliesCanBuildQueryRsType.class),
        @XmlElement(name = "ItemNonInventoryModRs", type = ItemNonInventoryModRsType.class),
        @XmlElement(name = "ChargeAddRs", type = ChargeAddRsType.class),
        @XmlElement(name = "BillPaymentCreditCardAddRs", type = BillPaymentCreditCardAddRsType.class),
        @XmlElement(name = "BuildAssemblyQueryRs", type = BuildAssemblyQueryRsType.class),
        @XmlElement(name = "DataExtModRs", type = DataExtModRsType.class),
        @XmlElement(name = "ReceivePaymentToDepositQueryRs", type = ReceivePaymentToDepositQueryRsType.class),
        @XmlElement(name = "TxnDisplayAddRs", type = TxnDisplayAddRsType.class),
        @XmlElement(name = "TransactionQueryRs", type = TransactionQueryRsType.class),
        @XmlElement(name = "CheckModRs", type = CheckModRsType.class),
        @XmlElement(name = "PriceLevelAddRs", type = PriceLevelAddRsType.class),
        @XmlElement(name = "CompanyQueryRs", type = CompanyQueryRsType.class),
        @XmlElement(name = "DataEventRecoveryInfoDelRs", type = DataEventRecoveryInfoDelRsType.class),
        @XmlElement(name = "PaymentMethodQueryRs", type = PaymentMethodQueryRsType.class),
        @XmlElement(name = "CustomerMsgAddRs", type = CustomerMsgAddRsType.class),
        @XmlElement(name = "WorkersCompCodeQueryRs", type = WorkersCompCodeQueryRsType.class),
        @XmlElement(name = "PriceLevelQueryRs", type = PriceLevelQueryRsType.class),
        @XmlElement(name = "SalesRepQueryRs", type = SalesRepQueryRsType.class),
        @XmlElement(name = "EmployeeAddRs", type = EmployeeAddRsType.class),
        @XmlElement(name = "CheckQueryRs", type = CheckQueryRsType.class),
        @XmlElement(name = "TxnDeletedQueryRs", type = TxnDeletedQueryRsType.class),
        @XmlElement(name = "JournalEntryAddRs", type = JournalEntryAddRsType.class),
        @XmlElement(name = "BillToPayQueryRs", type = BillToPayQueryRsType.class),
        @XmlElement(name = "VehicleAddRs", type = VehicleAddRsType.class),
        @XmlElement(name = "ItemSalesTaxGroupQueryRs", type = ItemSalesTaxGroupQueryRsType.class),
        @XmlElement(name = "ItemInventoryAssemblyQueryRs", type = ItemInventoryAssemblyQueryRsType.class),
        @XmlElement(name = "ItemPaymentAddRs", type = ItemPaymentAddRsType.class),
        @XmlElement(name = "PurchaseOrderModRs", type = PurchaseOrderModRsType.class),
        @XmlElement(name = "CustomerAddRs", type = CustomerAddRsType.class),
        @XmlElement(name = "EstimateQueryRs", type = EstimateQueryRsType.class),
        @XmlElement(name = "ItemReceiptQueryRs", type = ItemReceiptQueryRsType.class),
        @XmlElement(name = "DataExtDefDelRs", type = DataExtDefDelRsType.class),
        @XmlElement(name = "PriceLevelModRs", type = PriceLevelModRsType.class),
        @XmlElement(name = "CustomDetailReportQueryRs", type = CustomDetailReportQueryRsType.class),
        @XmlElement(name = "JournalEntryModRs", type = JournalEntryModRsType.class),
        @XmlElement(name = "InvoiceAddRs", type = InvoiceAddRsType.class),
        @XmlElement(name = "ItemServiceAddRs", type = ItemServiceAddRsType.class),
        @XmlElement(name = "ItemInventoryAssemblyAddRs", type = ItemInventoryAssemblyAddRsType.class),
        @XmlElement(name = "DateDrivenTermsAddRs", type = DateDrivenTermsAddRsType.class),
        @XmlElement(name = "StandardTermsQueryRs", type = StandardTermsQueryRsType.class),
        @XmlElement(name = "StandardTermsAddRs", type = StandardTermsAddRsType.class),
        @XmlElement(name = "OtherNameQueryRs", type = OtherNameQueryRsType.class),
        @XmlElement(name = "TimeTrackingAddRs", type = TimeTrackingAddRsType.class)
    })
    protected List<Object> hostQueryRsOrCompanyQueryRsOrCompanyActivityQueryRs;
    @XmlAttribute
    protected String newMessageSetID;
    @XmlAttribute
    protected BigInteger messageSetStatusCode;

    /**
     * Gets the value of the hostQueryRsOrCompanyQueryRsOrCompanyActivityQueryRs property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the hostQueryRsOrCompanyQueryRsOrCompanyActivityQueryRs property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getHostQueryRsOrCompanyQueryRsOrCompanyActivityQueryRs().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ListDeletedQueryRsType }
     * {@link CustomerTypeQueryRsType }
     * {@link ReceivePaymentModRsType }
     * {@link CreditCardChargeAddRsType }
     * {@link JobTypeAddRsType }
     * {@link UnitOfMeasureSetQueryRsType }
     * {@link PayrollDetailReportQueryRsType }
     * {@link ClassQueryRsType }
     * {@link ItemDiscountModRsType }
     * {@link ClassAddRsType }
     * {@link DepositAddRsType }
     * {@link ItemServiceQueryRsType }
     * {@link ShipMethodQueryRsType }
     * {@link SalesReceiptAddRsType }
     * {@link SalesTaxPaymentCheckQueryRsType }
     * {@link EntityQueryRsType }
     * {@link SalesRepAddRsType }
     * {@link ItemSubtotalAddRsType }
     * {@link ItemInventoryModRsType }
     * {@link DepositQueryRsType }
     * {@link ToDoQueryRsType }
     * {@link VehicleQueryRsType }
     * {@link ItemReceiptAddRsType }
     * {@link EstimateAddRsType }
     * {@link ItemSalesTaxGroupAddRsType }
     * {@link BudgetSummaryReportQueryRsType }
     * {@link CreditMemoAddRsType }
     * {@link DataExtAddRsType }
     * {@link VendorQueryRsType }
     * {@link DataExtDefQueryRsType }
     * {@link InvoiceModRsType }
     * {@link BillPaymentCheckModRsType }
     * {@link TemplateQueryRsType }
     * {@link AgingReportQueryRsType }
     * {@link ItemDiscountQueryRsType }
     * {@link JobReportQueryRsType }
     * {@link DepositModRsType }
     * {@link PayrollItemWageAddRsType }
     * {@link ItemFixedAssetModRsType }
     * {@link EmployeeModRsType }
     * {@link TimeTrackingQueryRsType }
     * {@link GeneralSummaryReportQueryRsType }
     * {@link SalesTaxCodeAddRsType }
     * {@link JournalEntryQueryRsType }
     * {@link WorkersCompCodeModRsType }
     * {@link ItemInventoryAddRsType }
     * {@link ListDisplayModRsType }
     * {@link CustomerQueryRsType }
     * {@link ItemGroupModRsType }
     * {@link EstimateModRsType }
     * {@link ItemSalesTaxGroupModRsType }
     * {@link DataExtDelRsType }
     * {@link ItemSalesTaxAddRsType }
     * {@link ItemQueryRsType }
     * {@link JobTypeQueryRsType }
     * {@link SalesReceiptQueryRsType }
     * {@link ChargeModRsType }
     * {@link ItemGroupQueryRsType }
     * {@link ClearedStatusModRsType }
     * {@link SalesTaxCodeQueryRsType }
     * {@link TermsQueryRsType }
     * {@link CreditMemoModRsType }
     * {@link BillPaymentCreditCardQueryRsType }
     * {@link SpecialItemAddRsType }
     * {@link BillPaymentCheckQueryRsType }
     * {@link ReceivePaymentAddRsType }
     * {@link VendorTypeQueryRsType }
     * {@link InvoiceQueryRsType }
     * {@link ItemGroupAddRsType }
     * {@link UnitOfMeasureSetAddRsType }
     * {@link ItemOtherChargeQueryRsType }
     * {@link ReceivePaymentQueryRsType }
     * {@link BuildAssemblyAddRsType }
     * {@link CustomerTypeAddRsType }
     * {@link PayrollItemWageQueryRsType }
     * {@link DateDrivenTermsQueryRsType }
     * {@link ItemPaymentQueryRsType }
     * {@link CreditMemoQueryRsType }
     * {@link ChargeQueryRsType }
     * {@link ItemNonInventoryAddRsType }
     * {@link InventoryAdjustmentQueryRsType }
     * {@link BillModRsType }
     * {@link ItemFixedAssetQueryRsType }
     * {@link SpecialAccountAddRsType }
     * {@link ShipMethodAddRsType }
     * {@link ItemReceiptModRsType }
     * {@link SalesRepModRsType }
     * {@link ItemSubtotalModRsType }
     * {@link ItemServiceModRsType }
     * {@link CompanyActivityQueryRsType }
     * {@link AccountAddRsType }
     * {@link PaymentMethodAddRsType }
     * {@link CreditCardCreditModRsType }
     * {@link CreditCardCreditQueryRsType }
     * {@link ARRefundCreditCardQueryRsType }
     * {@link TimeReportQueryRsType }
     * {@link VendorCreditAddRsType }
     * {@link CreditCardChargeModRsType }
     * {@link PayrollItemNonWageQueryRsType }
     * {@link CustomerMsgQueryRsType }
     * {@link ItemFixedAssetAddRsType }
     * {@link HostQueryRsType }
     * {@link VendorTypeAddRsType }
     * {@link CustomSummaryReportQueryRsType }
     * {@link SalesReceiptModRsType }
     * {@link ItemNonInventoryQueryRsType }
     * {@link AccountModRsType }
     * {@link VehicleMileageAddRsType }
     * {@link CreditCardChargeQueryRsType }
     * {@link SalesOrderQueryRsType }
     * {@link PurchaseOrderQueryRsType }
     * {@link BuildAssemblyModRsType }
     * {@link ItemInventoryQueryRsType }
     * {@link ItemOtherChargeModRsType }
     * {@link PayrollSummaryReportQueryRsType }
     * {@link ItemPaymentModRsType }
     * {@link GeneralDetailReportQueryRsType }
     * {@link ItemSalesTaxModRsType }
     * {@link ItemDiscountAddRsType }
     * {@link VendorModRsType }
     * {@link EmployeeQueryRsType }
     * {@link AccountQueryRsType }
     * {@link BillPaymentCheckAddRsType }
     * {@link PreferencesQueryRsType }
     * {@link TxnDisplayModRsType }
     * {@link VendorAddRsType }
     * {@link TxnDelRsType }
     * {@link BillAddRsType }
     * {@link TxnVoidRsType }
     * {@link SalesOrderAddRsType }
     * {@link VehicleModRsType }
     * {@link PurchaseOrderAddRsType }
     * {@link ItemSalesTaxQueryRsType }
     * {@link SalesOrderModRsType }
     * {@link DataEventRecoveryInfoQueryRsType }
     * {@link CreditCardCreditAddRsType }
     * {@link VendorCreditQueryRsType }
     * {@link ListDelRsType }
     * {@link ItemInventoryAssemblyModRsType }
     * {@link OtherNameModRsType }
     * {@link AccountTaxLineInfoQueryRsType }
     * {@link ItemSubtotalQueryRsType }
     * {@link InventoryAdjustmentAddRsType }
     * {@link WorkersCompCodeAddRsType }
     * {@link BillingRateAddRsType }
     * {@link ARRefundCreditCardAddRsType }
     * {@link DataExtDefModRsType }
     * {@link OtherNameAddRsType }
     * {@link CustomerModRsType }
     * {@link DataExtDefAddRsType }
     * {@link TimeTrackingModRsType }
     * {@link CheckAddRsType }
     * {@link BillQueryRsType }
     * {@link ListMergeRsType }
     * {@link ItemOtherChargeAddRsType }
     * {@link BillingRateQueryRsType }
     * {@link ToDoAddRsType }
     * {@link ListDisplayAddRsType }
     * {@link VehicleMileageQueryRsType }
     * {@link ItemAssembliesCanBuildQueryRsType }
     * {@link ItemNonInventoryModRsType }
     * {@link ChargeAddRsType }
     * {@link BillPaymentCreditCardAddRsType }
     * {@link BuildAssemblyQueryRsType }
     * {@link DataExtModRsType }
     * {@link ReceivePaymentToDepositQueryRsType }
     * {@link TxnDisplayAddRsType }
     * {@link TransactionQueryRsType }
     * {@link CheckModRsType }
     * {@link PriceLevelAddRsType }
     * {@link CompanyQueryRsType }
     * {@link DataEventRecoveryInfoDelRsType }
     * {@link PaymentMethodQueryRsType }
     * {@link CustomerMsgAddRsType }
     * {@link WorkersCompCodeQueryRsType }
     * {@link PriceLevelQueryRsType }
     * {@link SalesRepQueryRsType }
     * {@link EmployeeAddRsType }
     * {@link CheckQueryRsType }
     * {@link TxnDeletedQueryRsType }
     * {@link JournalEntryAddRsType }
     * {@link BillToPayQueryRsType }
     * {@link VehicleAddRsType }
     * {@link ItemSalesTaxGroupQueryRsType }
     * {@link ItemInventoryAssemblyQueryRsType }
     * {@link ItemPaymentAddRsType }
     * {@link PurchaseOrderModRsType }
     * {@link CustomerAddRsType }
     * {@link EstimateQueryRsType }
     * {@link ItemReceiptQueryRsType }
     * {@link DataExtDefDelRsType }
     * {@link PriceLevelModRsType }
     * {@link CustomDetailReportQueryRsType }
     * {@link JournalEntryModRsType }
     * {@link InvoiceAddRsType }
     * {@link ItemServiceAddRsType }
     * {@link ItemInventoryAssemblyAddRsType }
     * {@link DateDrivenTermsAddRsType }
     * {@link StandardTermsQueryRsType }
     * {@link StandardTermsAddRsType }
     * {@link OtherNameQueryRsType }
     * {@link TimeTrackingAddRsType }
     * 
     * 
     */
    public List<Object> getHostQueryRsOrCompanyQueryRsOrCompanyActivityQueryRs() {
        if (hostQueryRsOrCompanyQueryRsOrCompanyActivityQueryRs == null) {
            hostQueryRsOrCompanyQueryRsOrCompanyActivityQueryRs = new ArrayList<Object>();
        }
        return this.hostQueryRsOrCompanyQueryRsOrCompanyActivityQueryRs;
    }

    /**
     * Gets the value of the newMessageSetID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNewMessageSetID() {
        return newMessageSetID;
    }

    /**
     * Sets the value of the newMessageSetID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNewMessageSetID(String value) {
        this.newMessageSetID = value;
    }

    /**
     * Gets the value of the messageSetStatusCode property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getMessageSetStatusCode() {
        return messageSetStatusCode;
    }

    /**
     * Sets the value of the messageSetStatusCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setMessageSetStatusCode(BigInteger value) {
        this.messageSetStatusCode = value;
    }

}
