package com.picsauditing.rbic
dialect "java"

import com.picsauditing.rbic.ContractorModel;
import com.picsauditing.jpa.entities.LowMedHigh;

rule "numberOfSeatsInAircraft"
// criteriaId: 976
// operatorId: 34878
// questionId: 16965
    when
        $con : ContractorModel($numberOfSeats : findQuestionAnswerAsInt(16965), $numberOfSeats > 0)
    then
        $con.updateCriteriaLimitForContractor(981 , 34878,$numberOfSeats * 3000000);
    end
