package com.picsauditing.rbic
dialect "java"

import com.picsauditing.rbic.ContractorModel;
import com.picsauditing.jpa.entities.LowMedHigh;

rule "workingOnHighFloor"
    when
        $con : ContractorModel( findQuestionAnswerAsNumber(16961) > 9)
    then
        $con.updateCriteriaLimitForContractor(523, 34887, 3000123);
    end
rule "workingOnLowFloor"
    when
        $con : ContractorModel(findQuestionAnswerAsNumber(16961) <= 9)
    then
        $con.updateCriteriaLimitForContractor(523, 34887, 1000123);
    end

