package com.picsauditing.rbic
dialect "java"

import com.picsauditing.rbic.ContractorModel;
import com.picsauditing.jpa.entities.LowMedHigh;

rule "tag"
    when
        $con : ContractorModel(hasTag(201), worksFor(11879))
    then
        $con.randomInsuranceLimit = 7000000;
    end

rule "pqf"
    when
        $con : ContractorModel($answer : findPqfQuestionAnswer(76), $answer == "Don Couch")
    then
        $con.randomInsuranceLimit = 6000000;
    end

rule "highRisk"
   when
       $con : ContractorModel($answer : safetyRisk, $answer == LowMedHigh.High)
   then
       $con.randomInsuranceLimit = 5000000;
   end

rule "medRisk"
   when
       $con : ContractorModel($answer : safetyRisk, $answer == LowMedHigh.Med)
   then
       $con.randomInsuranceLimit = 2000000;
   end

rule "lowRisk"
   when
       $con : ContractorModel($answer : safetyRisk, $answer == LowMedHigh.Low)
   then
       $con.randomInsuranceLimit = 1000000;
   end