package com.picsauditing.jpa.entities;
// Generated Nov 15, 2007 2:20:12 PM by Hibernate Tools 3.2.0.b11


import java.util.ArrayList;
import java.util.Collection;
import java.util.Date;
import java.util.List;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedNativeQueries;
import javax.persistence.NamedNativeQuery;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.OneToMany;
import javax.persistence.SqlResultSetMapping;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.EntityResult;
import javax.persistence.FieldResult;

import org.hibernate.annotations.Where;



/**
 * ContractorInfoReport generated by hbm2java
 */
@Entity
@SqlResultSetMapping(name="needsOshaAndEmrVerificationMapping",
		entities={@EntityResult(entityClass=ContractorInfoReport.class)})

@NamedNativeQueries({		
@NamedNativeQuery(name="needsOshaAndEmrVerification",
		query="select c.id, c.pqfAuditor_id, c.pqfSubmittedDate from contractor_info c join accounts a on c.id=a.id and a.active='Y' "+
		"join pqfdata e on c.id=e.conID and e.questionID in (889,1519,1617) and e.dateVerified='0000-00-00' where e.conID > 0 "+
		"union select c.id, c.pqfAuditor_id, c.pqfSubmittedDate from contractor_info c join accounts a on c.id=a.id and a.active='Y' "+
		"left join osha o on c.id=o.conID and (o.verifiedDate1 is null or o.verifiedDate2 is null or o.verifiedDate3 is null) where o.conID > 0 "+
		"order by pqfSubmittedDate desc",
		resultSetMapping="needsOshaAndEmrVerificationMapping"),
@NamedNativeQuery(name="needsEmrVerification",
		query="select c.id, c.pqfAuditor_id, c.pqfSubmittedDate from contractor_info c join accounts a on c.id=a.id and a.active='Y'" +
		" join pqfdata e on c.id=e.conID and e.questionID in (889,1519,1617) and e.dateVerified='0000-00-00' where e.conID > 0 "+
		"order by pqfSubmittedDate desc",
		resultSetMapping="needsOshaAndEmrVerificationMapping")
})

/*@NamedNativeQuery(name="needsOshaAndEmrVerification",
		query="select c.id, c.pqfAuditor_id, c.pqfSubmittedDate from contractor_info c join accounts a on c.id=a.id and a.active='Y' join pqfdata e on c.id=e.conID and e.questionID in (889,1519,1617) and e.dateVerified='0000-00-00' where e.conID > 0", 
		resultSetMapping="needsOshaAndEmrVerificationMapping")
*/		
@NamedQueries({
	@NamedQuery(name="contractorsByName", query="select cr from ContractorInfoReport cr where cr.account.name like :name order by cr.pqfSubmittedDate desc"),
	@NamedQuery(name="contractorsByAuditor", query="select cr from ContractorInfoReport cr where cr.pqfAuditorId=:pqfAuditorId order by cr.pqfSubmittedDate desc"),
	@NamedQuery(name="getActiveContractors", query="select cr from ContractorInfoReport cr where cr.account.active='Y' order by cr.pqfSubmittedDate desc")
})

@Table(name="contractor_info"
)
public class ContractorInfoReport  implements java.io.Serializable {


     private int id;
     private AccountReport account;
     private int pqfAuditorId;
     private Date pqfSubmittedDate;
     private List<GeneralContractor> generalContractors = new ArrayList<GeneralContractor>(0);
     private Collection<OshaLogReport> oshaLogs = new ArrayList<OshaLogReport>(0);
     private List<PqfLogReport> emrLogs = new ArrayList<PqfLogReport>(0);

    public ContractorInfoReport() {
    }

	
    public ContractorInfoReport(int id, AccountReport account, int pqfAuditorId, Date pqfSubmittedDate) {
        this.id = id;
        this.account = account;
        this.pqfAuditorId = pqfAuditorId;
        this.pqfSubmittedDate = pqfSubmittedDate;
    }
    public ContractorInfoReport(int id, AccountReport account, int pqfAuditorId, Date pqfSubmittedDate, List<GeneralContractor> generalContractors, Collection<OshaLogReport> oshaLogs, List<PqfLogReport> emrLogs) {
       this.id = id;
       this.account = account;
       this.pqfAuditorId = pqfAuditorId;
       this.generalContractors = generalContractors;
       this.oshaLogs = oshaLogs;
       this.emrLogs = emrLogs;
       this.pqfSubmittedDate = pqfSubmittedDate;
    }
   
     @Id 
    
    @Column(name="id", nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id", nullable=false, insertable=false, updatable=false)
    public AccountReport getAccount() {
        return this.account;
    }

public void setAccount(AccountReport account) {
    this.account = account;
}

@OneToMany(fetch=FetchType.LAZY, mappedBy="contractorInfo")
    public Collection<OshaLogReport> getOshaLogs() {
        return this.oshaLogs;
    }
    
    public void setOshaLogs(Collection<OshaLogReport> oshaLogs) {
        this.oshaLogs = oshaLogs;
    }
//@OneToMany(fetch=FetchType.LAZY, mappedBy="contractorInfoReport")
    @OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY)
    @JoinColumn(name="conID")
     //@Where(clause="questionID=126 or questionID=889 or questionID=1519")
    @Where(clause="questionID in (889,1519,1617)")
    public List<PqfLogReport> getEmrLogs() {
        return this.emrLogs;
    }
    
    public void setEmrLogs(List<PqfLogReport> emrLogs) {
        this.emrLogs = emrLogs;
    }
    
    @Column(name="pqfAuditor_id", nullable=false)
    public int getPqfAuditorId() {
        return this.pqfAuditorId;
    }
    
    public void setPqfAuditorId(int pqfAuditorId) {
        this.pqfAuditorId = pqfAuditorId;
    }
    
    @OneToMany(fetch=FetchType.LAZY, mappedBy="contractorInfo")
    public List<GeneralContractor> getGeneralContractors() {
        return this.generalContractors;
    }
    
    public void setGeneralContractors(List<GeneralContractor> generalContractors) {
        this.generalContractors = generalContractors;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="pqfSubmittedDate", nullable=false, length=10)
    public Date getPqfSubmittedDate() {
        return this.pqfSubmittedDate;
    }
    
    public void setPqfSubmittedDate(Date pqfSubmittedDate) {
        this.pqfSubmittedDate = pqfSubmittedDate;
    }


}


