package com.picsauditing.jpa.entities;
// Generated Nov 15, 2007 2:20:12 PM by Hibernate Tools 3.2.0.b11


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * FacilityId generated by hbm2java
 */
@Embeddable
public class FacilityId  implements java.io.Serializable {


     private int opId;
     private int corporateId;

    public FacilityId() {
    }

    public FacilityId(int opId, int corporateId) {
       this.opId = opId;
       this.corporateId = corporateId;
    }
   

    @Column(name="opID", nullable=false)
    public int getOpId() {
        return this.opId;
    }
    
    public void setOpId(int opId) {
        this.opId = opId;
    }

    @Column(name="corporateID", nullable=false)
    public int getCorporateId() {
        return this.corporateId;
    }
    
    public void setCorporateId(int corporateId) {
        this.corporateId = corporateId;
    }




}


