package com.picsauditing.jpa.entities;
// Generated Nov 15, 2007 2:20:12 PM by Hibernate Tools 3.2.0.b11


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Pqfcategory generated by hbm2java
 */
@Entity
@Table(name="pqfcategories"
)
public class Pqfcategory  implements java.io.Serializable {


     private Short catId;
     private String auditType;
     private String category;
     private byte number;
     private short numRequired;
     private short numQuestions;

    public Pqfcategory() {
    }

    public Pqfcategory(String auditType, String category, byte number, short numRequired, short numQuestions) {
       this.auditType = auditType;
       this.category = category;
       this.number = number;
       this.numRequired = numRequired;
       this.numQuestions = numQuestions;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="catID", nullable=false)
    public Short getCatId() {
        return this.catId;
    }
    
    public void setCatId(Short catId) {
        this.catId = catId;
    }
    
    @Column(name="auditType", nullable=false, length=7)
    public String getAuditType() {
        return this.auditType;
    }
    
    public void setAuditType(String auditType) {
        this.auditType = auditType;
    }
    
    @Column(name="category", nullable=false)
    public String getCategory() {
        return this.category;
    }
    
    public void setCategory(String category) {
        this.category = category;
    }
    
    @Column(name="number", nullable=false)
    public byte getNumber() {
        return this.number;
    }
    
    public void setNumber(byte number) {
        this.number = number;
    }
    
    @Column(name="numRequired", nullable=false)
    public short getNumRequired() {
        return this.numRequired;
    }
    
    public void setNumRequired(short numRequired) {
        this.numRequired = numRequired;
    }
    
    @Column(name="numQuestions", nullable=false)
    public short getNumQuestions() {
        return this.numQuestions;
    }
    
    public void setNumQuestions(short numQuestions) {
        this.numQuestions = numQuestions;
    }




}


