package com.picsauditing.jpa.entities;
// Generated Nov 15, 2007 2:20:12 PM by Hibernate Tools 3.2.0.b11


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PqfLogId generated by hbm2java
 */
@Embeddable
public class PqfLogId  implements java.io.Serializable {


     private int conId;
     private short questionId;

    public PqfLogId() {
    }

    public PqfLogId(int conId, short questionId) {
       this.conId = conId;
       this.questionId = questionId;
    }
   

    @Column(name="conID", nullable=false)
    public int getConId() {
        return this.conId;
    }
    
    public void setConId(int conId) {
        this.conId = conId;
    }

    @Column(name="questionID", nullable=false)
    public short getQuestionId() {
        return this.questionId;
    }
    
    public void setQuestionId(short questionId) {
        this.questionId = questionId;
    }




}


