package com.picsauditing.jpa.entities;
// Generated Nov 15, 2007 2:20:12 PM by Hibernate Tools 3.2.0.b11


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Pqfsubcategory generated by hbm2java
 */
@Entity
@Table(name="pqfsubcategories"
)
public class Pqfsubcategory  implements java.io.Serializable {


     private Short subCatId;
     private String subCategory;
     private short categoryId;
     private byte number;

    public Pqfsubcategory() {
    }

    public Pqfsubcategory(String subCategory, short categoryId, byte number) {
       this.subCategory = subCategory;
       this.categoryId = categoryId;
       this.number = number;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="subCatID", nullable=false)
    public Short getSubCatId() {
        return this.subCatId;
    }
    
    public void setSubCatId(Short subCatId) {
        this.subCatId = subCatId;
    }
    
    @Column(name="subCategory", nullable=false)
    public String getSubCategory() {
        return this.subCategory;
    }
    
    public void setSubCategory(String subCategory) {
        this.subCategory = subCategory;
    }
    
    @Column(name="categoryID", nullable=false)
    public short getCategoryId() {
        return this.categoryId;
    }
    
    public void setCategoryId(short categoryId) {
        this.categoryId = categoryId;
    }
    
    @Column(name="number", nullable=false)
    public byte getNumber() {
        return this.number;
    }
    
    public void setNumber(byte number) {
        this.number = number;
    }




}


