package com.picsauditing.salecommission.invoice.strategy;

import com.picsauditing.PICS.BillingService;
import com.picsauditing.PICS.FeeService;
import com.picsauditing.dao.InvoiceCommissionDAO;
import org.springframework.beans.factory.annotation.Autowired;

import com.picsauditing.dao.ContractorAccountDAO;
import com.picsauditing.jpa.entities.Invoice;

/**
 * This class contains all the logic for calculating the revenue generated by each Client Site that
 * should be split by the Sales Representative/Account Manager.
 */
public abstract class AbstractInvoiceCommissionStrategy implements InvoiceCommissionStrategy<Invoice> {

    @Autowired
    protected InvoiceCommissionDAO invoiceCommissionDAO;
	@Autowired
	protected ContractorAccountDAO contractorAccountDAO;
	@Autowired
	protected BillingService billingService;
    @Autowired
    protected FeeService feeService;

	public void processInvoiceCommission(Invoice invoice) {
		if (hasStrategyAlreadyProcessed(invoice)) {
			return;
		}

		buildInvoiceCommissions(invoice);
	}

	protected abstract boolean hasStrategyAlreadyProcessed(Invoice invoice);

	protected abstract void buildInvoiceCommissions(Invoice invoice);

}