SET SQL_MODE='';
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO';
ALTER TABLE `report` CHANGE COLUMN `ownerID` `ownerID` INT(11) NOT NULL  ,
  ADD CONSTRAINT `FK_report_owner`
  FOREIGN KEY (`ownerID` )
  REFERENCES `users` (`id` )
  ON DELETE NO ACTION
  ON UPDATE NO ACTION
, ADD INDEX `FK_report_owner` (`ownerID` ASC) ;
