drop table if exists app_language;

create table `app_language`( `locale` varchar(5) NOT NULL , `language` varchar(2) NOT NULL , `country` varchar(2) , `status` varchar(50) NOT NULL DEFAULT 'Future' , PRIMARY KEY (`locale`))  ;

alter table `pics_pruned`.`app_language` add unique `language_country` (`language`, `country`);

insert into app_language(`locale`, `language`, `country`)
values ('sq', 'sq', NULL),
('ar_DZ', 'ar', 'DZ'),
('ar_BH', 'ar', 'BH'),
('ar_EG', 'ar', 'EG'),
('ar_IQ', 'ar', 'IQ'),
('ar_JO', 'ar', 'JO'),
('ar_KW', 'ar', 'KW'),
('ar_LB', 'ar', 'LB'),
('ar_LY', 'ar', 'LY'),
('ar_MA', 'ar', 'MA'),
('ar_OM', 'ar', 'OM'),
('ar_QA', 'ar', 'QA'),
('ar_SA', 'ar', 'SA'),
('ar_SD', 'ar', 'SD'),
('ar_SY', 'ar', 'SY'),
('ar_TN', 'ar', 'TN'),
('ar_AE', 'ar', 'AE'),
('ar_YE', 'ar', 'YE'),
('be', 'be', NULL),
('bg', 'bg', NULL),
('ca', 'ca', NULL),
('zh_CN', 'zh', 'CN'),
('zh_HK', 'zh', 'HK'),
('zh_SG', 'zh', 'SG'),
('zh_TW', 'zh', 'TW'),
('hr', 'hr', NULL),
('cs', 'cs', NULL),
('da', 'da', NULL),
('nl', 'nl', NULL),
('nl_BE', 'nl', 'BE'),
('nl_NL', 'nl', 'NL'),
('en_AU', 'en', 'AU'),
('en_CA', 'en', 'CA'),
('en_IN', 'en', 'IN'),
('en_IE', 'en', 'IE'),
('en_MT', 'en', 'MT'),
('en_NZ', 'en', 'NZ'),
('en_PH', 'en', 'PH'),
('en_SG', 'en', 'SG'),
('en_ZA', 'en', 'ZA'),
('en_GB', 'en', 'GB'),
('en_US', 'en', 'US'),
('et', 'et', NULL),
('fi', 'fi', NULL),
('fr_BE', 'fr', 'BE'),
('fr_CA', 'fr', 'CA'),
('fr_FR', 'fr', 'FR'),
('fr_LU', 'fr', 'LU'),
('fr_CH', 'fr', 'CH'),
('de_AT', 'de', 'AT'),
('de_DE', 'de', 'DE'),
('de_LU', 'de', 'LU'),
('de_CH', 'de', 'CH'),
('el_CY', 'el', 'CY'),
('el_GR', 'el', 'GR'),
('iw', 'iw', NULL),
('hi', 'hi', NULL),
('hu', 'hu', NULL),
('is', 'is', NULL),
('in', 'in', NULL),
('ga', 'ga', NULL),
('it_IT', 'it', 'IT'),
('it_CH', 'it', 'CH'),
('ja', 'ja', NULL),
('ko', 'ko', NULL),
('lv', 'lv', NULL),
('lt', 'lt', NULL),
('mk', 'mk', NULL),
('ms', 'ms', NULL),
('mt', 'mt', NULL),
('no', 'no', NULL),
('pl', 'pl', NULL),
('pl_PL', 'pl', 'PL'),
('pt_BR', 'pt', 'BR'),
('pt_PT', 'pt', 'PT'),
('ro', 'ro', NULL),
('ru', 'ru', NULL),
('sr_BA', 'sr', 'BA'),
('sr_ME', 'sr', 'ME'),
('sr_CS', 'sr', 'CS'),
('sr_RS', 'sr', 'RS'),
('sk', 'sk', NULL),
('sl', 'sl', NULL),
('es_AR', 'es', 'AR'),
('es_BO', 'es', 'BO'),
('es_CL', 'es', 'CL'),
('es_CO', 'es', 'CO'),
('es_CR', 'es', 'CR'),
('es_DO', 'es', 'DO'),
('es_EC', 'es', 'EC'),
('es_SV', 'es', 'SV'),
('es_GT', 'es', 'GT'),
('es_HN', 'es', 'HN'),
('es_MX', 'es', 'MX'),
('es_NI', 'es', 'NI'),
('es_PA', 'es', 'PA'),
('es_PY', 'es', 'PY'),
('es_PE', 'es', 'PE'),
('es_PR', 'es', 'PR'),
('es_ES', 'es', 'ES'),
('es_US', 'es', 'US'),
('es_UY', 'es', 'UY'),
('es_VE', 'es', 'VE'),
('sv', 'sv', NULL),
('th', 'th', NULL),
('tr', 'tr', NULL),
('uk', 'uk', NULL),
('vi', 'vi', NULL);

update app_language
set status = 'Stable'
where `language` in ('en','fr','es','de','fi','sv','no','pt');

update app_language
set status = 'Beta'
where `language` in ('nl', 'zh');