ALTER TABLE `ref_country`   
  ADD COLUMN `id` INT(11) NOT NULL FIRST,
  ADD COLUMN `createdBy` INT(11) NULL AFTER `id`,
  ADD COLUMN `creationDate` DATETIME NULL AFTER `createdBy`,
  ADD COLUMN `updatedBy` INT(11) NULL AFTER `creationDate`,
  ADD COLUMN `updateDate` DATETIME NULL AFTER `updatedBy`,
  CHANGE `isoCode` `isoCode` VARCHAR(10) CHARSET latin1 COLLATE latin1_swedish_ci DEFAULT ''  NULL,
  CHANGE `proforma` `proforma` TINYINT(4) DEFAULT 0  NOT NULL  AFTER `currency`,
  CHANGE `csrID` `csrID` INT(11) NULL  AFTER `proforma`,
  CHANGE `phone` `csrPhone` VARCHAR(30) CHARSET utf8 COLLATE utf8_general_ci NULL  AFTER `csrID`,
  CHANGE `fax` `csrFax` VARCHAR(30) CHARSET utf8 COLLATE utf8_general_ci NULL  AFTER `csrPhone`,
  CHANGE `picsEmail` `csrEmail` VARCHAR(100) CHARSET utf8 COLLATE utf8_general_ci DEFAULT 'info@picsauditing.com'   NULL  AFTER `csrFax`,
  ADD COLUMN `csrAddress` VARCHAR(50) NULL AFTER `csrEmail`,
  ADD COLUMN `csrCity` VARCHAR(30) NULL AFTER `csrAddress`,
  ADD COLUMN `csrCountrySubdivision` VARCHAR(10) NULL AFTER `csrCity`,
  ADD COLUMN `csrZip` VARCHAR(15) NULL AFTER `csrCountrySubdivision`,
  CHANGE `salesPhone` `isrPhone` VARCHAR(30) CHARSET utf8 COLLATE utf8_general_ci NULL,
  ADD COLUMN `isrFax` VARCHAR(30) NULL AFTER `isrPhone`,
  ADD COLUMN `isrEmail` VARCHAR(100) NULL AFTER `isrFax`,
  ADD COLUMN `isrAddress` VARCHAR(50) NULL AFTER `isrEmail`,
  ADD COLUMN `isrCity` VARCHAR(30) NULL AFTER `isrAddress`,
  ADD COLUMN `isrCountrySubdivision` VARCHAR(10) NULL AFTER `isrCity`,
  ADD COLUMN `isrZip` VARCHAR(15) NULL AFTER `isrCountrySubdivision`;
