package com.picsauditing.jpa.entities;
// Generated Nov 15, 2007 2:20:12 PM by Hibernate Tools 3.2.0.b11


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * AccountReport generated by hbm2java
 */
@Entity
@Table(name="accounts"
)
public class AccountReport  implements java.io.Serializable {


     private Integer id;
     private String type;
     private String name;
     private ContractorInfoReport contractor;
     private char active;

    public AccountReport() {
    }

    public AccountReport(String type, String name, ContractorInfoReport contractor, char active) {
       this.type = type;
       this.name = name;
       this.contractor = contractor;
       this.active = active;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    
    @Column(name="type", nullable=false, length=20)
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    
    @Column(name="name", nullable=false, length=50)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id", nullable=false, insertable=false, updatable=false)
    public ContractorInfoReport getContractor() {
        return this.contractor;
    }
    
    public void setContractor(ContractorInfoReport contractor) {
        this.contractor = contractor;
    }
    
    @Column(name="active", nullable=false, length=1)
    public char getActive() {
        return this.active;
    }
    
    public void setActive(char active) {
        this.active = active;
    }




}


