package com.picsauditing.jpa.entities;
// Generated Nov 15, 2007 2:20:12 PM by Hibernate Tools 3.2.0.b11


import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Account generated by hbm2java
 */
@Entity
@Table(name="accounts"
)
public class Account  implements java.io.Serializable {


     private Integer id;
     private String type;
     private String name;
     private String username;
     private String password;
     private Date passwordChange;
     private Date lastLogin;
     private String contact;
     private String address;
     private String city;
     private String state;
     private String zip;
     private String phone;
     private String phone2;
     private String fax;
     private String email;
     private String webUrl;
     private String industry;
     private char active;
     private String createdBy;
     private Date dateCreated;
     private char seesAllB;
     private char sendActivationEmailB;
     private String activationEmailsB;
     private Date emailConfirmedDate;
     private List<GeneralContractor> generalContractors = new ArrayList<GeneralContractor>(0);
     private ContractorInfo contractorInfo;

    public Account() {
    }

	
    public Account(String type, String name, String username, String password, Date passwordChange, Date lastLogin, String contact, String address, String city, String state, String zip, String phone, String phone2, String fax, String email, String webUrl, String industry, char active, String createdBy, Date dateCreated, char seesAllB, char sendActivationEmailB, String activationEmailsB, Date emailConfirmedDate, ContractorInfo contractorInfo) {
        this.type = type;
        this.name = name;
        this.username = username;
        this.password = password;
        this.passwordChange = passwordChange;
        this.lastLogin = lastLogin;
        this.contact = contact;
        this.address = address;
        this.city = city;
        this.state = state;
        this.zip = zip;
        this.phone = phone;
        this.phone2 = phone2;
        this.fax = fax;
        this.email = email;
        this.webUrl = webUrl;
        this.industry = industry;
        this.active = active;
        this.createdBy = createdBy;
        this.dateCreated = dateCreated;
        this.seesAllB = seesAllB;
        this.sendActivationEmailB = sendActivationEmailB;
        this.activationEmailsB = activationEmailsB;
        this.emailConfirmedDate = emailConfirmedDate;
        this.contractorInfo = contractorInfo;
    }
    public Account(String type, String name, String username, String password, Date passwordChange, Date lastLogin, String contact, String address, String city, String state, String zip, String phone, String phone2, String fax, String email, String webUrl, String industry, char active, String createdBy, Date dateCreated, char seesAllB, char sendActivationEmailB, String activationEmailsB, Date emailConfirmedDate, List<GeneralContractor> generalContractors, ContractorInfo contractorInfo) {
       this.type = type;
       this.name = name;
       this.username = username;
       this.password = password;
       this.passwordChange = passwordChange;
       this.lastLogin = lastLogin;
       this.contact = contact;
       this.address = address;
       this.city = city;
       this.state = state;
       this.zip = zip;
       this.phone = phone;
       this.phone2 = phone2;
       this.fax = fax;
       this.email = email;
       this.webUrl = webUrl;
       this.industry = industry;
       this.active = active;
       this.createdBy = createdBy;
       this.dateCreated = dateCreated;
       this.seesAllB = seesAllB;
       this.sendActivationEmailB = sendActivationEmailB;
       this.activationEmailsB = activationEmailsB;
       this.emailConfirmedDate = emailConfirmedDate;
       this.generalContractors = generalContractors;
       this.contractorInfo = contractorInfo;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    
    @Column(name="type", nullable=false, length=20)
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    
    @Column(name="name", nullable=false, length=50)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    
    @Column(name="username", unique=true, nullable=false, length=50)
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    
    @Column(name="password", nullable=false, length=50)
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="passwordChange", nullable=false, length=10)
    public Date getPasswordChange() {
        return this.passwordChange;
    }
    
    public void setPasswordChange(Date passwordChange) {
        this.passwordChange = passwordChange;
    }
    
    @Column(name="lastLogin", nullable=false, length=19)
    public Date getLastLogin() {
        return this.lastLogin;
    }
    
    public void setLastLogin(Date lastLogin) {
        this.lastLogin = lastLogin;
    }
    
    @Column(name="contact", nullable=false, length=50)
    public String getContact() {
        return this.contact;
    }
    
    public void setContact(String contact) {
        this.contact = contact;
    }
    
    @Column(name="address", nullable=false, length=50)
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    
    @Column(name="city", nullable=false, length=50)
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }
    
    @Column(name="state", nullable=false, length=2)
    public String getState() {
        return this.state;
    }
    
    public void setState(String state) {
        this.state = state;
    }
    
    @Column(name="zip", nullable=false, length=50)
    public String getZip() {
        return this.zip;
    }
    
    public void setZip(String zip) {
        this.zip = zip;
    }
    
    @Column(name="phone", nullable=false, length=50)
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }
    
    @Column(name="phone2", nullable=false, length=50)
    public String getPhone2() {
        return this.phone2;
    }
    
    public void setPhone2(String phone2) {
        this.phone2 = phone2;
    }
    
    @Column(name="fax", nullable=false, length=20)
    public String getFax() {
        return this.fax;
    }
    
    public void setFax(String fax) {
        this.fax = fax;
    }
    
    @Column(name="email", nullable=false, length=50)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    
    @Column(name="web_URL", nullable=false, length=50)
    public String getWebUrl() {
        return this.webUrl;
    }
    
    public void setWebUrl(String webUrl) {
        this.webUrl = webUrl;
    }
    
    @Column(name="industry", nullable=false, length=50)
    public String getIndustry() {
        return this.industry;
    }
    
    public void setIndustry(String industry) {
        this.industry = industry;
    }
    
    @Column(name="active", nullable=false, length=1)
    public char getActive() {
        return this.active;
    }
    
    public void setActive(char active) {
        this.active = active;
    }
    
    @Column(name="createdBy", nullable=false, length=10)
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="dateCreated", nullable=false, length=10)
    public Date getDateCreated() {
        return this.dateCreated;
    }
    
    public void setDateCreated(Date dateCreated) {
        this.dateCreated = dateCreated;
    }
    
    @Column(name="seesAll_B", nullable=false, length=1)
    public char getSeesAllB() {
        return this.seesAllB;
    }
    
    public void setSeesAllB(char seesAllB) {
        this.seesAllB = seesAllB;
    }
    
    @Column(name="sendActivationEmail_B", nullable=false, length=1)
    public char getSendActivationEmailB() {
        return this.sendActivationEmailB;
    }
    
    public void setSendActivationEmailB(char sendActivationEmailB) {
        this.sendActivationEmailB = sendActivationEmailB;
    }
    
    @Column(name="activationEmails_B", nullable=false, length=155)
    public String getActivationEmailsB() {
        return this.activationEmailsB;
    }
    
    public void setActivationEmailsB(String activationEmailsB) {
        this.activationEmailsB = activationEmailsB;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="emailConfirmedDate", nullable=false, length=10)
    public Date getEmailConfirmedDate() {
        return this.emailConfirmedDate;
    }
    
    public void setEmailConfirmedDate(Date emailConfirmedDate) {
        this.emailConfirmedDate = emailConfirmedDate;
    }
@OneToMany(fetch=FetchType.LAZY, mappedBy="account")
    public List<GeneralContractor> getGeneralContractors() {
        return this.generalContractors;
    }
    
    public void setGeneralContractors(List<GeneralContractor> generalContractors) {
        this.generalContractors = generalContractors;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id", nullable=false, insertable=false, updatable=false)
    public ContractorInfo getContractorInfo() {
        return this.contractorInfo;
    }
    
    public void setContractorInfo(ContractorInfo contractorInfo) {
        this.contractorInfo = contractorInfo;
    }




}


