package com.picsauditing.jpa.entities;
// Generated Nov 15, 2007 2:20:12 PM by Hibernate Tools 3.2.0.b11


import java.util.ArrayList;
import java.util.Collection;
import java.util.List;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.hibernate.annotations.Where;



/**
 * ContractorInfoReport generated by hbm2java
 */
@Entity
@Table(name="contractor_info"
)
public class ContractorInfoReport  implements java.io.Serializable {


     private int id;
     private AccountReport account;
     private Collection<OshaLogReport> oshaLogs = new ArrayList<OshaLogReport>(0);
     private List<PqfLogReport> emrLogs = new ArrayList<PqfLogReport>(0);

    public ContractorInfoReport() {
    }

	
    public ContractorInfoReport(int id, AccountReport account) {
        this.id = id;
        this.account = account;
    }
    public ContractorInfoReport(int id, AccountReport account, Collection<OshaLogReport> oshaLogs, List<PqfLogReport> emrLogs) {
       this.id = id;
       this.account = account;
       this.oshaLogs = oshaLogs;
       this.emrLogs = emrLogs;
    }
   
     @Id 
    
    @Column(name="id", nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id", nullable=false, insertable=false, updatable=false)
    public AccountReport getAccount() {
        return this.account;
    }
    
    public void setAccount(AccountReport account) {
        this.account = account;
    }
@OneToMany(fetch=FetchType.LAZY, mappedBy="contractorInfo")
    public Collection<OshaLogReport> getOshaLogs() {
        return this.oshaLogs;
    }
    
    public void setOshaLogs(Collection<OshaLogReport> oshaLogs) {
        this.oshaLogs = oshaLogs;
    }
//@OneToMany(fetch=FetchType.LAZY, mappedBy="contractorInfoReport")
    @OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY)
    @JoinColumn(name="conID")
     //@Where(clause="questionID=126 or questionID=889 or questionID=1519")
    @Where(clause="questionID in (126,889,1519)")
    public List<PqfLogReport> getEmrLogs() {
        return this.emrLogs;
    }
    
    public void setEmrLogs(List<PqfLogReport> emrLogs) {
        this.emrLogs = emrLogs;
    }




}


