package com.picsauditing.jpa.entities;
// Generated Nov 15, 2007 2:20:12 PM by Hibernate Tools 3.2.0.b11


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * GeneralContractorId generated by hbm2java
 */
@Embeddable
public class GeneralContractorId  implements java.io.Serializable {


     private int subId;
     private int genId;

    public GeneralContractorId() {
    }

    public GeneralContractorId(int subId, int genId) {
       this.subId = subId;
       this.genId = genId;
    }
   

    @Column(name="subID", nullable=false)
    public int getSubId() {
        return this.subId;
    }
    
    public void setSubId(int subId) {
        this.subId = subId;
    }

    @Column(name="genID", nullable=false)
    public int getGenId() {
        return this.genId;
    }
    
    public void setGenId(int genId) {
        this.genId = genId;
    }




}


