package com.picsauditing.jpa.entities;
// Generated Nov 15, 2007 2:20:12 PM by Hibernate Tools 3.2.0.b11


import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQuery;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * GeneralContractor generated by hbm2java
 */
@Entity
@NamedQuery(name="contractorsByOperator", query="select gc.contractorInfo from GeneralContractor gc where gc.id.genId=:genId")

@Table(name="generalcontractors"
)
public class GeneralContractor  implements java.io.Serializable {


     private GeneralContractorId id;
     private Account account;
     private ContractorInfoReport contractorInfo;
     private Date dateAdded;

    public GeneralContractor() {
    }

    public GeneralContractor(GeneralContractorId id, Account account, ContractorInfoReport contractorInfo, Date dateAdded) {
       this.id = id;
       this.account = account;
       this.contractorInfo = contractorInfo;
       this.dateAdded = dateAdded;
    }
   
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="subId", column=@Column(name="subID", nullable=false) ), 
        @AttributeOverride(name="genId", column=@Column(name="genID", nullable=false) ) } )
    public GeneralContractorId getId() {
        return this.id;
    }
    
    public void setId(GeneralContractorId id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="genID", nullable=false, insertable=false, updatable=false)
    public Account getAccount() {
        return this.account;
    }
    
    public void setAccount(Account account) {
        this.account = account;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="subID", nullable=false, insertable=false, updatable=false)
    public ContractorInfoReport getContractorInfo() {
        return this.contractorInfo;
    }
    
    public void setContractorInfo(ContractorInfoReport contractorInfo) {
        this.contractorInfo = contractorInfo;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="dateAdded", nullable=false, length=10)
    public Date getDateAdded() {
        return this.dateAdded;
    }
    
    public void setDateAdded(Date dateAdded) {
        this.dateAdded = dateAdded;
    }




}


