/**
 *
 *
 * User: APhatarphekar
 * Date: 6/23/2014
 * Time: 10:25 AM
 *
 */
package com.picsauditing.employeeguard.models.operations;

public enum MOperations {
	COPY_ID, COPY_NAME, COPY_ACCOUNT_ID, ATTACH_REQD_SKILLS, EVAL_EMPLOYEE_COUNT, EVAL_OVERALL_STATUS_ONLY, EVAL_OVERALL_STATUS, EVAL_ALL_SKILLS_STATUS, ATTACH_DOCUMENTATION, ATTACH_SKILLS, ATTACH_ROLES,ATTACH_ROLE, ATTACH_GROUPS, ATTACH_PROJECTS, ATTACH_SITES, ATTACH_CORPORATES, ATTACH_CONTRACTORS, ATTACH_CONTRACTOR, ATTACH_CONTRACTOR_EMPLOYEES, EVAL_ASSIGNMENT_STATUS, COPY_FIRST_NAME, COPY_LAST_NAME, COPY_TITLE, ENABLE_ASSIGNMENT_FLAG
}
