package com.picsauditing.rbic
dialect "java"

import com.picsauditing.rbic.ContractorModel;
import com.picsauditing.jpa.entities.LowMedHigh;

rule "highRisk"
    when
        $con : ContractorModel(safetyRisk == LowMedHigh.High)
    then
        $con.updateCriteriaLimitForContractor(526, 13726, 1000000);
        $con.updateCriteriaLimitForContractor(521, 13726, 5000000);
    end

rule "medRisk"
    when
        $con : ContractorModel(safetyRisk == LowMedHigh.Med)
    then
        $con.updateCriteriaLimitForContractor(526, 13726, 1000000);
        $con.updateCriteriaLimitForContractor(521, 13726, 2000000);
    end

rule "lowRisk"
    when
        $con : ContractorModel(safetyRisk == LowMedHigh.Low)
    then
        $con.updateCriteriaLimitForContractor(526, 13726, 1000000);
        $con.updateCriteriaLimitForContractor(802, 13726, 2000000);
    end