package com.picsauditing.rbic
dialect "java"

import com.picsauditing.rbic.ContractorModel;
import com.picsauditing.jpa.entities.LowMedHigh;

rule "highRisk"
    when
        $con : ContractorModel(safetyRisk == LowMedHigh.High)
    then
        $con.updateCriteriaLimitForContractor(802, 34877, 3000000);
        $con.updateCriteriaLimitForContractor(523, 34877, 3000000);
        $con.updateCriteriaLimitForContractor(541, 34877, 3000000);
    end

rule "medRisk"
    when
        $con : ContractorModel(safetyRisk == LowMedHigh.Med)
    then
        $con.updateCriteriaLimitForContractor(802, 34877, 2000000);
        $con.updateCriteriaLimitForContractor(523, 34877, 2000000);
        $con.updateCriteriaLimitForContractor(541, 34877, 2000000);
    end

rule "lowRisk"
    when
        $con : ContractorModel(safetyRisk == LowMedHigh.Low)
    then
        $con.updateCriteriaLimitForContractor(802, 34877, 1000000);
        $con.updateCriteriaLimitForContractor(523, 34877, 1000000);
        $con.updateCriteriaLimitForContractor(541, 34877, 1000000);
    end
