package com.picsauditing.rbic
dialect "java"

import com.picsauditing.rbic.ContractorModel;
import com.picsauditing.jpa.entities.LowMedHigh;

rule "category1Tag"
    when
        $con : ContractorModel(hasTag(372))
    then
        $con.updateCriteriaLimitForContractor(521, 7727, 4000000);
    end

rule "category2Tag"
    when
        $con : ContractorModel(hasTag(373))
    then
        $con.updateCriteriaLimitForContractor(521, 7727, 1000000);
    end

rule "category3Tag"
    when
        $con : ContractorModel(hasTag(374))
    then
        $con.updateCriteriaLimitForContractor(521, 7727, 1000000);
    end

rule "default"
    when
        $con : ContractorModel(hasTag(374))
    then
        $con.updateCriteriaLimitForContractor(521, 7727, 1000000);
    end