<%@ taglib prefix="s" uri="/struts-tags" %>

<h1>Hello World</h1>
        
<link rel="stylesheet" type="text/css" media="screen" href="js/jquery/tagit/jquery.tagit.css" />
<script type="text/javascript" src="js/jquery/tagit/jquery.tagit.js"></script>

<label for="tag" style="float: left;">Tag:</label>
<input id="tag" type="text" name="auditName" style="width: 400px" />

<script>
$(document).ready(function () {
    $('#tag').tagit({
        source: [
             {id: 'AD',value: 'Andorra'}, 
             {id: 'AE',value: 'United Arab Emirates'}, 
             {id: 'AF',value: 'Afganistan'}, 
             {id: 'AG',value: 'Antigua and Barbuda'}, 
             {id: 'AI',value: 'Anguila'}, 
             {id: 'AL',value: 'Albania'}, 
             {id: 'AM',value: 'Armenia'}, 
             {id: 'AN',value: 'Netherlands Antilles'}, 
             {id: 'AO',value: 'Angola'}, 
             {id: 'AQ',value: 'Antarctica'}, 
             {id: 'AR',value: 'Argentina'}, 
             {id: 'AS',value: 'American Samoa'}, 
             {id: 'AT',value: 'Austria'}, 
             {id: 'AU',value: 'Australia'}, 
             {id: 'AW',value: 'Aruba'}, 
             {id: 'AX',value: 'Aland Islands'}, 
             {id: 'AZ',value: 'Azerbaijan'}, 
             {id: 'BA',value: 'Bosnia and Herzegovina'}, 
             {id: 'BB',value: 'Barbados'}, 
             {id: 'BD',value: 'Bangladesh'}, 
             {id: 'BE',value: 'Belgium'}, 
             {id: 'BF',value: 'Burkina Faso'}, 
             {id: 'BG',value: 'Bulgaria'}, 
             {id: 'BH',value: 'Bahrain'}, 
             {id: 'BI',value: 'Burundi'}, 
             {id: 'BJ',value: 'Benin'}, 
             {id: 'BL',value: 'Saint Barthelemy'}, 
             {id: 'BM',value: 'Bermuda'}, 
             {id: 'BN',value: 'Brunei Darussalam'}, 
             {id: 'BO',value: 'Bolivia'}, 
             {id: 'BR',value: 'Brazil'}, 
             {id: 'BS',value: 'Bahamas'}, 
             {id: 'BT',value: 'Bhutan'}, 
             {id: 'BV',value: 'Bouvet Island'}, 
             {id: 'BW',value: 'Botswana'}, 
             {id: 'BY',value: 'Belarus'}, 
             {id: 'BZ',value: 'Belize'}, 
             {id: 'CA',value: 'Canada'}, 
             {id: 'CC',value: 'Cocos (Keeling) Islands'}, 
             {id: 'CD',value: 'Congo, Democratic Republic of the'}, 
             {id: 'CF',value: 'Central African Republic'}, 
             {id: 'CG',value: 'Congo, Republic of the'}, 
             {id: 'CH',value: 'Switzerland'}, 
             {id: 'CI',value: 'Cote dIvoire'}, 
             {id: 'CK',value: 'Cook Islands'}, 
             {id: 'CL',value: 'Chile'}, 
             {id: 'CM',value: 'Cameroon'}, 
             {id: 'CN',value: 'China'}, 
             {id: 'CO',value: 'Colombia'}, 
             {id: 'CR',value: 'Costa Rica'}, 
             {id: 'CU',value: 'Cuba'}, 
             {id: 'CV',value: 'Cape Verde'}, 
             {id: 'CX',value: 'Christmas Island'}, 
             {id: 'CY',value: 'Cyprus'}, 
             {id: 'CZ',value: 'Czech Republic'}, 
             {id: 'DE',value: 'Germany'}, 
             {id: 'DJ',value: 'Djibouti'}, 
             {id: 'DK',value: 'Denmark'}, 
             {id: 'DM',value: 'Dominica'}, 
             {id: 'DO',value: 'Dominican Republic'}, 
             {id: 'DZ',value: 'Algeria'}, 
             {id: 'EC',value: 'Ecuador'}, 
             {id: 'EE',value: 'Estonia'}, 
             {id: 'EG',value: 'Egypt'}, 
             {id: 'EH',value: 'Western Sahara'}, 
             {id: 'ER',value: 'Eritrea'}, 
             {id: 'ES',value: 'Spain'}, 
             {id: 'ET',value: 'Ethiopia'}, 
             {id: 'FI',value: 'Finland'}, 
             {id: 'FJ',value: 'Fiji'}, 
             {id: 'FK',value: 'Falkland Islands'}, 
             {id: 'FM',value: 'Micronesia'}, 
             {id: 'FO',value: 'Faroe Islands'}, 
             {id: 'FR',value: 'France'}, 
             {id: 'GA',value: 'Gabon'}, 
             {id: 'GB',value: 'United Kingdom'}, 
             {id: 'GD',value: 'Grenada'}, 
             {id: 'GE',value: 'Georgia'}, 
             {id: 'GF',value: 'French Guiana'}, 
             {id: 'GG',value: 'Guernsey'}, 
             {id: 'GH',value: 'Ghana'}, 
             {id: 'GI',value: 'Gibraltar'}, 
             {id: 'GL',value: 'Greenland'}, 
             {id: 'GM',value: 'Gambia'}, 
             {id: 'GN',value: 'Guinea'}, 
             {id: 'GP',value: 'Guadeloupe'}, 
             {id: 'GQ',value: 'Equatorial Guinea'}, 
             {id: 'GR',value: 'Greece'}, 
             {id: 'GS',value: 'South Georgia & Sandwich Islands'}, 
             {id: 'GT',value: 'Guatemala'}, 
             {id: 'GU',value: 'Guam'}, 
             {id: 'GW',value: 'Guinea-Bissau'}, 
             {id: 'GY',value: 'Guyana'}, 
             {id: 'HK',value: 'Hong Kong'}, 
             {id: 'HM',value: 'Heard Island and McDonald Islands'}, 
             {id: 'HN',value: 'Honduras'}, 
             {id: 'HR',value: 'Croatia'}, 
             {id: 'HT',value: 'Haiti'}, 
             {id: 'HU',value: 'Hungary'}, 
             {id: 'ID',value: 'Indonesia'}, 
             {id: 'IE',value: 'Ireland'}, 
             {id: 'IL',value: 'Israel'}, 
             {id: 'IM',value: 'Isle of Man'}, 
             {id: 'IN',value: 'India'}, 
             {id: 'IO',value: 'British Indian Ocean Territory'}, 
             {id: 'IQ',value: 'Iraq'}, 
             {id: 'IR',value: 'Iran'}, 
             {id: 'IS',value: 'Iceland'}, 
             {id: 'IT',value: 'Italy'}, 
             {id: 'JE',value: 'Jersey'}, 
             {id: 'JM',value: 'Jamaica'}, 
             {id: 'JO',value: 'Jordan'}, 
             {id: 'JP',value: 'Japan'}, 
             {id: 'KE',value: 'Kenya'}, 
             {id: 'KG',value: 'Kyrgyzstan'}, 
             {id: 'KH',value: 'Cambodia'}, 
             {id: 'KI',value: 'Kiribati'}, 
             {id: 'KM',value: 'Comoros'}, 
             {id: 'KN',value: 'Saint Kitts and Nevis'}, 
             {id: 'KP',value: 'Korea (North)'}, 
             {id: 'KR',value: 'Korea (South)'}, 
             {id: 'KW',value: 'Kuwait'}, 
             {id: 'KY',value: 'Cayman Islands'}, 
             {id: 'KZ',value: 'Kazakhstan'}, 
             {id: 'LA',value: 'Laos'}, 
             {id: 'LB',value: 'Lebanon'}, 
             {id: 'LC',value: 'Saint Lucia'}, 
             {id: 'LI',value: 'Liechtenstein'}, 
             {id: 'LK',value: 'Sri Lanka'}, 
             {id: 'LR',value: 'Liberia'}, 
             {id: 'LS',value: 'Lesotho'}, 
             {id: 'LT',value: 'Lithuania'}, 
             {id: 'LU',value: 'Luxembourg'}, 
             {id: 'LV',value: 'Latvia'}, 
             {id: 'LY',value: 'Libya'}, 
             {id: 'MA',value: 'Morocco'}, 
             {id: 'MC',value: 'Monaco'}, 
             {id: 'MD',value: 'Moldova'}, 
             {id: 'ME',value: 'Montenegro'}, 
             {id: 'MF',value: 'Saint Martin'}, 
             {id: 'MG',value: 'Madagascar'}, 
             {id: 'MH',value: 'Marshall Islands'}, 
             {id: 'MK',value: 'Macedonia'}, 
             {id: 'ML',value: 'Mali'}, 
             {id: 'MM',value: 'Myanmar'}, 
             {id: 'MN',value: 'Mongolia'}, 
             {id: 'MO',value: 'Macao'}, 
             {id: 'MP',value: 'Northern Mariana Islands'}, 
             {id: 'MQ',value: 'Martinique'}, 
             {id: 'MR',value: 'Mauritania'}, 
             {id: 'MS',value: 'Montserrat'}, 
             {id: 'MT',value: 'Malta'}, 
             {id: 'MU',value: 'Mauritius'}, 
             {id: 'MV',value: 'Maldives'}, 
             {id: 'MW',value: 'Malawi'}, 
             {id: 'MX',value: 'Mexico'}, 
             {id: 'MY',value: 'Malaysia'}, 
             {id: 'MZ',value: 'Mozambique'}, 
             {id: 'NA',value: 'Namibia'}, 
             {id: 'NC',value: 'New Caledonia'}, 
             {id: 'NE',value: 'Niger'}, 
             {id: 'NF',value: 'Norfolk Island'}, 
             {id: 'NG',value: 'Nigeria'}, 
             {id: 'NI',value: 'Nicaragua'}, 
             {id: 'NL',value: 'Netherlands'}, 
             {id: 'NO',value: 'Norway'}, 
             {id: 'NP',value: 'Nepal'}, 
             {id: 'NR',value: 'Nauru'}, 
             {id: 'NU',value: 'Niue'}, 
             {id: 'NZ',value: 'New Zealand'}, 
             {id: 'OM',value: 'Oman'}, 
             {id: 'PA',value: 'Panama'}, 
             {id: 'PE',value: 'Peru'}, 
             {id: 'PF',value: 'French Polynesia'}, 
             {id: 'PG',value: 'Papua New Guinea'}, 
             {id: 'PH',value: 'Philippines'}, 
             {id: 'PK',value: 'Pakistan'}, 
             {id: 'PL',value: 'Poland'}, 
             {id: 'PM',value: 'Saint Pierre and Miquelon'}, 
             {id: 'PN',value: 'Pitcairn'}, 
             {id: 'PR',value: 'Puerto Rico'}, 
             {id: 'PS',value: 'Palestinian Territories'}, 
             {id: 'PT',value: 'Portugal'}, 
             {id: 'PW',value: 'Palau'}, 
             {id: 'PY',value: 'Paraguay'}, 
             {id: 'QA',value: 'Qatar'}, 
             {id: 'RE',value: 'Reunion'}, 
             {id: 'RO',value: 'Romania'}, 
             {id: 'RS',value: 'Serbia'}, 
             {id: 'RU',value: 'Russia'}, 
             {id: 'RW',value: 'Rwanda'}, 
             {id: 'SA',value: 'Saudi Arabia'}, 
             {id: 'SB',value: 'Solomon Islands'}, 
             {id: 'SC',value: 'Seychelles'}, 
             {id: 'SD',value: 'Sudan'}, 
             {id: 'SE',value: 'Sweden'}, 
             {id: 'SG',value: 'Singapore'}, 
             {id: 'SH',value: 'Saint Helena'}, 
             {id: 'SI',value: 'Slovenia'}, 
             {id: 'SJ',value: 'Svalbard and Jan Mayen'}, 
             {id: 'SK',value: 'Slovakia'}, 
             {id: 'SL',value: 'Sierra Leone'}, 
             {id: 'SM',value: 'San Marino'}, 
             {id: 'SN',value: 'Senegal'}, 
             {id: 'SO',value: 'Somalia'}, 
             {id: 'SR',value: 'Suriname'}, 
             {id: 'ST',value: 'Sao Tome and Principe'}, 
             {id: 'SV',value: 'El Salvador'}, 
             {id: 'SY',value: 'Syrian Arab Republic'}, 
             {id: 'SZ',value: 'Swaziland'}, 
             {id: 'TC',value: 'Turks and Caicos Islands'}, 
             {id: 'TD',value: 'Chad'}, 
             {id: 'TF',value: 'French Southern Territories'}, 
             {id: 'TG',value: 'Togo'}, 
             {id: 'TH',value: 'Thailand'}, 
             {id: 'TJ',value: 'Tajikistan'}, 
             {id: 'TK',value: 'Tokelau'}, 
             {id: 'TL',value: 'Timor-Leste'}, 
             {id: 'TM',value: 'Turkmenistan'}, 
             {id: 'TN',value: 'Tunisia'}, 
             {id: 'TO',value: 'Tonga'}, 
             {id: 'TR',value: 'Turkey'}, 
             {id: 'TT',value: 'Trinidad and Tobago'}, 
             {id: 'TV',value: 'Tuvalu'}, 
             {id: 'TW',value: 'Taiwan'}, 
             {id: 'TZ',value: 'Tanzania'}, 
             {id: 'UA',value: 'Ukraine'}, 
             {id: 'UG',value: 'Uganda'}, 
             {id: 'UM',value: 'United States Minor Islands'}, 
             {id: 'US',value: 'United States'}, 
             {id: 'UY',value: 'Uruguay'}, 
             {id: 'UZ',value: 'Uzbekistan'}, 
             {id: 'VA',value: 'Holy See'}, 
             {id: 'VC',value: 'Saint Vincent and the Grenadines'}, 
             {id: 'VE',value: 'Venezuela'}, 
             {id: 'VG',value: 'British Virgin Islands'}, 
             {id: 'VI',value: 'United States Virgin Islands'}, 
             {id: 'VN',value: 'Vietnam'}, 
             {id: 'VU',value: 'Vanuatu'}, 
             {id: 'WF',value: 'Wallis and Futuna'}, 
             {id: 'WS',value: 'Samoa'}, 
             {id: 'YE',value: 'Yemen'}, 
             {id: 'YT',value: 'Mayotte'}, 
             {id: 'ZA',value: 'South Africa'}, 
             {id: 'ZM',value: 'Zambia'}, 
             {id: 'ZW',value: 'Zimbabwe'}
         ]
    });
});
</script>